Repository kubeshop/monokle, pull requests merged in 2022-10, with the labels that each got.

#2474 [Snyk] Upgrade @kubernetes/client-node from 0.17.0 to 0.17.1
  package-lock.json
  package.json
Labels: size/XS

#2473 [Snyk] Upgrade antd from 4.22.8 to 4.23.1
  package-lock.json
  package.json
  src/App.tsx
  src/components/atoms/TableSelect/TableSelect.tsx
  src/components/molecules/FilterPopover/FilterPopover.tsx
  src/components/molecules/HelmChartModalConfirmWithNamespaceSelect/HelmChartModalConfirmWithNamespaceSelect.tsx
  src/components/molecules/ModalConfirm/ModalConfirm.tsx
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
  src/components/molecules/Walkthrough/Walkthrough.tsx
  src/components/organisms/AboutModal/AboutModal.tsx
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ActionsPane/Scale/Scale.tsx
  src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/CompareModal/CompareModal.tsx
  src/components/organisms/CreateFileFolderModal/CreateFileFolderModal.tsx
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/FiltersPresetModal/FiltersPresetModal.tsx
  src/components/organisms/FormEditorModal/FormEditorModal.tsx
  src/components/organisms/GitPane/CommitModal.tsx
  src/components/organisms/KeyboardShortcuts/KeyboardShortcuts.tsx
  src/components/organisms/LazyDrawer/LazyDrawer.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/components/organisms/PluginManager/PluginInstallModal.tsx
  src/components/organisms/QuickSearchActions/QuickSearchActions.tsx
  src/components/organisms/RenameEntityModal/RenameEntityModal.tsx
  src/components/organisms/RenameResourceModal/RenameResourceModal.tsx
  src/components/organisms/ReplaceImageModal/ReplaceImageModal.tsx
  src/components/organisms/SearchPane/SearchPane.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/SettingsManager/styled.tsx
  src/components/organisms/StartProjectPane/RecentProject.tsx
Labels: size/XL

#2476 fix: monaco editor hide scroll
  package-lock.json
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
Labels: size/S

#2477 chore(release): 1.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#2499 fix: local branches by default
  src/components/molecules/BranchSelect/BranchTable.tsx
Labels: size/S

#2488 feat: compare branches commits
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  electron/app/ipc/ipcListeners.ts
  src/App.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/CompareModal/CompareModalSelecting.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/GitBranchSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/GitCommitSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/GitSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/index.ts
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmValuesOrConfigSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelectColor.styled.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx
  src/components/organisms/GitPane/BottomActions.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/LazyDrawer/LazyDrawer.tsx
  src/components/organisms/PageHeader/CreateProject.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.styled.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
  src/constants/tooltips.tsx
  src/models/git.ts
  src/redux/compare/selectors.ts
  src/redux/compare/state.ts
  src/redux/compare/utils.ts
  src/redux/git/git.initialState.ts
  src/redux/git/git.slice.ts
  src/redux/services/compare/fetchResources.ts
  src/redux/services/gitFolderMonitor.ts
  src/redux/thunks/multiplePathsChanged.ts
  src/utils/git.ts
Labels: size/XL

#2502 fix: double scroll
  src/components/organisms/PaneManager/PaneManager.tsx
Labels: size/XS

#2501 Update resource-validation.md
  docs/resource-validation.md
Labels: size/S

#2508 refactor: git clone modal
  electron/app/git/git.ts
  src/App.tsx
  src/components/organisms/GitCloneModal/GitCloneModal.tsx
  src/components/organisms/GitCloneModal/index.ts
  src/components/organisms/PageHeader/CreateProject.tsx
  src/components/organisms/PageHeader/GitCloneModal.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
  src/components/organisms/index.ts
  src/constants/constants.ts
  src/models/git.ts
  src/redux/git/git.initialState.ts
  src/redux/git/git.slice.ts
Labels: size/L

#2509 refactor: cluster selection size
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
Labels: size/S

#2506 [Snyk] Upgrade xterm-addon-fit from 0.5.0 to 0.6.0
  package-lock.json
  package.json
Labels: size/XS

#2512 fix: handle clone errors
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/organisms/GitCloneModal/GitCloneModal.tsx
Labels: size/S

#2514 fix: set left menu selection to file explorer when opening project
  src/redux/reducers/appConfig.ts
Labels: size/XS

#2516 fix: get new content of the file when modifying resource
  src/redux/services/fileEntry.ts
Labels: size/S

#2517 refactor: highlight row for comparing resources
  src/components/organisms/CompareModal/ComparisonList.styled.tsx
Labels: size/XS

#2519 disable UI tests on PRs
  .github/workflows/monokle-ui-tests.yml
Labels: size/XS

#2520 [Snyk] Upgrade git-url-parse from 13.0.0 to 13.1.0
  package-lock.json
  package.json
Labels: size/XS

#2522 [Snyk] Upgrade simple-git from 3.14.0 to 3.14.1
  package-lock.json
  package.json
Labels: size/XS

#2521 [Snyk] Upgrade antd from 4.23.1 to 4.23.2
  package-lock.json
  package.json
Labels: size/XS

#2529 fix: filtered kustomizations/helms/files
  src/components/molecules/ContextMenu/ContextMenu.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
  src/components/organisms/FileTreePane/CreateNode.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/FileTreePane/styled.tsx
  src/components/organisms/FileTreePane/types.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/hooks/fileTreeHooks/useFileSelect.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenuWrapper.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartQuickAction.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenu.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenuWrapper.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationQuickAction.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts
Labels: size/L

#2533 feat: modal for creating new resource from CRD
  src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDItem.styled.tsx
  src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDItem.tsx
  src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDsSchemaValidation.tsx
Labels: size/M

#2534 Update CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#2536 fix: remove unnecessary p closing tag
  README.md
Labels: size/XS

#2537 fix: use div
  README.md
Labels: size/S

#2542 fix: form editor scrollbar
  src/components/molecules/FormEditor/FormEditor.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/FileTreePane/types.tsx
Labels: size/S

#2548 fix: logs scrollbar
  src/components/molecules/Logs/Logs.styled.ts
Labels: size/XS

#2553 feat: enable sync button
  src/components/organisms/GitPane/BottomActions.tsx
Labels: size/XS

#2546 feat: deploy diff actions
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/ActionsPane/Diff/Diff.tsx
  src/components/organisms/ActionsPane/InstallDeploy/InstallDeploy.tsx
  src/hooks/resourceHooks/index.ts
  src/hooks/resourceHooks/useDiff.ts
  src/hooks/resourceHooks/useInstallDeploy.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
Labels: size/L

#2549 refactor: collapse all folders but root
  src/components/organisms/FileTreePane/FileTreePane.tsx
Labels: size/XS

#2551 feat: discard changes for unstaged files
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/utils/files.ts
Labels: size/M

#2555 refactor: async git tasks on setRootFolder
  src/redux/git/git.slice.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/S

#2557 refactor: actions pane buttons
  src/components/organisms/ActionsPane/ActionsPaneHeader.styled.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/ActionsPane/Diff/Diff.tsx
  src/components/organisms/ActionsPane/InstallDeploy/InstallDeploy.tsx
  src/components/organisms/ActionsPane/Restart/Restart.tsx
  src/components/organisms/ActionsPane/Scale/Scale.tsx
Labels: size/M

#2559 refactor: improve set expanded folders
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/hooks/fileTreeHooks/useHighlightNode.ts
Labels: size/XS

#2527 Update schema versions for K8s
  resources/schemas/1.24.6.json
  src/constants/constants.ts
Labels: size/S

#2561 fix: set repo/changed files to initial
  src/redux/git/git.slice.ts
  src/redux/reducers/main.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/S

#2562 refactor: left panel
  src/components/atoms/Icon/Icons/Git.tsx
  src/components/atoms/Icon/Icons/GitOps.tsx
  src/components/atoms/Icon/Icons/OpenPolicyAgent.tsx
  src/components/atoms/Icon/Icons/Search.tsx
  src/components/atoms/Icon/Icons/Validation.tsx
  src/components/atoms/MonoPaneTitle/MonoPaneTitle.tsx
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PaneManager/MenuButton/MenuButton.styled.tsx
  src/components/organisms/PaneManager/MenuButton/MenuButton.tsx
  src/components/organisms/PaneManager/MenuButton/styled.ts
  src/components/organisms/PaneManager/MenuIcon.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.styled.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/constants/constants.ts
  src/styles/Colors.ts
Labels: size/L

#2568 chore(release): 1.11.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#2560 docs: Screenshot Updates for 1.11
  docs/creating-resources.md
  docs/file-explorer.md
  docs/helm.md
  docs/images.md
  docs/img/explorer-file-actions-1.11.png
  docs/img/explorer-folder-actions-1.11.png
  docs/img/helm-navigation-1.11.png
  docs/img/helm-preview-action-1.11.png
  docs/img/helm-preview-configurations-1.11.png
  docs/img/helm-preview-output-1.11.png
  docs/img/helm-preview-reload-1.11.png
  docs/img/helm-settings-1.11.png
  docs/img/helm-templates-1.11.png
  docs/img/helm-values-reference-1-11.png
  docs/img/invoke-kustomize-setting-1.11.png
  docs/img/kusk-preview-reload-1.11.png
  docs/img/kustomize-navigation-1.11.png
  docs/img/kustomize-outgoing-links-1.11.png
  docs/img/kustomize-preview-1.11.png
  docs/img/kustomize-preview-action-1.11.png
  docs/img/kustomize-preview-content-1.11.png
  docs/img/kustomize-settings-1.11.png
  docs/img/navigator-resource-check-box-1.11.png
  docs/img/navigator-resource-cluster-actions-1.11.png
  docs/img/navigator-resource-options-1.11.png
  docs/img/navigator-select-cluster-resources-1.11.png
  docs/img/navigator-unknown-resource-options-1.11.png
  docs/img/quick-filter-popup-1.11.png
  docs/img/recent-folders-1.11.png
  docs/img/rename-1.11.png
  docs/img/resource-crds-location-1.11.png
  docs/img/resource-filtering-1.11.png
  docs/img/resource-navigation-1-1.11.png
  docs/img/resource-navigation-2-1.11.png
  docs/img/select-and-manage-projects-1.11.png
  docs/img/select-multi-resource-1.11.png
  docs/img/source-editor-auto-complete-1.11.png
  docs/img/source-editor-context-hover-1.11.png
  docs/kustomize.md
  docs/projects.md
  docs/resource-crds.md
  docs/resource-editing.md
  docs/resource-navigation.md
  docs/working-with-multiple-resources.md
Labels: size/L

#2573 fix: disable side-by-side cta
  src/components/atoms/Icon/Icons/SplitView.tsx
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/M

#2572 fix: dispose only models not attached to any editor
  src/components/molecules/Monaco/Monaco.tsx
Labels: size/S

#2566 fix: image outgoing resources refs
  src/navsections/ImagesSectionBlueprint/ImageOutgoingResourcesPopover.tsx
Labels: size/XS

#2567 fix: show ellipsis + hover full name for project name
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
Labels: size/XS

#2575 feat: register CRDs from files
  src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDsSchemaValidation.styled.tsx
  src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDsSchemaValidation.tsx
Labels: size/L

#2576 feat: add close icon to drawers
  src/components/organisms/LazyDrawer/LazyDrawer.styled.tsx
  src/components/organisms/LazyDrawer/LazyDrawer.tsx
Labels: size/S

#2570 docs: Remaining Screenshot Updates
  docs/apply-and-diff.md
  docs/cluster-integration.md
  docs/compare-sync.md
  docs/img/add-new-plugin-1.11.png
  docs/img/cluster-compare-button-1.11.png
  docs/img/cluster-preview-1.11.png
  docs/img/cluster-preview2-1.11.png
  docs/img/cluster-selector-1.11.png
  docs/img/clusters-tab-1.11.png
  docs/img/default-templates-1.11.gif
  docs/img/diff-tble-8-1.11.png
  docs/img/kubeconfig-setting-1.11.png
  docs/img/open-plugin-manager-1.11.png
  docs/img/view-template-icon-1.11.png
  docs/plugins.md
  docs/templates.md
Labels: size/M

#2579 [Snyk] Upgrade react-redux from 8.0.2 to 8.0.4
  package-lock.json
  package.json
Labels: size/XS

#2581 feat: Remove Metadata tab, bring back to Form tab
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/kindhandlers/common/formLoader.ts
Labels: size/M

#2574 feat: preview any command
  src/components/molecules/CommandPreview/PreviewSavedCommand.tsx
  src/components/molecules/CommandPreview/SaveCommand.tsx
  src/components/molecules/CommandPreview/index.ts
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/models/appconfig.ts
  src/models/appstate.ts
  src/redux/reducers/main.ts
  src/redux/selectors.ts
  src/redux/services/preview.ts
  src/redux/services/previewCommand.ts
Labels: size/L

#2586 refactor: disable helm/kustomize in compare&sync
  src/components/organisms/CompareModal/ResourceSetSelector/ClusterContextSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/GitBranchSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmChartSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmValuesOrConfigSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/KustomizeSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx
Labels: size/M

#2558 feat: add loading for git tasks
  src/components/atoms/TableSelect/TableSelect.tsx
  src/components/molecules/BranchSelect/BranchSelect.tsx
  src/components/organisms/GitPane/BottomActions.tsx
  src/components/organisms/GitPane/CommitModal.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/GitPane/GitPane.styled.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/models/git.ts
  src/redux/git/git.initialState.ts
  src/redux/git/git.slice.ts
  src/redux/services/fileMonitor.ts
  src/redux/services/gitFolderMonitor.ts
  src/redux/thunks/multiplePathsAdded.ts
  src/redux/thunks/multiplePathsChanged.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/L

#2241 feat: macOS key icons for tooltips
  public/index.html
  src/components/molecules/HotkeyLabel/HotkeyLabel.styled.tsx
  src/components/molecules/HotkeyLabel/HotkeyLabel.tsx
  src/constants/tooltips.tsx
Labels: size/M

#2591 fix: enable deploy in cluster mode
  src/components/organisms/ActionsPane/ActionsPaneHeader.styled.tsx
  src/hooks/resourceHooks/useInstallDeploy.ts
Labels: size/S

#2593 fix: bring form buttons back
  src/components/molecules/FormEditor/FormArrayFieldTemplate.tsx
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/FormEditor/FormObjectFieldTemplate.tsx
Labels: size/S

#2592 feat: add editor placeholder
  src/assets/MonacoPlaceholderImage.svg
  src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.styled.tsx
  src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/SettingsManager/Settings.tsx
  src/models/appconfig.ts
  src/redux/reducers/appConfig.ts
  src/styles/Colors.ts
Labels: size/L

#2594 feat: git staged/unstaged same file
  electron/app/git/git.ts
  src/components/organisms/GitOpsView/GitView.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/redux/git/git.slice.ts
  src/redux/services/fileEntry.ts
  src/redux/thunks/multiplePathsChanged.ts
  src/utils/git.ts
Labels: size/L

#2595 feat: add git commit create date
  src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/GitCommitSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelectColor.styled.tsx
  src/utils/git.ts
Labels: size/S

#2600 [Snyk] Upgrade tiny-invariant from 1.2.0 to 1.3.1
  package-lock.json
  package.json
Labels: size/XS

#2601 [Snyk] Upgrade antd from 4.23.2 to 4.23.3
  package-lock.json
  package.json
Labels: size/XS

#2607 chore: increase width of Saved Command modal
  src/components/molecules/CommandPreview/SaveCommand.tsx
Labels: size/XS

#2608 refactor: compare & sync
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/Compare.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/atoms/StyledComponents/PrimaryButton.tsx
  src/components/atoms/StyledComponents/SecondaryButton.tsx
  src/components/atoms/StyledComponents/index.ts
  src/components/atoms/index.ts
  src/components/organisms/ActionsPane/ActionsPaneHeader.styled.tsx
  src/components/organisms/ActionsPane/Diff/Diff.tsx
  src/components/organisms/ActionsPane/InstallDeploy/InstallDeploy.tsx
  src/components/organisms/ActionsPane/Restart/Restart.tsx
  src/components/organisms/ActionsPane/Scale/Scale.tsx
  src/components/organisms/NavigatorPane/CompareButton.tsx
  src/models/icons.ts
Labels: size/L

#2605 refactor: highlight/selection colors
  src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionMenu.styled.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
  src/components/molecules/SectionRenderer/styled.tsx
  src/components/organisms/FileTreePane/styled.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/SearchPane/styled.tsx
  src/styles/Colors.ts
Labels: size/M

#2603 refactor: change left menu badge background color
  src/components/organisms/PaneManager/PaneManagerLeftMenu.styled.tsx
  src/styles/Colors.ts
Labels: size/XS

#2610 refactor: remove footer
  src/App.tsx
  src/components/organisms/PageFooter/PageFooter.tsx
  src/components/organisms/PageFooter/index.ts
  src/components/organisms/index.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/utils/hooks.ts
Labels: size/M

#2609 fix: selecting files on macOS
  electron/app/commands.ts
  src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDsSchemaValidation.tsx
Labels: size/XS

#2606 refactor: remove border from primary button
  src/components/atoms/StyledComponents/PrimaryButton.tsx
Labels: size/XS

#2611 fix: styling for editor pane actions
  src/components/atoms/StyledComponents/SecondaryButton.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/ActionsPane/Diff/Diff.tsx
  src/components/organisms/ActionsPane/InstallDeploy/InstallDeploy.tsx
  src/components/organisms/ActionsPane/Restart/Restart.tsx
  src/components/organisms/ActionsPane/Scale/Scale.tsx
  src/constants/constants.ts
Labels: size/M

#2612 chore: add release notes for 1.12
  resources/releaseNotes/1.12/1.12.json
  resources/releaseNotes/1.12/1.12.md
  resources/releaseNotes/1.12/1.12.svg
Labels: size/L

#2613 feat: kill terminals
  electron/app/createWindow.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/utils.ts
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/redux/reducers/appConfig.ts
Labels: size/M

#2614 chore(release): 1.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#2616 [Snyk] Upgrade antd from 4.23.3 to 4.23.4
  package-lock.json
  package.json
Labels: size/XS

#2617 [Snyk] Upgrade yaml from 2.1.1 to 2.1.2
  package-lock.json
  package.json
Labels: size/XS

#2622 fix: check policies errors on add/update
  src/redux/reducers/main.ts
  src/redux/services/fileEntry.ts
  src/redux/thunks/updateMultipleResources.ts
Labels: size/S

#2625 fix: validation pane scroll
  src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgentTable.tsx
Labels: size/XS

#2631 chore: add feature flag for TwoZero
  src/App.tsx
  src/feature-flags.json
  src/utils/features.tsx
Labels: size/S

#2636 feat/new bottom selection
  package-lock.json
  package.json
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/NewPaneManager/NewPaneManager.tsx
  src/components/organisms/NewPaneManager/NewPaneManagerLeftMenu.tsx
  src/components/organisms/NewPaneManager/activities.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/models/ui.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/terminal.ts
  src/redux/reducers/ui.ts
  src/utils/terminal.ts
Labels: size/L

#2640 [Snyk] Upgrade @reduxjs/toolkit from 1.8.5 to 1.8.6
  package-lock.json
  package.json
Labels: size/XS

#2642 fix: isGitRepo property
  src/redux/thunks/setRootFolder.ts
Labels: size/XS
