Repository kubeshop/monokle, pull requests merged in 2022-06, with the labels that each got.

#1891 fix: preview loading button shrinking
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
Labels: size/M

#1883 fix: hover on row - edit btn
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/index.css
Labels: size/XS

#1892 fix: overflow-y auto for table on selectors
  src/components/organisms/PageHeader/ClusterSelectionTable.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
Labels: size/S

#1886 fix: fix resource filter margin
  src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
Labels: size/S

#1894 fix: update checked selection when deleting resources
  src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
  src/redux/thunks/removeResources.ts
Labels: size/S

#1885 fix: tooltip behaviour for disabled button
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
Labels: size/XS

#1884 fix: enable switch projects while in Cluster or Preview mode
  src/components/organisms/PageHeader/ProjectSelection.tsx
Labels: size/XS

#1887 fix: template drop down issue
  src/components/molecules/FormEditor/FormWidgets/ApiGroupSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/NamespaceSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/PodSelectorSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/ResourceSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/SecretKindResourceForm.styled.tsx
  src/components/molecules/FormEditor/FormWidgets/SecretKindResourceForm.tsx
  src/components/molecules/FormEditor/FormWidgets/SecretKindSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/styled.tsx
Labels: size/L

#1895 fix: highlight unsaved resource after append
  src/redux/reducers/main.ts
  src/redux/thunks/saveUnsavedResources.ts
Labels: size/XS

#1888 fix: do not remove empty objects
  src/redux/services/manifest-utils.test.ts
  src/redux/services/manifest-utils.ts
Labels: size/XS

#1900 fix: scroll to link if resource is not selected
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
Labels: size/S

#1901 feat: show not found message
  src/components/molecules/ImageDetails/ImageDetails.styled.tsx
  src/components/molecules/ImageDetails/ImageDetails.tsx
Labels: size/S

#1898 fix: newly created resource selected and highlighted
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
  src/redux/reducers/main.ts
Labels: size/XS

#1904 chore: add "dev" shorthand for "electron:dev"
  package.json
Labels: size/XS

#1907 feat: image tag tooltip delay
  src/components/molecules/ImageDetails/ImageTags.tsx
Labels: size/XS

#1899 fix: deselect image on preview/exit
  src/redux/reducers/main.ts
Labels: size/XS

#1905 Wito/fix/fix custom kubeconfig
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionNameSuffix.tsx
  src/redux/compare/selectors.ts
  src/redux/selectors.ts
Labels: size/S

#1910 Wito/feat/walkthrough 1 8
  src/components/molecules/WalkThrough/newReleaseFeaturesContent.ts
  src/components/molecules/WalkThrough/types.ts
  src/components/molecules/WalkThrough/walkThroughNoviceContent.ts
  src/components/organisms/CompareModal/CompareModalComparing.tsx
  src/components/organisms/CompareModal/ResourceList.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/NavigatorPane/ClusterCompareButton.tsx
  src/components/organisms/NavigatorPane/CompareButton.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/redux/compare/listeners.ts
  src/redux/compare/slice.ts
  src/redux/compare/state.ts
  src/redux/services/compare/compareResources.ts
  src/redux/services/compare/fetchResources.ts
  src/utils/kubeclient.ts
  src/utils/yaml.ts
Labels: size/L

#1913 chore: add publisherNames
  package.json
Labels: size/XS

#1914 chore: change cluster selection placement
  src/components/organisms/PageHeader/ClusterSelection.tsx
Labels: size/XS

#1921 fix: loading helm chart folder
  src/redux/services/helm.ts
Labels: size/XS

#1925 Fix is cluster mode
  src/components/organisms/FileTreePane/styled.tsx
  src/redux/selectors.ts
Labels: size/S

#1926 chore: top panel resize
  src/components/organisms/PageHeader/ClusterSelection.tsx
Labels: size/XS

#1931 chore(release): 1.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#1936 chore: specify a version for AzureSignTool
  .github/workflows/monokle-build-nightly.yml
  .github/workflows/monokle-publish-downloads.yml
  .github/workflows/monokle-publish-updater.yml
  .github/workflows/monokle-publish.yml
  .github/workflows/monokle-ui-tests.yml
Labels: size/S

#1937 feat: filter templates also by author name
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
Labels: size/S

#1935 fix: tooltip hotkey overflow
  src/components/molecules/HotkeyLabel/HotkeyLabel.styled.tsx
  src/index.css
Labels: size/XS

#1941 chore: delete config json file on start up
  jest.config.js
  package-lock.json
  package.json
  playwright.config.ts
  src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/MessageBox/MessageBox.tsx
  tests/antdHelpers.ts
  tests/base.test.ts
  tests/electronHelpers.ts
  tests/git.test.ts
  tests/models/mainWindow.ts
  tests/models/newResourceModal.ts
  tests/models/projectsDropdown.ts
  tests/models/saveResourceModal.ts
  tests/models/startProjectPane.ts
  tests/project.test.ts
Labels: size/L

#1944 chore: revert notification duration
  package-lock.json
  src/components/organisms/MessageBox/MessageBox.tsx
Labels: size/XS

#1942 feat: opa validation status
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/OPAStatus.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/atoms/Icon/index.ts
  src/components/molecules/IconWithPopover/IconWithPopover.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/NavigatorPane/OPAValidationStatus.styled.tsx
  src/components/organisms/NavigatorPane/OPAValidationStatus.tsx
  src/components/organisms/PaneManager/MenuIcon.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/ValidationOpenPolicyAgent.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/ValidationOpenPolicyAgentHeading.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/useOpenPolicyAgentTable.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationCard.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationOverview.tsx
  src/components/organisms/ValidationDrawer/ValidationDrawer.tsx
  src/models/icons.ts
  src/models/integrations.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
Labels: size/L

#1943 feat: validation methods
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/K8sSchema.tsx
  src/components/atoms/Icon/Icons/OpenPolicyAgent.tsx
  src/components/atoms/Icon/Icons/ResourceLinks.tsx
  src/components/atoms/Icon/Icons/YAMLSyntax.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/organisms/ValidationDrawer/Overview/ValidationCard.styled.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationCard.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationCardUpnext.styled.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationOverview.tsx
  src/models/icons.ts
  src/models/integrations.ts
Labels: size/L

#1945 feat: upgrade electron version to 19.0.4
  package-lock.json
  package.json
Labels: size/XS

#1946 feat: validation drawer as tab
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/NavigatorPane/OPAValidationStatus.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.styled.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/ValidationOpenPolicyAgent.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationOverview.tsx
  src/components/organisms/ValidationDrawer/ValidationDrawer.styled.tsx
  src/components/organisms/ValidationDrawer/ValidationDrawer.tsx
  src/components/organisms/ValidationDrawer/ValidationDrawerHeading.styled.tsx
  src/components/organisms/ValidationDrawer/ValidationDrawerHeading.tsx
  src/components/organisms/ValidationDrawer/index.ts
  src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgent.styled.tsx
  src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgent.tsx
  src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgentHeading.styled.tsx
  src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgentHeading.tsx
  src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgentTable.styled.tsx
  src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgentTable.tsx
  src/components/organisms/ValidationPane/OpenPolicyAgent/index.ts
  src/components/organisms/ValidationPane/OpenPolicyAgent/useOpenPolicyAgentTable.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationCard.styled.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationCard.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationCardUpNext.styled.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationCardUpNext.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationOverview.styled.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationOverview.tsx
  src/components/organisms/ValidationPane/ValidationOverview/index.ts
  src/components/organisms/ValidationPane/ValidationPane.styled.tsx
  src/components/organisms/ValidationPane/ValidationPane.tsx
  src/components/organisms/ValidationPane/index.ts
  src/components/organisms/index.ts
  src/constants/constants.ts
  src/models/appstate.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/reducers/ui.ts
Labels: size/XL

#1959 fix: stringify helm value
  src/components/molecules/Monaco/CodeIntel/helmChartFile.ts
Labels: size/XS

#1961 fix: cluster resource delete
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/redux/services/compare/fetchResources.ts
  src/redux/thunks/loadClusterDiff.ts
  src/redux/thunks/previewCluster.ts
  src/utils/kubeclient.ts
Labels: size/M

#1960 fix: don't show popover when button is disabled
  src/components/molecules/FilterPopover/FilterPopover.tsx
Labels: size/M

#1974 chore: update package-lock
  package-lock.json
Labels: size/XS

#1973 feat: duplicate file
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/FileTreePane/types.tsx
  src/utils/files.ts
Labels: size/M

#1969 feat: autosave indicator
  src/components/molecules/FormEditor/FormEditor.styled.tsx
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/models/appstate.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/thunks/updateFileEntry.ts
  src/redux/thunks/updateResource.ts
  src/styles/Colors.ts
Labels: size/L

#1975 feat: new file action in file explorer for folders
  src/App.tsx
  src/components/organisms/CreateFileFolderModal/CreateFileFolderModal.tsx
  src/components/organisms/CreateFileFolderModal/index.ts
  src/components/organisms/CreateFolderModal/CreateFolderModal.tsx
  src/components/organisms/CreateFolderModal/index.ts
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/FileTreePane/types.tsx
  src/components/organisms/RenameEntityModal/RenameEntityModal.tsx
  src/components/organisms/index.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/utils/files.ts
Labels: size/L

#1978 [Snyk] Upgrade framer-motion from 6.3.4 to 6.3.6
  package-lock.json
  package.json
Labels: size/XS

#1977 chore: fix type issu for tar dependency
  electron/tsconfig.json
  package-lock.json
Labels: size/XS

#1980 feat: hide namespace for cluster scoped resources
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/models/k8sresource.ts
  src/redux/services/compare/transferResource.ts
  src/redux/services/resource.test.ts
  src/redux/services/resource.ts
  src/redux/services/unsavedResource.ts
Labels: size/M

#1976 refactor: setup Segment integration
  .github/workflows/monokle-build-nightly.yml
  .github/workflows/monokle-publish-downloads.yml
  .github/workflows/monokle-publish-updater.yml
  .github/workflows/monokle-publish.yml
  electron/app/amplitude.ts
  electron/app/createWindow.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/segment.ts
  electron/app/utils.ts
  package-lock.json
  package.json
  src/utils/telemetry.ts
Labels: size/L

#1981 feat: deploy scoped resources modal
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.styled.tsx
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
Labels: size/L

#1986 feat: show release notes only for the next big release
  src/App.tsx
Labels: size/XS

#1987 feat: compare modal unused space
  src/components/organisms/CompareModal/CompareModal.styled.tsx
  src/components/organisms/CompareModal/CompareModal.tsx
  src/components/organisms/CompareModal/CompareModalComparing.tsx
  src/components/organisms/CompareModal/CompareModalFooter.tsx
Labels: size/M

#1988 chore(release): 1.8.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#1989 feat: get about info from json file
  resources/releaseNotes/1.8/1.8.json
  src/components/organisms/AboutModal/AboutModal.tsx
Labels: size/M

#1993 fix: restore the previous selection history when preview fails
  src/models/appstate.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
Labels: size/S

#1999 chore: update react-redux + use only useAppDispatch
  package-lock.json
  package.json
  src/App.tsx
  src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgent.tsx
  src/components/organisms/ValidationPane/OpenPolicyAgent/useOpenPolicyAgentTable.tsx
Labels: size/S

#2004 feat: middle/patch release notification
  src/App.tsx
  src/components/organisms/MessageBox/MessageBox.tsx
  src/models/alert.ts
Labels: size/M

#2002 feat: add latest k8s versions
  package-lock.json
  resources/schemas/1.24.2.json
  src/constants/constants.ts
  src/redux/services/validation.test.ts
Labels: size/XXL

#2005 feat: delete project action for recent projects
  src/App.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/StartProjectPane/RecentProject.styled.tsx
  src/components/organisms/StartProjectPane/RecentProject.tsx
  src/utils/index.ts
Labels: size/L

#2024 feat: disable replace in preview mode
  src/navsections/ImagesSectionBlueprint/ImagesQuickAction.styled.tsx
  src/navsections/ImagesSectionBlueprint/ImagesQuickAction.tsx
Labels: size/S
