Repository kubeshop/monokle, pull requests merged in 2022-12, with the labels that each got.

#2836 Razvantopliceanu/chore/merging
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
Labels: size/S

#2844 Erdikose/chore/dashboard reviews
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/Dashboard.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/ResourceRefsIconPopover/RefLink.tsx
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
  src/components/molecules/ValidationErrorsPopover/ErrorsPopoverContent.tsx
  src/components/molecules/ValidationErrorsPopover/ValidationErrorLink.tsx
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/Header/Header.styled.tsx
  src/components/organisms/Dashboard/Header/Header.tsx
  src/components/organisms/Dashboard/Overview/Activity.styled.tsx
  src/components/organisms/Dashboard/Overview/Activity.tsx
  src/components/organisms/Dashboard/Overview/InventoryInfo.styled.tsx
  src/components/organisms/Dashboard/Overview/InventoryInfo.tsx
  src/components/organisms/Dashboard/Overview/Overview.styled.tsx
  src/components/organisms/Dashboard/Overview/Overview.tsx
  src/components/organisms/Dashboard/Overview/Status.styled.tsx
  src/components/organisms/Dashboard/Overview/Status.tsx
  src/components/organisms/Dashboard/Overview/Utilization.styled.tsx
  src/components/organisms/Dashboard/Overview/Utilization.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/EditorTab.tsx
  src/components/organisms/Dashboard/Tableview/InfoTab.styled.tsx
  src/components/organisms/Dashboard/Tableview/InfoTab.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.styled.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.tsx
  src/components/organisms/Dashboard/Tableview/Tableview.styled.tsx
  src/components/organisms/Dashboard/Tableview/Tableview.tsx
  src/components/organisms/DashboardPane/DashboardPane.style.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/components/organisms/DashboardPane/menu.ts
  src/kindhandlers/EventHandler.ts
  src/kindhandlers/NodeHandler.ts
  src/kindhandlers/index.ts
  src/redux/dashboard/slice.ts
  src/redux/dashboard/state.ts
  src/redux/services/clusterDashboard.ts
  src/redux/services/clusterResourceWatcher.ts
  src/styles/Colors.ts
Labels: size/XXL

#2850 Erdikose/chore/cluster dashboard progress
  src/components/atoms/Icon/Icons/Dashboard.tsx
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/Header/Header.styled.tsx
  src/components/organisms/Dashboard/Header/Header.tsx
  src/components/organisms/Dashboard/Overview/Activity.tsx
  src/components/organisms/Dashboard/Overview/InventoryInfo.tsx
  src/components/organisms/Dashboard/Overview/Status.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.styled.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/InfoTab.styled.tsx
  src/components/organisms/Dashboard/Tableview/InfoTab.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.styled.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/kindhandlers/EventHandler.ts
  src/redux/dashboard/slice.ts
  src/redux/dashboard/state.ts
  src/redux/services/clusterResourceWatcher.ts
Labels: size/XL

#2857 fix: reprocess resources after doing a preview
  src/redux/thunks/previewCluster.ts
Labels: size/S

#2860 feat: release tooltips
  src/components/molecules/Walkthrough/content/newReleaseFeatures.ts
  src/components/molecules/Walkthrough/content/novice.ts
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/models/walkthrough.ts
Labels: size/M

#2861 fix trackEvent method, rename events and add missing ones
  electron/app/git/git.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/utils.ts
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/molecules/ValidationErrorsPopover/ErrorsPopoverContent.tsx
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/Dashboard/Tableview/InfoTab.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/QuickSearchActions/QuickSearchActions.tsx
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationCard.tsx
  src/redux/compare/slice.ts
  src/redux/forms/slice.ts
  src/redux/reducers/main.ts
  src/redux/services/preview.ts
  src/redux/services/previewCommand.ts
  src/redux/thunks/applyFile.ts
  src/redux/thunks/applyHelmChart.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/runPreviewConfiguration.ts
  src/redux/thunks/saveUnsavedResources.ts
  src/redux/thunks/setRootFolder.ts
  src/utils/shell.ts
  src/utils/telemetry.ts
Labels: size/L

#2862 chore: release notes for 1.13
  resources/releaseNotes/1.13/1.13.json
  resources/releaseNotes/1.13/1.13.md
  resources/releaseNotes/1.13/1.13.svg
Labels: size/L

#2864 refactor: start project styling
  src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
Labels: size/XS

#2866 chore: add dashboard telemetry
  src/components/organisms/Dashboard/Header/Header.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
  src/redux/dashboard/slice.ts
  src/utils/telemetry.ts
Labels: size/M

#2867 chore(release): 1.13.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS

#2869 Changed paragraph to preformatted text
  src/components/molecules/NotificationMarkdown/NotificationMarkdown.tsx
Labels: size/XS

#2868 doc: 1.13 Doc Updates
  docs/cluster-mode.md
  docs/compare-subfolders.md
  docs/img/cluster-mode-icon-1.13.png
  docs/img/cluster-mode-navigation-1.13.png
  docs/img/cluster-mode-overview-1.13.png
  docs/img/cluster-mode-resource-navigation-1.13.png
  docs/img/cluster-mode-resource-validation-1.13.png
  docs/img/cluster-mode-yaml-1.13.png
  docs/img/compare-subfolders-1.13.png
  docs/resource-editing.md
  mkdocs.yml
Labels: size/M

#2870 fix: add support for external patch refs
  src/redux/services/kustomize.ts
Labels: size/XS

#2679 Devmariam/feat/2621 new get started page
  .gitignore
  electron/app/menu.ts
  paths.json
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/index.ts
  src/components/organisms_new/PaneManager/PaneManager.styled.tsx
  src/components/organisms_new/PaneManager/PaneManager.tsx
  src/components/organisms_new/TutorialPage/TutorialCard.styled.tsx
  src/components/organisms_new/TutorialPage/TutorialCard.tsx
  src/components/organisms_new/TutorialPage/TutorialPage.styled.tsx
  src/components/organisms_new/TutorialPage/TutorialPage.tsx
  src/components/organisms_new/TutorialPage/TutorialReference.styled.tsx
  src/components/organisms_new/TutorialPage/TutorialReference.tsx
  src/components/organisms_new/TutorialPage/index.ts
  src/components/organisms_new/index.ts
  src/shared/constants/features.ts
  src/shared/constants/hotkeys.ts
  src/shared/constants/index.ts
  src/shared/constants/tutorialReferences.ts
  src/shared/models/features.ts
  src/shared/models/index.ts
  src/shared/models/telemetry.ts
  src/shared/models/tutorialReferences.ts
  src/shared/models/ui.ts
  src/shared/styles/colors.ts
  src/shared/utils/kubeclient.ts
Labels: size/L

#2876 feat/compare git subfolders
  src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/GitBranchSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/GitCommitSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/GitFolderSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/GitSelect/GitSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx
  src/hooks/useFolderTreeSelectData.ts
  src/redux/compare/selectors.ts
  src/redux/compare/state.ts
  src/redux/services/compare/fetchResources.ts
Labels: size/L

#2877 fix: notification markdown "pre"
  src/components/molecules/NotificationMarkdown/styled.tsx
Labels: size/XS

#2882 [Snyk] Upgrade react-monaco-editor from 0.50.1 to 0.51.0
  package-lock.json
  package.json
Labels: size/XS

#2881 [Snyk] Upgrade @ant-design/icons from 4.7.0 to 4.8.0
  package-lock.json
  package.json
Labels: size/XS

#2883 fix: git compare resource content
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/redux/services/compare/fetchResources.ts
Labels: size/S

#2884 feat: add new tracking events
  src/components/organisms/PageHeader/CreateProject.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/utils/telemetry.ts
Labels: size/XS

#2885 fix: create file
  src/utils/files.ts
Labels: size/XS

#2886 feat: add Sentry to electron and remove Nucleus
  .github/workflows/monokle-build-nightly.yml
  .github/workflows/monokle-publish-downloads.yml
  .github/workflows/monokle-publish-test.yml
  .github/workflows/monokle-publish-updater.yml
  .github/workflows/monokle-publish.yml
  electron/app/createWindow.ts
  electron/app/index.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/utils.ts
  package-lock.json
  package.json
  src/utils/telemetry.ts
Labels: size/L

#2890 docs: Update index.md
  docs/index.md
Labels: size/XS

#2891 chore(release): 1.13.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#2896 fix: handle exit preview error
  src/redux/services/clusterResourceWatcher.ts
Labels: size/S

#2903 fix: updated options and improved error output for failed Helm Previews
  src/constants/helmOptions.ts
  src/redux/thunks/runPreviewConfiguration.ts
Labels: size/XS

#2902 fix: delete preview config custom option
  src/redux/reducers/appConfig.ts
  src/redux/services/projectConfig.ts
Labels: size/M

#2914 chore: adding support for K8s 1.26.0
  src/constants/constants.ts
Labels: size/XS

#2909 chore: fix kubeconfig watcher
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/redux/services/monitorKubeConfig.ts
Labels: size/L

#2908 fix: rename helm value file
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenuWrapper.tsx
Labels: size/M

#2923 Fixed blog's broken link in 1.13 release notes.
  resources/releaseNotes/1.13/1.13.md
Labels: size/XS

#2924 fix: tests by adding 1.26 k8s schema
  resources/schemas/1.26.0.json
Labels: size/XXL

#2931 [Snyk] Upgrade vm2 from 3.9.11 to 3.9.12
  package-lock.json
  package.json
Labels: size/XS

#2932 fix: default project settings when no active project
  src/components/organisms/SettingsManager/SettingsManager.tsx
Labels: size/XS

#2937 [Snyk] Upgrade @reduxjs/toolkit from 1.9.0 to 1.9.1
  package-lock.json
  package.json
Labels: size/XS

#2910 Erdikose/feat/kubectl proxy
  electron/app/ipc/ipcListeners.ts
  electron/app/kubectl.ts
  package-lock.json
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/services/preview.ts
  src/redux/thunks/previewCluster.ts
  src/utils/commands/kubectl.ts
  src/utils/electronStore.ts
  src/utils/kubeclient.ts
  src/utils/promises.ts
Labels: size/L

#2940 refactor: change default font-family to Inter
  public/Splashscreen.css
  public/index.html
  src/components/atoms/MonoPaneTitle/MonoPaneTitle.tsx
  src/components/molecules/Logs/Logs.styled.ts
  src/components/organisms/FileTreePane/styled.tsx
  src/components/organisms/KeyboardShortcuts/BoardKeys/BoardKeys.styled.tsx
  src/components/organisms/SearchPane/styled.tsx
  src/index.css
Labels: size/M

#2941 Refactor: app udates logic
  electron/app/ipc/ipcListeners.ts
  electron/app/utils.ts
  src/components/organisms/UpdateNotice/UpdateNotice.tsx
  src/utils/electronStore.ts
  src/utils/telemetry.ts
Labels: size/M

#2942 fix Sentry problems
  electron/app/createWindow.ts
  electron/app/index.ts
  package-lock.json
  package.json
  src/redux/reducers/appConfig.ts
Labels: size/M

#2921 feat: enable validation
  package-lock.json
  package.json
  src/components/molecules/Monaco/Monaco.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms_new/PaneManager/PaneManager.tsx
  src/components/organisms_new/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms_new/PaneManager/activities.tsx
  src/utils/hooks.ts
Labels: size/L

#2944 fix: loading the app icon
  electron/app/createWindow.ts
  resources/icon.ico
Labels: size/XS

#2949 chore: change text of cluster proxy setting
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/SettingsManager/styled.tsx
Labels: size/M

#2951 chore(release): 1.13.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS
