Repository kubeshop/monokle, pull requests merged in 2022-08, with the labels that each got.

#2160 fix: updated electron and node/npm, added temp fix for pty error on M1
  .npmrc
  .nvmrc
  electron/app/ipc/ipcListeners.ts
  package.json
Labels: size/M

#2165 fix: deploy cluster scoped resource
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
  src/redux/reducers/main.ts
Labels: size/S

#2162 feat: open shell into pod
  electron/app/ipc/ipcListeners.ts
  package-lock.json
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/TerminalPane/TerminalPane.tsx
  src/models/terminal.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
  src/redux/reducers/terminal.ts
Labels: size/L

#2123 build: choose highlighted
  src/components/organisms/CompareModal/ResourceSetSelector/ClusterContextSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmChartSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmValuesOrConfigSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/KustomizeSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelectColor.styled.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx
Labels: size/L

#2166 refactor: terminal redesign
  package-lock.json
  src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/TerminalPane/TerminalPane.styled.tsx
  src/components/organisms/TerminalPane/TerminalPane.tsx
Labels: size/L

#2167 feat: toggle terminal pane hotkey
  docs/hotkeys.md
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/constants/hotkeys.ts
  src/constants/tooltips.tsx
Labels: size/M

#2169 [Snyk] Upgrade antd from 4.21.5 to 4.21.6
  package-lock.json
  package.json
Labels: size/XS

#2170 feat: terminal font size
  src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/TerminalPane/TerminalOptions.styled.tsx
  src/components/organisms/TerminalPane/TerminalOptions.tsx
  src/components/organisms/TerminalPane/TerminalPane.tsx
  src/models/terminal.ts
  src/redux/initialState.ts
  src/redux/reducers/terminal.ts
  src/utils/electronStore.ts
Labels: size/L

#2171 fix: disable form editor in preview mode
  src/components/molecules/FormEditor/FormEditor.tsx
Labels: size/S

#2172 feat: terminal name for pod shell
  src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/TerminalPane/TerminalPane.tsx
  src/models/terminal.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
Labels: size/M

#2176 [Snyk] Upgrade framer-motion from 6.4.3 to 6.5.0
  package-lock.json
  package.json
Labels: size/XS

#2122 build: splitter style enhancement done as requested
  src/index.css
Labels: size/XS

#2175 [Snyk] Upgrade analytics-node from 6.0.0 to 6.1.0
  package-lock.json
  package.json
Labels: size/XS

#2178 feat: confirmation modal for killing terminal
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/TerminalPane/TerminalPane.tsx
Labels: size/M

#2173 chore: fix kubeconfig monitor dispatch
  src/redux/reducers/appConfig.ts
Labels: size/XS

#2180 feat: terminal exit command
  electron/app/ipc/ipcListeners.ts
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/TerminalPane/TerminalPane.tsx
Labels: size/M

#2185 feat: terminal multiple shells
  electron/app/ipc/ipcListeners.ts
  package-lock.json
  package.json
  src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/TerminalPane/NewTerminalOptions.styled.tsx
  src/components/organisms/TerminalPane/NewTerminalOptions.tsx
  src/components/organisms/TerminalPane/TerminalOptions.styled.tsx
  src/components/organisms/TerminalPane/TerminalOptions.tsx
  src/components/organisms/TerminalPane/TerminalPane.tsx
  src/constants/terminal.ts
  src/models/terminal.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
  src/redux/initialState.ts
  src/redux/reducers/terminal.ts
  src/redux/services/terminalShells.ts
  src/redux/store.ts
  src/utils/electronStore.ts
Labels: size/L

#2187 Erdikose/fix/resource kind information
  src/navsections/K8sResourceSectionBlueprint/ResourceKindInformation.tsx
Labels: size/S

#2189 fix: select helm template
  package-lock.json
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
Labels: size/S

#2196 chore: update electron version
  package-lock.json
  package.json
Labels: size/XS

#2197 fix: bring back create namespace option
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
Labels: size/XS

#2198 refactor: tree item tooltip overlay style
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/constants/constants.ts
Labels: size/S

#2181 Julia/feat/scale restart
  docs/hotkeys.md
  src/components/organisms/ActionsPane/ActionsPaneHeader.styled.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/ActionsPane/Restart/Restart.tsx
  src/components/organisms/ActionsPane/Scale/Scale.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/constants/hotkeys.ts
  src/constants/tooltips.tsx
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/redux/services/restartDeployment.ts
  src/redux/services/scaleDeployment.ts
Labels: size/L

#2190 docs: Update mkdocs.yml
  mkdocs.yml
Labels: size/XS

#2200 feat: terminal tabs horizontal scrolling + popconfirm
  src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/TerminalPane/TerminalPane.tsx
  src/index.css
Labels: size/M

#2199 fix: close new project popup on option click
  src/components/organisms/PageHeader/CreateProject.styled.tsx
  src/components/organisms/PageHeader/CreateProject.tsx
Labels: size/L

#2121 style: fixed header styling due to design changes
  src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/CreateProject.styled.tsx
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/PaneManager/MenuButton/MenuButton.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.styled.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
Labels: size/M

#2204 [Snyk] Upgrade antd from 4.21.6 to 4.21.7
  package-lock.json
  package.json
Labels: size/XS

#2205 fix: ignore file/folder contained in filter when in preview mode
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
  src/redux/selectors.ts
  src/utils/resources.ts
Labels: size/M

#2209 refactor: age/status info
  src/navsections/K8sResourceSectionBlueprint/ResourceKindInformation.styled.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindInformation.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
  src/navsections/UnknownResourceSectionBlueprint/UnknownResourceSectionBlueprint.ts
  src/styles/Colors.ts
Labels: size/M

#2210 fix: select and highlight first created resource from templates
  src/redux/reducers/main.ts
  src/redux/services/unsavedResource.ts
Labels: size/S

#2211 1.10 Release Notes
  resources/releaseNotes/1.10/1.10.json
  resources/releaseNotes/1.10/1.10.md
  resources/releaseNotes/1.10/1.10.svg
  src/components/organisms/ReleaseNotes/ReleaseNotes.tsx
  src/components/organisms/ReleaseNotes/styled.tsx
Labels: size/L

#2212 chore(release): 1.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#2213 [Snyk] Upgrade type-fest from 2.16.0 to 2.17.0
  package-lock.json
  package.json
Labels: size/XS

#2231 refactor: warnings/errors dropdown padding
  src/components/organisms/NavigatorPane/WarningAndErrorsDisplay.styled.tsx
  src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
Labels: size/M

#2232 refactor: terminal icon isSelected
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
Labels: size/XS

#2233 refactor: show scale/restart only in cluster mode
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/ActionsPane/Restart/Restart.tsx
  src/components/organisms/ActionsPane/Scale/Scale.tsx
Labels: size/M

#2234 feat: remove tag in name filter using backspace
  src/components/molecules/InputTags/InputTags.tsx
Labels: size/S

#2236 refactor: compare & sync button text
  src/components/organisms/NavigatorPane/CompareButton.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
Labels: size/M

#2235 fix: close alert after clicking on button and open notifications
  src/App.tsx
  src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx
Labels: size/XS

#2237 chore: update package-lock
  package-lock.json
Labels: size/XS

#2238 [Snyk] Upgrade react-hotkeys-hook from 3.4.4 to 3.4.7
  package-lock.json
  package.json
Labels: size/XS

#2240 fix: save zoom factor in electron store
  electron/app/createWindow.ts
  src/redux/reducers/ui.ts
  src/utils/electronStore.ts
Labels: size/S

#2245 fix: remove highlights for matched chars/patterns
  src/components/organisms/SearchPane/SearchPane.tsx
Labels: size/XS

#2246 [Snyk] Upgrade antd from 4.22.0 to 4.22.1
  package-lock.json
  package.json
Labels: size/XS

#2253 chore(release): 1.10.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS

#2265 Erdikose/fix/auto updater
  .github/workflows/monokle-publish-test.yml
  .nvmrc
  dev-app-update.yml
  electron/app/autoUpdater.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/openApplication.ts
  package-lock.json
  package.json
  src/utils/logToFile.ts
  src/utils/telemetry.ts
Labels: size/L

#2267 fix: preview configuration details crashing
  src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.tsx
Labels: size/S

#2254 fix: select file on match line click
  src/components/organisms/SearchPane/CreateFilteredNode.tsx
  src/hooks/fileTreeHooks/useFileSelect.tsx
Labels: size/XS

#2263 fix: improved handling of invalid Chart.yaml
  src/redux/services/helm.ts
Labels: size/S

#2278 chore(release): 1.10.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#2279 docs: Create Working with Multiple Resources Doc
  docs/cluster-integration.md
  docs/working-with-multiple-resources.md
  mkdocs.yml
Labels: size/S

#2284 feat: start new project by cloning a Git repository
  electron/app/git/git.ts
  electron/app/git/index.ts
  electron/app/git/ipc.ts
  electron/app/index.ts
  package-lock.json
  package.json
  src/components/organisms/PageHeader/CreateProject.tsx
  src/components/organisms/PageHeader/GitCloneModal.styled.tsx
  src/components/organisms/PageHeader/GitCloneModal.tsx
  src/utils/promises.ts
Labels: size/L

#2287 fix: downgrade electron version
  package-lock.json
  package.json
Labels: size/XS

#2288 chore(release): 1.10.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#2290 feat: branch selector + logic for branch checkout
  electron/app/createWindow.ts
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/atoms/CopyButton/CopyButton.tsx
  src/components/atoms/CopyButton/index.ts
  src/components/atoms/TableSelect/TableSelect.tsx
  src/components/atoms/TableSelect/index.ts
  src/components/atoms/index.ts
  src/components/molecules/BranchSelect/BranchCell.tsx
  src/components/molecules/BranchSelect/BranchSelect.tsx
  src/components/molecules/BranchSelect/BranchTable.styled.tsx
  src/components/molecules/BranchSelect/BranchTable.tsx
  src/components/molecules/BranchSelect/index.ts
  src/components/molecules/BranchSelect/useBranchTable.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/models/git.ts
  src/models/rootstate.ts
  src/redux/git/git.initialState.ts
  src/redux/git/git.slice.ts
  src/redux/git/index.ts
  src/redux/reducers/main.ts
  src/redux/store.ts
  src/redux/thunks/setRootFolder.ts
  src/styles/Colors.ts
Labels: size/L

#2312 docs: Add v10 Blog Post
  docs/index.md
Labels: size/S
