Repository kubeshop/monokle, pull requests merged in 2022-11, with the labels that each got.

#2648 refactor: move new organisms to dedicated folder
  src/App.tsx
  src/components/organisms/NewPaneManager/index.ts
  src/components/organisms/index.ts
  src/components/organisms_new/NavigatorPane/NavigatorPane.tsx
  src/components/organisms_new/NavigatorPane/index.ts
  src/components/organisms_new/PaneManager/PaneManager.styled.tsx
  src/components/organisms_new/PaneManager/PaneManager.tsx
  src/components/organisms_new/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms_new/PaneManager/activities.tsx
  src/components/organisms_new/PaneManager/index.ts
  src/components/organisms_new/index.ts
Labels: size/M

#2650 remove unused logs slice & cleanup services
  src/components/molecules/Monaco/useDebouncedCodeSave.ts
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/SettingsManager/Settings.tsx
  src/redux/initialState.ts
  src/redux/reducers/logs.ts
  src/redux/services/applyFileWithConfirm.tsx
  src/redux/services/clusterResource.ts
  src/redux/services/k8sVersionService.ts
  src/redux/services/log.ts
  src/redux/store.ts
Labels: size/M

#2655 [Snyk] Upgrade antd from 4.23.4 to 4.23.5
  package-lock.json
  package.json
Labels: size/XS

#2661 [Snyk] Upgrade antd from 4.23.5 to 4.23.6
  package-lock.json
  package.json
Labels: size/XS

#2663 refactor: logo collapsing arrows
  package-lock.json
  package.json
  src/assets/MonokleLogoDark.svg
  src/assets/NewMonokleLogoDark.svg
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/styled.tsx
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms_new/PaneManager/PaneManager.tsx
  src/styles/Colors.ts
Labels: size/L

#2664 chore: update codeowners
  .github/CODEOWNERS
Labels: size/XS

#2653 refactor: validation configuration
  electron/app/ipc/ipcListeners.ts
  package-lock.json
  package.json
  src/App.tsx
  src/assets/NewValidationFigure.svg
  src/assets/policies/trivy.wasm
  src/components/organisms/NewValidationPane/NewValidationPane.styled.tsx
  src/components/organisms/NewValidationPane/NewValidationPane.tsx
  src/components/organisms/NewValidationPane/index.ts
  src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgent.tsx
  src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgentTable.tsx
  src/components/organisms/ValidationPane/OpenPolicyAgent/useOpenPolicyAgentTable.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationCard.styled.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationCard.tsx
  src/components/organisms/index.ts
  src/components/organisms_new/PaneManager/PaneManager.tsx
  src/components/organisms_new/PaneManager/activities.tsx
  src/models/integrations.ts
  src/models/rootstate.ts
  src/models/validation.ts
  src/redux/store.ts
  src/redux/validation/validation.initialState.ts
  src/redux/validation/validation.listeners.ts
  src/redux/validation/validation.selectors.ts
  src/redux/validation/validation.services.ts
  src/redux/validation/validation.slice.ts
  src/redux/validation/validation.thunks.ts
  src/utils/electronStore.ts
Labels: size/L

#2669 chore: remove unused type
  src/models/appstate.ts
Labels: size/S

#2670 feat: created lib for shared logic between main & renderer
  package-lock.json
  package.json
  shared/.gitignore
  shared/package-lock.json
  shared/package.json
  shared/src/index.ts
  shared/src/plugin.ts
  shared/src/repository.ts
  shared/tsconfig.json
  shared/tsconfig.node.json
  shared/vite-env.d.ts
  shared/vite.config.ts
Labels: size/L

#2675 fix: shared lib building
  package-lock.json
  package.json
  shared/.gitignore
  shared/package-lock.json
  shared/package.json
  shared/tsconfig.json
  shared/tsconfig.node.json
  shared/vite-env.d.ts
  shared/vite.config.ts
Labels: size/L

#2676 feat: hot reload for shared lib
  package-lock.json
  package.json
  shared/package-lock.json
  shared/package.json
Labels: size/S

#2677 chore: add shared folder + gitignore on main
  shared/.gitignore
Labels: size/S

#2666 feat(menu): open on github
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/models/git.ts
Labels: size/M

#2703 Erdikose/feat/add issues to project
  .github/workflows/add-issues-to-project.yaml
Labels: size/S

#2714 refactor: shared constants
  electron/app/constants/ipcEvents.ts
  electron/app/constants/telemetry.ts
  electron/app/createWindow.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/menu.ts
  electron/app/utils.ts
  electron/main.ts
  shared/package.json
  shared/src/constants/hotkeys.ts
  shared/src/constants/index.ts
  shared/src/constants/ipcEvents.ts
  shared/src/constants/k8s.ts
  shared/src/constants/telemetry.ts
  shared/src/index.ts
  shared/src/models/hotkeys.ts
  shared/src/models/index.ts
  src/components/atoms/HotkeyLabel/HotkeyLabel.tsx
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/KeyboardShortcuts/KeyboardShortcuts.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PluginManager/PluginInstallModal.tsx
  src/components/organisms/QuickSearchActions/QuickSearchActions.tsx
  src/components/organisms/SettingsManager/Settings.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/components/organisms_new/SettingsPane/DefaultProjectSettings/DefaultProjectSettings.tsx
  src/components/organisms_new/SettingsPane/PluginsManager/PluginInstallModal.tsx
  src/components/organisms_new/SettingsPane/Settings/Settings.tsx
  src/constants/constants.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartQuickAction.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationQuickAction.tsx
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/main.ts
  src/redux/services/extension.ts
  src/redux/services/projectConfig.ts
  src/redux/services/validation.test.ts
  src/redux/thunks/applyFile.ts
  src/redux/thunks/applyHelmChart.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/runPreviewConfiguration.ts
  src/redux/thunks/saveUnsavedResources.ts
  src/redux/thunks/setRootFolder.ts
  src/utils/electronStore.ts
  src/utils/shell.ts
  src/utils/telemetry.ts
Labels: size/XL

#2719 refactor: shared electron store
  electron/app/createWindow.ts
  electron/app/initKubeconfig.ts
  electron/app/utils.ts
  package-lock.json
  shared/package-lock.json
  shared/package.json
  shared/src/constants/electronStore.ts
  shared/src/constants/index.ts
  shared/src/index.ts
  shared/src/utils/electronStore.ts
  shared/src/utils/index.ts
  src/App.tsx
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/main.ts
  src/redux/reducers/terminal.ts
  src/redux/reducers/ui.ts
  src/redux/services/templates.ts
  src/redux/thunks/loadPolicies.ts
  src/redux/validation/validation.initialState.ts
  src/redux/validation/validation.slice.ts
  src/utils/segment.ts
Labels: size/M

#2715 docs: Desktop. vs Cloud Page. Add Cloud Blog Post
  docs/desktop-v-SAAS.md
  docs/getting-started.md
  docs/img/monokle-cloud-start-screen.png
  docs/index.md
  mkdocs.yml
Labels: size/L

#2195 Erdikose/feat/live resource updates
  package-lock.json
  src/redux/reducers/main.ts
  src/redux/services/clusterResourceWatcher.ts
  src/redux/services/preview.ts
  src/redux/thunks/previewCluster.ts
Labels: size/L

#2725 refactor: segment + telemetry
  electron/app/createWindow.ts
  electron/app/index.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/utils.ts
  package-lock.json
  shared/package-lock.json
  shared/package.json
  shared/src/models/index.ts
  shared/src/models/telemetry.ts
  shared/src/utils/index.ts
  shared/src/utils/segment.ts
  shared/src/utils/shell.ts
  shared/src/utils/telemetry.ts
  shared/src/utils/thread.ts
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/QuickSearchActions/QuickSearchActions.tsx
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationCard.tsx
  src/redux/compare/slice.ts
  src/redux/reducers/main.ts
  src/redux/thunks/applyFile.ts
  src/redux/thunks/applyHelmChart.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/runPreviewConfiguration.ts
  src/redux/thunks/saveUnsavedResources.ts
  src/redux/thunks/setRootFolder.ts
  src/utils/commands/execute.ts
  src/utils/kubeclient.ts
Labels: size/L

#2727 feat: add CREATE_ISSUE_TOKEN
  .github/workflows/add-issues-to-project.yaml
Labels: size/XS

#2729 fix fresh install in 2.0
  package-lock.json
  package.json
Labels: size/XS

#2731 fix: dev tools
  electron/app/createWindow.ts
Labels: size/XS

#2732 fix: remove warning for terminals
  .gitignore
  electron/app/createWindow.ts
  electron/app/utils.ts
  src/components/organisms/PageHeader/ProjectSelection.tsx
Labels: size/S

#2740 chore: add ESLint rules for imports
  .eslintrc.js
  package-lock.json
  package.json
  src/components/molecules/Monaco/Monaco.tsx
  src/redux/services/resource.ts
Labels: size/L

#2745 fix: parsing yaml documents with comment before
  src/redux/services/resource.ts
Labels: size/XS, merge to 2.0

#2746 fix: parse multi-doc comment before
  src/redux/services/resource.ts
Labels: size/XS, merge to 2.0

#2748 feat: possiblity to compare namespaces
  src/components/organisms/CompareModal/ComparisonList.styled.tsx
  src/components/organisms/CompareModal/ComparisonList.tsx
  src/components/organisms/CompareModal/ResourceList.styled.tsx
  src/components/organisms/CompareModal/ResourceList.tsx
  src/components/organisms/CompareModal/types.ts
  src/redux/compare/selectors.ts
  src/redux/services/compare/compareResources.ts
Labels: size/M, merge to 2.0

#2750 fix: compare operations
  src/redux/services/compare/compareResources.ts
Labels: size/M

#2751 fix: being able to select folders as files
  src/hooks/fileTreeHooks/useFileSelect.tsx
Labels: size/XS

#2752 fix: show editor for empty files
  src/components/molecules/Monaco/Monaco.tsx
Labels: size/XS

#2767 fix: a bunch of kustomize fixes and refactorings backported from Cloud
  src/redux/services/kustomize.ts
  src/redux/services/resource.ts
Labels: size/M

#2761 feat: edit saved commands
  src/App.tsx
  src/components/molecules/CommandPreview/CommandLabel.styled.tsx
  src/components/molecules/CommandPreview/CommandLabel.tsx
  src/components/molecules/CommandPreview/SaveCommand.tsx
  src/components/organisms/SaveEditCommandModal/SaveEditCommandModal.tsx
  src/components/organisms/SaveEditCommandModal/index.ts
  src/components/organisms/index.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
Labels: size/L, merge to 2.0

#2769 fix: reading content of folder
  src/redux/services/fileEntry.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/S, merge to 2.0

#2770 refactor: merge inside 2.0
  .github/workflows/add-issues-to-project.yaml
  .gitignore
  docs/desktop-v-SAAS.md
  docs/getting-started.md
  docs/img/monokle-cloud-start-screen.png
  docs/index.md
  electron/app/createWindow.ts
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  electron/app/utils.ts
  mkdocs.yml
  package-lock.json
  shared/src/models/compare.ts
  shared/src/models/git.ts
  shared/src/models/ui.ts
  src/App.tsx
  src/components/molecules/CommandPreview/CommandLabel.styled.tsx
  src/components/molecules/CommandPreview/CommandLabel.tsx
  src/components/molecules/CommandPreview/SaveCommand.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/SaveEditCommandModal/SaveEditCommandModal.tsx
  src/components/organisms/SaveEditCommandModal/index.ts
  src/components/organisms/index.ts
  src/components/organisms_new/CompareSyncPane/ComparisonList/ComparisonList.styled.tsx
  src/components/organisms_new/CompareSyncPane/ComparisonList/ComparisonList.tsx
  src/components/organisms_new/CompareSyncPane/ResourceList/ResourceList.styled.tsx
  src/components/organisms_new/CompareSyncPane/ResourceList/ResourceList.tsx
  src/hooks/fileTreeHooks/useFileSelect.tsx
  src/redux/compare/selectors.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/reducers/ui.ts
  src/redux/services/clusterResourceWatcher.ts
  src/redux/services/compare/compareResources.ts
  src/redux/services/fileEntry.ts
  src/redux/services/kustomize.ts
  src/redux/services/preview.ts
  src/redux/services/resource.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/XL

#2771 refactor: set CWD of saved command to current project path
  electron/app/commands.ts
  src/components/organisms/SaveEditCommandModal/SaveEditCommandModal.tsx
  src/redux/services/previewCommand.ts
  src/utils/commands/execute.ts
Labels: size/S

#2787 fix: monaco editor decorations disappearing
  package-lock.json
  package.json
  src/components/molecules/CommandPreview/CommandLabel.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/editorHelpers.ts
  src/components/molecules/Monaco/useEditorKeybindings.ts
Labels: size/M

#2791 refactor: compare sync
  src/components/organisms/CompareModal/CompareActionBar.tsx
  src/components/organisms/CompareModal/CompareModal.styled.tsx
  src/components/organisms/CompareModal/CompareModal.tsx
  src/components/organisms/CompareModal/ComparisonList.styled.tsx
  src/components/organisms/CompareModal/ComparisonList.tsx
  src/components/organisms/CompareModal/types.ts
  src/redux/compare/selectors.ts
  src/redux/services/compare/compareResources.ts
  src/utils/resources.ts
Labels: size/L

#2796 feat: use folder tree select data hook
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/hooks/useFolderTreeSelectData.ts
Labels: size/M

#2797 feat: compare sub folders
  src/components/organisms/CompareModal/ResourceSetSelector/LocalSelect/LocalSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/LocalSelect/index.ts
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/redux/compare/state.ts
  src/redux/compare/utils.ts
  src/redux/services/compare/fetchResources.ts
Labels: size/M

#2799 [Snyk] Upgrade tar from 6.1.11 to 6.1.12
  package-lock.json
  package.json
Labels: size/XS

#2801 [Snyk] Upgrade yargs from 17.6.0 to 17.6.1
  package-lock.json
  package.json
Labels: size/XS

#2802 fix: duplicated images walkthrough
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
Labels: size/M

#2803 fix: tooltip with absolute path only over name
  src/components/organisms/FileTreePane/CreateNode.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
Labels: size/M

#2804 fix: eslint imports on shared
  .eslintrc.js
  package.json
Labels: size/S

#2805 feat: sorting files folders
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/utils/electronStore.ts
  src/utils/fileExplorer.ts
Labels: size/M

#2795 feat: add option to generate random content for new resources
  package.json
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/redux/services/schema.ts
  src/redux/services/unsavedResource.ts
Labels: size/L

#2808 fix: key warning
  src/utils/fileExplorer.ts
Labels: size/XS

#2807 fix: git auth needed
  electron/app/git/git.ts
  package-lock.json
  src/components/atoms/TableSelect/TableSelect.tsx
  src/components/organisms/GitPane/BottomActions.tsx
  src/components/organisms/GitPane/GitPane.styled.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/components/organisms/GitPane/RemoteInput.tsx
  src/models/git.ts
  src/redux/git/git.slice.ts
  src/redux/thunks/setRootFolder.ts
  src/styles/Colors.ts
Labels: size/L

#2811 refactor: bring back resource selector at all times
  src/components/organisms/CompareModal/CompareModal.styled.tsx
  src/components/organisms/CompareModal/CompareModal.tsx
Labels: size/S

#2810 feat: group resource list by kind and api version group
  src/components/organisms/CompareModal/ResourceList.tsx
Labels: size/S

#2812 fix: resource list duplicate keys
  src/components/organisms/CompareModal/ResourceList.tsx
Labels: size/XS

#2813 Razvantopliceanu/chore/merging branches
  .gitignore
  electron/app/git/git.ts
  package-lock.json
  package.json
  src/components/atoms/TableSelect/TableSelect.tsx
  src/components/organisms/FileTreePane/CreateNode.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/GitPane/BottomActions.tsx
  src/components/organisms/GitPane/GitPane.styled.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/components/organisms/GitPane/RemoteInput.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms_new/CompareSyncPane/CompareSyncPane.styled.tsx
  src/components/organisms_new/CompareSyncPane/CompareSyncPane.tsx
  src/components/organisms_new/CompareSyncPane/ResourceList/ResourceList.styled.tsx
  src/components/organisms_new/CompareSyncPane/ResourceList/ResourceList.tsx
  src/redux/git/git.slice.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/services/schema.ts
  src/redux/services/unsavedResource.ts
  src/redux/thunks/setRootFolder.ts
  src/shared/constants/electronStore.ts
  src/shared/models/config.ts
  src/shared/models/git.ts
  src/shared/styles/colors.ts
  src/utils/fileExplorer.ts
Labels: size/L

#2794 feat: watch CRD changes in cluster mode
  package-lock.json
  src/kindhandlers/common/customObjectKindHandler.ts
  src/kindhandlers/index.ts
  src/models/appstate.ts
  src/models/resourcekindhandler.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/services/clusterResourceWatcher.ts
Labels: size/L

#2726 Erdikose/feat/minimal cluster dashboard
  electron/app/createWindow.ts
  electron/app/initKubeconfig.ts
  package-lock.json
  package.json
  src/assets/InfoCircle.svg
  src/components/atoms/Icon/Icon.tsx
  src/components/organisms/Dashboard/Dashboard.styled.tsx
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/Header/Header.styled.tsx
  src/components/organisms/Dashboard/Header/Header.tsx
  src/components/organisms/Dashboard/Overview/Activity.styled.tsx
  src/components/organisms/Dashboard/Overview/Activity.tsx
  src/components/organisms/Dashboard/Overview/InventoryInfo.styled.tsx
  src/components/organisms/Dashboard/Overview/InventoryInfo.tsx
  src/components/organisms/Dashboard/Overview/Overview.styled.tsx
  src/components/organisms/Dashboard/Overview/Overview.tsx
  src/components/organisms/Dashboard/Overview/Status.styled.tsx
  src/components/organisms/Dashboard/Overview/Status.tsx
  src/components/organisms/Dashboard/Overview/Utilization.styled.tsx
  src/components/organisms/Dashboard/Overview/Utilization.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.styled.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/EditorTab.styled.tsx
  src/components/organisms/Dashboard/Tableview/EditorTab.tsx
  src/components/organisms/Dashboard/Tableview/InfoTab.styled.tsx
  src/components/organisms/Dashboard/Tableview/InfoTab.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.styled.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.tsx
  src/components/organisms/Dashboard/Tableview/Tableview.styled.tsx
  src/components/organisms/Dashboard/Tableview/Tableview.tsx
  src/components/organisms/Dashboard/index.ts
  src/components/organisms/DashboardPane/DashboardPane.style.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/components/organisms/DashboardPane/index.ts
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/models/icons.ts
  src/models/rootstate.ts
  src/models/ui.ts
  src/redux/dashboard/index.ts
  src/redux/dashboard/slice.ts
  src/redux/dashboard/state.ts
  src/redux/reducers/appConfig.ts
  src/redux/selectors.ts
  src/redux/services/clusterDashboard.ts
  src/redux/services/clusterResourceWatcher.ts
  src/redux/services/kubeConfigManager.ts
  src/redux/services/kubeConfigMonitor.ts
  src/redux/services/projectConfig.ts
  src/redux/store.ts
  src/styles/Colors.ts
  src/utils/timeAgo.ts
  src/utils/unit-converter.ts
  tsconfig.json
Labels: size/XXL

#2828 feat: add empty screeen for cluster dashboard
  src/assets/ConnectClusterDashboard.svg
  src/assets/LoadClusterDashboard.svg
  src/components/organisms/Dashboard/EmptyDashboard.styled.tsx
  src/components/organisms/Dashboard/EmptyDashboard.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
Labels: size/M

#2830 feat: quick preview cluster
  electron/app/menu.ts
  src/assets/FromScratch.svg
  src/assets/FromTemplate.svg
  src/assets/QuickClusterPreview.svg
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/index.ts
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/components/organisms/DashboardPane/index.ts
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/StartProjectPane/ActionCard.styled.tsx
  src/components/organisms/StartProjectPane/ActionCard.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.styled.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
  src/models/ui.ts
  src/redux/reducers/ui.ts
  src/utils/hooks.ts
Labels: size/XL

#2831 Razvantopliceanu/chore/merging
  electron/app/menu.ts
  src/assets/FromScratch.svg
  src/assets/FromTemplate.svg
  src/assets/QuickClusterPreview.svg
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/index.ts
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/components/organisms/DashboardPane/index.ts
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PaneManager/MenuButton/MenuButton.styled.tsx
  src/components/organisms/PaneManager/MenuButton/MenuButton.tsx
  src/components/organisms/PaneManager/MenuButton/index.ts
  src/components/organisms/PaneManager/MenuIcon.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.styled.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerRightMenu.styled.tsx
  src/components/organisms/PaneManager/PaneManagerRightMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.styled.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/components/organisms/PaneManager/PaneTooltip/PaneTooltip.tsx
  src/components/organisms/PaneManager/PaneTooltip/index.ts
  src/components/organisms/PaneManager/index.ts
  src/components/organisms/PaneManager/react-reflex/package.json
  src/components/organisms/PaneManager/react-reflex/readme.md
  src/components/organisms/PaneManager/react-reflex/types.d.ts
  src/components/organisms/PaneManager/styled.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/StartProjectPane/ActionCard.styled.tsx
  src/components/organisms/StartProjectPane/ActionCard.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.styled.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
  src/components/organisms/index.ts
  src/components/organisms_new/PaneManager/PaneManager.tsx
  src/components/organisms_new/PaneManager/activities.tsx
  src/redux/reducers/ui.ts
  src/redux/services/kubeConfigMonitor.ts
  src/shared/models/ui.ts
  src/utils/hooks.ts
Labels: size/XXL

#2832 fix: key warning
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
Labels: size/XS

#2833 fix: fix kubeConfig mismatch
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
  src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts
  src/navsections/KustomizePatchSectionBlueprint/KustomizePatchSectionBlueprint.ts
  src/redux/selectors.ts
  src/redux/thunks/applyMultipleResources.ts
  src/redux/thunks/runPreviewConfiguration.ts
Labels: size/S

#2834 Erdikose/chore/merging
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
  src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts
  src/navsections/KustomizePatchSectionBlueprint/KustomizePatchSectionBlueprint.ts
  src/redux/selectors.ts
  src/redux/thunks/applyMultipleResources.ts
  src/redux/thunks/runPreviewConfiguration.ts
Labels: size/S

#2835 refactor: disconnect cluster on logo click
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
Labels: size/S
