Repository kubeshop/monokle, pull requests merged in 2022-01, with the labels that each got.

#1006 fix: prevent to convert null value to Base64
  src/components/molecules/FormEditor/FormWidgets/SecretKindResourceForm.tsx
Labels: size/S

#1009 fix: updated kustomization schema, electron version and improved hand…
  package.json
  resources/schemas/kustomization.json
  src/redux/thunks/setRootFolder.ts
Labels: size/L

#1005 Erdikose/feature/sign publish nightly builds
  .github/workflows/monokle-build-nightly.yml
Labels: size/L

#1010 fix: added USE_HARD_LINKS: false to electron builder actions
  .github/workflows/monokle-build-nightly.yml
  .github/workflows/monokle-sign-notarize-publish-linux.yml
  .github/workflows/monokle-sign-notarize-publish.yml
Labels: size/XS

#1011 fix: set electron-builder version to 22.11.7
  package.json
Labels: size/XS

#1012 feat: add name context to section header
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/SectionRenderer/useSectionCustomization.ts
  src/models/navigator.ts
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts
Labels: size/M

#1014 fix: see more documentation flicker
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/XS

#1016 Update Remaining Monokle 1.4.0 Docs
  docs/apply-and-diff.md
  docs/architecture.md
  docs/development.md
  docs/faq.md
  docs/img/deploy-and-diff-buttons-1.5.0.png
  mkdocs.yml
Labels: size/L

#1019 feat: added setting for enabling Helm with Kustomize
  electron/commands.ts
  electron/main.ts
  package.json
  src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
  src/constants/tooltips.ts
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/ui.ts
  src/redux/thunks/previewKustomization.ts
Labels: size/L

#865 feat: Templates, Template Packs and Plugins first iteration
  electron/extensions/downloadExtension.ts
  electron/extensions/downloadExtensionEntry.ts
  electron/extensions/fileSystem.ts
  electron/extensions/loadExtension.ts
  electron/extensions/loadMultipleExtensions.ts
  electron/extensions/types.ts
  electron/main.ts
  electron/pluginService.ts
  electron/templateService.ts
  electron/utils.ts
  package-lock.json
  package.json
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/SectionRenderer/useSectionCustomization.ts
  src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
  src/components/molecules/TemplateFormRenderer/index.ts
  src/components/molecules/index.ts
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/PluginManagerPane/PluginInformation.styled.tsx
  src/components/organisms/PluginManagerPane/PluginInformation.tsx
  src/components/organisms/PluginManagerPane/PluginInstallModal.tsx
  src/components/organisms/PluginManagerPane/PluginManagerPane.styled.tsx
  src/components/organisms/PluginManagerPane/PluginManagerPane.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
  src/components/organisms/TemplateManagerPane/TemplateInstallModal.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
  src/components/organisms/TemplateManagerPane/index.ts
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/components/organisms/TemplateModal/index.ts
  src/components/organisms/TemplateModal/styled.tsx
  src/components/organisms/TemplatesPane/TemplatesPane.tsx
  src/components/organisms/TemplatesPane/index.ts
  src/components/organisms/index.ts
  src/constants/ipcEvents.ts
  src/constants/tooltips.ts
  src/feature-flags.json
  src/models/appconfig.ts
  src/models/appstate.ts
  src/models/extension.ts
  src/models/plugin.ts
  src/models/repository.ts
  src/models/template.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/extension.ts
  src/redux/reducers/main.ts
  src/redux/services/extension.ts
  src/redux/services/previewReferencedHelmChart.ts
  src/redux/services/templates.ts
  src/redux/store.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/types.d.ts
  src/utils/helm.ts
Labels: size/XXL

#952 Erdikose/feature/getting started wizard
  electron/main.ts
  electron/menu.ts
  electron/src/initKubeconfig.ts
  package-lock.json
  package.json
  src/App.tsx
  src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/CreateProjectModal/index.ts
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/PageFooter/PageFooter.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
  src/components/organisms/RecentProjectsPane/index.ts
  src/components/organisms/SettingsDrawer/Settings.tsx
  src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
  src/components/organisms/StartProjectPane/StartProjectPane.tsx
  src/components/organisms/StartProjectPane/index.ts
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/constants/constants.ts
  src/constants/tooltips.ts
  src/hooks/useTargetClusterNamespaces.ts
  src/models/appconfig.ts
  src/models/kubeConfig.ts
  src/models/ui.ts
  src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionEmptyDisplay.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts
  src/navsections/KustomizePatchSectionBlueprint/KustomizePatchSectionBlueprint.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/ui.ts
  src/redux/selectors.ts
  src/redux/services/applyMultipleResources.ts
  src/redux/services/fileEntry.ts
  src/redux/services/fileMonitor.ts
  src/redux/services/helm.ts
  src/redux/services/projectConfig.ts
  src/redux/services/projectConfigMonitor.ts
  src/redux/thunks/loadClusterDiff.ts
  src/redux/thunks/loadKubeConfig.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/setRootFolder.ts
  src/styles/Colors.ts
  src/utils/electronStore.ts
Labels: size/XXL

#987 feat: add glyph ref icons
  src/assets/IncomingRefsIcon.svg
  src/assets/OutgoingRefsIcon.svg
  src/components/molecules/Monaco/codeIntel.ts
  src/components/molecules/Monaco/editorConstants.ts
  src/components/molecules/Monaco/editorHelpers.ts
  src/index.css
Labels: size/L

#1045 fix: message typo
  electron/utils.ts
Labels: size/XS

#1044 feat: support for vanilla templates
  electron/templateService.ts
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/models/template.ts
  src/redux/services/manifest-utils.ts
  src/redux/services/previewReferencedHelmChart.ts
  src/redux/services/templates.ts
Labels: size/L

#1046 refactor: remove template install button and modal
  src/components/organisms/TemplateManagerPane/TemplateInstallModal.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
  src/redux/services/extension.ts
Labels: size/L

#1047 fix: recent projects scrollbar style
  src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
Labels: size/XS

#1050 fix: delete icon overflow text template information
  src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
Labels: size/S

#1023 fix: ignore parsing helm templates
  src/redux/services/fileEntry.test.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
Labels: size/S

#1053 fix: truncate title + fix width open button
  src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
Labels: size/M

#1054 feat: error boundary for template form renderer
  src/components/molecules/TemplateFormRenderer/TemplateFormErrorBoundary.tsx
  src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
Labels: size/M

#1055 fix: truncate step name + max height for modal content
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/components/organisms/TemplateModal/styled.tsx
Labels: size/M

#1027 Monokle Features Update 18/01/2022
  docs/img/create-resource-from-unsatisfied-link-1.5.0.png
  docs/img/explorer-file-actions-1.4.0.png
  docs/img/navigate-history-1.5.0.png
  docs/img/resource-diff-1.4.0.png
  docs/img/resource-open-k8s-documentation-1.5.0.png
  docs/overview.md
  docs/resource-editing.md
  docs/resource-navigation.md
Labels: size/S

#1052 Monokle Features Doc Updates 19/01/2022
  docs/helm.md
  docs/img/create-resource-unsatisfied-link-1.5.0.png
  docs/img/filter-from-editor-1.5.0.png
  docs/overview.md
  docs/resource-editing.md
  docs/resource-navigation.md
Labels: size/S

#1060 feat: search bar for templates and plugins
  src/components/organisms/PluginManagerPane/PluginManagerPane.styled.tsx
  src/components/organisms/PluginManagerPane/PluginManagerPane.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
Labels: size/L

#1058 Erdikose/feat/recent projects menu
  electron/main.ts
  electron/menu.ts
  electron/utils.ts
  src/App.tsx
  src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/M

#1061 fix template loading state on error and improve message
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/redux/services/templates.ts
Labels: size/XS

#1056 feat: Add Create Project menu to application menu
  electron/menu.ts
  src/App.tsx
  src/components/organisms/StartProjectPane/StartProjectPane.tsx
Labels: size/M

#1043 network policy form editor & script for other resources
  package.json
  resources/form-schemas/networkpolicy-schema.json
  resources/form-schemas/networkpolicy-ui-schema.json
  src/scripts/generate-schema.ts
  src/scripts/index.ts
Labels: size/XL

#1040 fix: disable tool menu when no active project
  src/components/organisms/PaneManager/MenuButton.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/StartProjectPane/StartProjectPane.tsx
Labels: size/M

#1066 Olelensmar/fix/template fixes
  src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
Labels: size/XS

#1067 fix: add badge to tool icons
  src/components/organisms/PaneManager/PaneManager.tsx
Labels: size/M

#1031 Create Project management dropdown
  src/App.tsx
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/PageHeader/Styled.tsx
  src/components/organisms/PageHeader/tooltips.ts
  src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
  src/components/organisms/StartProjectPane/StartProjectPane.tsx
  src/components/organisms/StartProjectPane/Styled.tsx
  src/constants/tooltips.ts
  src/index.css
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/services/projectConfig.ts
  src/redux/services/projectConfigMonitor.ts
  src/redux/thunks/loadKubeConfig.ts
  src/utils/electronStore.ts
Labels: size/XXL

#1070 feat: template information step
  src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/components/organisms/TemplateModal/styled.tsx
  src/scripts/generate-schema.ts
  src/scripts/index.ts
Labels: size/L

#1072 fix: remove intro page from formData array
  src/components/organisms/TemplateModal/TemplateModal.tsx
Labels: size/XS

#1073 feat: separate scrollbar for steps and form on modal
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/components/organisms/TemplateModal/styled.tsx
Labels: size/M

#1078 fix: show files to be replaced for <root>
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
Labels: size/XS

#1084 fix: propagation of namespace in generated manifests
  src/redux/services/templates.ts
Labels: size/XS

#1085 fix: persist left pane last size
  src/components/atoms/SplitView/SplitView.tsx
Labels: size/XS

#1083 Erdikose/fix/cluster configuration
  package-lock.json
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
  src/redux/reducers/appConfig.ts
  src/redux/selectors.ts
  src/redux/services/projectConfig.ts
  src/redux/services/projectConfigMonitor.ts
  src/utils/electronStore.ts
Labels: size/L

#1087 fix: use context name instead of cluster in UI
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/redux/thunks/loadKubeConfig.ts
Labels: size/S

#1088 refactor: templates pane redesign
  src/assets/TemplateIcon.svg
  src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
  src/constants/constants.ts
  src/styles/Colors.ts
Labels: size/L

#1090 fix: have auto rows with max content for templates
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
Labels: size/XS

#1089 chore: add error logging
  src/redux/services/projectConfig.ts
  src/redux/thunks/loadKubeConfig.ts
Labels: size/S

#1095 feat: unseen notifications badge
  src/components/organisms/MessageBox/MessageBox.tsx
  src/components/organisms/NotificationsDrawer/NotificationsDrawer.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/redux/reducers/main.ts
Labels: size/S

#1096 fix section header padding and quick preview padding
  src/components/molecules/QuickActionPreview/styled.tsx
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/SectionRenderer/styled.tsx
Labels: size/S

#1094 refactor: templates pane redesign
  src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
  src/constants/constants.ts
Labels: size/M

#1103 fix: small UI style bugs
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/PageHeader/Styled.tsx
  src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
  src/components/organisms/RecentProjectsPane/Styled.tsx
Labels: size/L

#1086 refactor: save duplicate resources with suffix
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
Labels: size/L

#1059 feat: settings improvements
  src/App.tsx
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/SettingsDrawer/Settings.tsx
  src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
  src/components/organisms/SettingsDrawer/Styles.tsx
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/services/projectConfig.ts
  src/redux/services/projectConfigMonitor.ts
Labels: size/L

#1112 refactor: cluster selector
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/PageHeader/Styled.tsx
Labels: size/XL

#1114 fix: correct import typo
  src/components/organisms/PageHeader/PageHeader.tsx
Labels: size/XS

#1115 fix: file typo
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/styled.tsx
Labels: size/XS

#1113 fix: fixed Helm-icon badge and improved rolebinding forms
  resources/form-schemas/clusterrolebinding-schema.json
  resources/form-schemas/clusterrolebinding-ui-schema.json
  resources/form-schemas/rolebinding-schema.json
  resources/form-schemas/rolebinding-ui-schema.json
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
  src/models/ui.ts
  src/redux/reducers/ui.ts
Labels: size/M

#1079 feat: KindHandlers and SectionBlueprints reactivity
  electron/ipcMainRedux.ts
  electron/main.ts
  electron/menu.ts
  src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
  src/components/molecules/Monaco/codeIntel.ts
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/molecules/SectionRenderer/SectionRenderer.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/components/organisms/QuickSearchActions/QuickSearchActions.tsx
  src/index.tsx
  src/kindhandlers/index.ts
  src/models/appconfig.ts
  src/models/appdispatch.ts
  src/models/appstate.ts
  src/models/kustomize.ts
  src/models/navigator.ts
  src/models/rootstate.ts
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameSuffix.tsx
  src/navsections/UnknownResourceSectionBlueprint/UnknownResourceSectionBlueprint.ts
  src/navsections/sectionBlueprintMap.ts
  src/navsections/sectionBlueprintMiddleware.ts
  src/redux/hooks.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/main.ts
  src/redux/reducers/navigator.ts
  src/redux/selectors.ts
  src/redux/services/applyMultipleResources.ts
  src/redux/services/extension.ts
  src/redux/services/fileMonitor.ts
  src/redux/services/getClusterObjects.ts
  src/redux/services/kustomize.ts
  src/redux/services/log.ts
  src/redux/services/preview.ts
  src/redux/services/previewReferencedHelmChart.ts
  src/redux/services/projectConfig.ts
  src/redux/services/projectConfigMonitor.ts
  src/redux/services/renameResource.ts
  src/redux/services/resource.ts
  src/redux/services/templates.ts
  src/redux/services/unsavedResource.ts
  src/redux/store.ts
  src/redux/storeListeners.ts
  src/redux/thunks/applyCheckedResources.ts
  src/redux/thunks/applyFile.ts
  src/redux/thunks/applyHelmChart.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/applySelectedResourceMatches.ts
  src/redux/thunks/loadClusterDiff.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/replaceSelectedResourceMatches.ts
  src/redux/thunks/saveUnsavedResources.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/XL

#1116 fix: disabled templates in preview mode
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
Labels: size/S

#1118 fix: set default value for undefined lastOpen date
  src/redux/reducers/appConfig.ts
Labels: size/XS

#1117 refactor: improve TemplateInformation UI
  src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
Labels: size/M

#1120 refactor: make template repository optional
  electron/templateService.ts
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/models/template.ts
Labels: size/S

#1119 chore: add padding to skeletons
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
Labels: size/S

#1122 plugin manager pane styling improvements
  src/components/organisms/PluginManagerPane/PluginInformation.styled.tsx
  src/components/organisms/PluginManagerPane/PluginInformation.tsx
  src/components/organisms/PluginManagerPane/PluginManagerPane.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
Labels: size/L

#1123 Template Modal improvements
  src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/components/organisms/TemplateModal/styled.tsx
Labels: size/M

#1099 Olelensmar/fix/improved isKustomization check
  src/components/molecules/PreviewDropdown/PreviewDropdown.tsx
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/constants/constants.ts
  src/kindhandlers/common/customObjectKindHandler.ts
  src/kindhandlers/index.ts
  src/models/resourcekindhandler.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
  src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts
  src/navsections/UnknownResourceSectionBlueprint/UnknownResourceSectionBlueprint.ts
  src/redux/reducers/main.ts
  src/redux/reducers/ui.ts
  src/redux/services/kustomize.ts
  src/redux/services/resource.ts
Labels: size/M

#1124 feat: hide icons, tooltips added, description
  package-lock.json
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
Labels: size/L

#1131 fix: removed bundled crds for argo rollouts/cd and emissary,
  resources/kindhandlers/crds/argo-rollouts/analysis-run-crd.yaml
  resources/kindhandlers/crds/argo-rollouts/analysis-template-crd.yaml
  resources/kindhandlers/crds/argo-rollouts/cluster-analysis-template-crd.yaml
  resources/kindhandlers/crds/argo-rollouts/experiment-crd.yaml
  resources/kindhandlers/crds/argo-rollouts/rollout-crd.yaml
  resources/kindhandlers/crds/argocd/application.crd.yaml
  resources/kindhandlers/crds/argocd/appproject.crd.yaml
  resources/kindhandlers/crds/emissary/emissary-crds.yaml
Labels: size/XXL

#1132 feat: add ability to change project name
  src/components/organisms/SettingsDrawer/Settings.tsx
  src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
  src/redux/reducers/appConfig.ts
Labels: size/M

#1128 feat: load default plugins
  electron/main.ts
  src/constants/constants.ts
Labels: size/S

#1104 Create Project from Templates
  electron/src/initKubeconfig.ts
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
  src/components/organisms/TemplateModal/TemplateModal.tsx
Labels: size/L

#1133 fix: section quick create button color
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameSuffix.tsx
Labels: size/S

#1136 Current context name is not shown when in cluster mode
  src/components/organisms/PageHeader/PageHeader.tsx
Labels: size/XS

#1135 fix: hide left menu icons badges after pane opens
  src/components/organisms/PaneManager/PaneManager.tsx
Labels: size/M

#1137 chore: set correct value change on project change
  src/components/organisms/SettingsDrawer/Settings.tsx
Labels: size/XS

#1126 feat: get back to start project page action
  docs/overview.md
  electron/menu.ts
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/PageHeader/styled.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/constants/constants.ts
  src/constants/hotkeys.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/ui.ts
Labels: size/L

#1138 refactor: improve left menu icons tooltips
  src/components/organisms/PaneManager/PaneManager.tsx
  src/constants/tooltips.ts
Labels: size/M

#1111 fix: styling project management
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/PageHeader/styled.tsx
  src/index.css
  src/styles/Colors.ts
Labels: size/L

#1140 fix: ellipsis for cluster context name
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
Labels: size/M

#1141 feat: Changed icons accoding to design
  src/assets/SelectAnEmptyProject.svg
  src/assets/SelectAnExistingFolder.svg
  src/assets/StartBackground.svg
  src/assets/StartFromTemplate.svg
  src/components/organisms/StartProjectPane/StartProjectPane.tsx
  src/components/organisms/StartProjectPane/Styled.tsx
  src/styles/Colors.ts
Labels: size/L

#1144 refactor: warnings/errors redesign
  src/components/atoms/MonoPaneTitle/MonoPaneTitle.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/NavigatorPane/WarningAndErrorsDisplay.styled.tsx
  src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
Labels: size/L

#1143 chore: update README
  README.md
  docs/img/linux.svg
  docs/img/macos.svg
  docs/img/windows.svg
Labels: size/L

#1142 fix: table padding
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/index.css
Labels: size/S

#1150 feat: If there is no recent projects - hide panel
  src/components/organisms/PaneManager/PaneManager.tsx
Labels: size/S

#1148 refactor: move plugins to drawer
  src/App.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/styled.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/PluginManagerDrawer/PluginInformation.styled.tsx
  src/components/organisms/PluginManagerDrawer/PluginInformation.tsx
  src/components/organisms/PluginManagerDrawer/PluginInstallModal.tsx
  src/components/organisms/PluginManagerDrawer/PluginManagerDrawer.styled.tsx
  src/components/organisms/PluginManagerDrawer/PluginManagerDrawer.tsx
  src/components/organisms/PluginManagerDrawer/index.ts
  src/components/organisms/PluginManagerPane/index.ts
  src/components/organisms/index.ts
  src/constants/tooltips.ts
  src/models/extension.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/extension.ts
Labels: size/L

#1147 fix: fixed retreival of schemas for dynamically loaded kindhandlers
  src/redux/services/schema.ts
Labels: size/XS

#1151 refactor: new styling for refs popover links
  src/components/molecules/ResourceRefsIconPopover/RefLink.styled.tsx
  src/components/molecules/ResourceRefsIconPopover/RefLink.tsx
Labels: size/L

#1157 refactor: change settings/quick search hotkeys
  docs/overview.md
  src/constants/hotkeys.ts
Labels: size/XS

#1146 fix: remove gap between context menu icon and dropdown
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
Labels: size/L

#1158 fix: dismiss project management selection by press escape
  src/components/organisms/PageHeader/ProjectSelection.tsx
Labels: size/S

#1160 fix: different color on hover for toolbar buttons
  src/components/organisms/PaneManager/MenuButton.tsx
Labels: size/S

#1161 fix: remove highlighting of matchLabels in a selector
  src/components/molecules/Monaco/symbolProcessing.ts
Labels: size/XS

#1156 fix: hover cluster load
  src/components/organisms/PageHeader/ClusterSelection.tsx
Labels: size/S

#1155 Erdikose/feature/add default project root
  electron/main.ts
  electron/utils.ts
  package-lock.json
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/SettingsDrawer/Settings.tsx
  src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/services/projectConfig.ts
  src/utils/electronStore.ts
Labels: size/L

#1166 fix: mark active project in recent projects pane
  src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
  src/components/organisms/RecentProjectsPane/Styled.tsx
Labels: size/M

#1167 fix: ensure namespace is parsed correctly when reparsing
  src/redux/services/resource.ts
Labels: size/S

#1165 fix: deleting active project issue
  src/components/organisms/PaneManager/PaneManager.tsx
  src/redux/reducers/appConfig.ts
Labels: size/XS

#1168 fix: quick search tooltip & resize settings icons
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/components/organisms/PageHeader/styled.tsx
  src/constants/tooltips.ts
Labels: size/M

#1169 fix: update kustomization check for Metadata Form editor
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/XS

#1172 fix: check pod template labels when filtering on label
  src/utils/resources.ts
Labels: size/XS

#1171 fix: dismiss cluster dropdown when press escape
  src/components/organisms/PageHeader/ClusterSelection.tsx
Labels: size/S

#1125 docs: first draft for templates/plugins docs
  docs/plugins.md
  docs/templates.md
  mkdocs.yml
Labels: size/L

#1170 fix: disable deploy/diff for unknown resources
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/S

#1175 fix: remove expand/collapse icons, move suffix to the right
  src/components/molecules/SectionRenderer/SectionHeader.tsx
Labels: size/S

#1176 fix: add scrollbar style to settings pane
  src/components/organisms/SettingsDrawer/SettingsDrawer.tsx
  src/components/organisms/SettingsDrawer/Styles.tsx
Labels: size/S

#1178 fix: center icons in top right corner
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/styled.tsx
Labels: size/M

#1181 fix: filter unsupported or excluded file names from append to file
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
Labels: size/M

#1184 fix: recent project folder path max width
  src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
  src/components/organisms/RecentProjectsPane/Styled.tsx
Labels: size/S

#1185 fix: pipeline for release
  .github/workflows/monokle-publish-updater.yml
  .github/workflows/monokle-publish.yml
Labels: size/S

#1193 fix: save project file
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
Labels: size/XS

#1196 fix: validator-cache now uses resource kind+apiVersion for key
  src/redux/services/validation.ts
Labels: size/XS

#1197 fix: filter only files by isSupported and isExcluded
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
Labels: size/S

#1200 fix: close modal if selecting from dropdown the same selected resource
  src/components/organisms/QuickSearchActions/QuickSearchActions.tsx
Labels: size/XS

#1202 fix: close dropdown on cluster select
  src/components/organisms/PageHeader/ClusterSelection.tsx
Labels: size/S

#1201 fix: kustomization parsing to ignore external resources and block pat…
  src/redux/services/kustomize.ts
Labels: size/M

#1203 fix: enable cluster selector when in preview mode
  src/components/organisms/PageHeader/ClusterSelection.tsx
Labels: size/XS

#1204 fix: open local diff modal for resources from preview mode
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
Labels: size/XS

#1206 fix: code editor intelligence for selected path
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/hooks/useResourceYamlSchema.ts
Labels: size/M

#1208 Erdikose/fix/load project settings correctly
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/Styled.tsx
  src/redux/reducers/appConfig.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/XL

#1210 fix: missing footer border top for editor pane
  src/constants/constants.ts
Labels: size/XS

#1211 fix: create project if there is none
  src/App.tsx
Labels: size/S

#1194 fix: style Recent Project improvements & clicn on whole item
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/PaneManager/Styled.tsx
  src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
  src/components/organisms/RecentProjectsPane/Styled.tsx
Labels: size/L

#1209 Olelensmar/docs/license and template widgets
  LICENSE
  docs/img/default-templates.png
  docs/templates.md
  mkdocs.yml
Labels: size/M

#1217 fix: diffing cluster resource would lead to error
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
Labels: size/M

#1219 chore: remove unused function
  electron/src/initKubeconfig.ts
Labels: size/XS

#1220 docs: added some more links and a subsection for our custom widgets
  docs/templates.md
Labels: size/S

#1215 tests & adding them to the nightly builds
  .github/workflows/monokle-build-nightly.yml
  .github/workflows/monokle-ui-tests.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  src/components/atoms/SplitView/SplitView.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/HelmPane/HelmPane.tsx
  src/components/organisms/KustomizePane/KustomizePane.tsx
  src/components/organisms/PageFooter/PageFooter.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/StartupModal/StartupModal.tsx
  tests/antdHelpers.ts
  tests/argo-rollouts/base/argo-rollouts-aggregate-roles.yaml
  tests/argo-rollouts/base/argo-rollouts-deployment.yaml
  tests/argo-rollouts/base/argo-rollouts-metrics-service.yaml
  tests/argo-rollouts/base/argo-rollouts-sa.yaml
  tests/argo-rollouts/base/kustomization.yaml
  tests/argo-rollouts/cluster-install/argo-rollouts-clusterrolebinding.yaml
  tests/argo-rollouts/cluster-install/kustomization.yaml
  tests/argo-rollouts/crds/analysis-run-crd.yaml
  tests/argo-rollouts/crds/analysis-template-crd.yaml
  tests/argo-rollouts/crds/cluster-analysis-template-crd.yaml
  tests/argo-rollouts/crds/experiment-crd.yaml
  tests/argo-rollouts/crds/kustomization.yaml
  tests/argo-rollouts/crds/rollout-crd.yaml
  tests/argo-rollouts/install.yaml
  tests/argo-rollouts/namespace-install.yaml
  tests/argo-rollouts/namespace-install/add-namespaced-flag.yaml
  tests/argo-rollouts/namespace-install/argo-rollouts-rolebinding.yaml
  tests/argo-rollouts/namespace-install/clusterrole-to-role.yaml
  tests/argo-rollouts/namespace-install/kustomization.yaml
  tests/argo-rollouts/role/argo-rollouts-clusterrole.yaml
  tests/argo-rollouts/role/kustomization.yaml
  tests/base.test.ts
  tests/electronHelpers.ts
Labels: size/XXL

#1227 fix: resolve relative path
  src/App.tsx
Labels: size/XS

#1229 feat: updated to electron 16.0.8
  package.json
Labels: size/XS

#1225 fix: update active forms
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/XS

#1226 refactor: lazy loading app modals/drawers
  src/App.tsx
  src/components/molecules/ChangeFiltersConfirmModal/ChangeFiltersConfirmModal.tsx
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
  src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
  src/components/organisms/CreateFolderModal/CreateFolderModal.tsx
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/CreateProjectModal/index.ts
  src/components/organisms/LazyDrawer/LazyDrawer.tsx
  src/components/organisms/LazyDrawer/index.ts
  src/components/organisms/MessageBox/MessageBox.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/components/organisms/NotificationsDrawer/NotificationsDrawer.tsx
  src/components/organisms/NotificationsDrawer/index.ts
  src/components/organisms/NotificationsManager/NotificationsManager.tsx
  src/components/organisms/NotificationsManager/index.ts
  src/components/organisms/NotificationsManager/styled.tsx
  src/components/organisms/PluginManager/PluginInformation.styled.tsx
  src/components/organisms/PluginManager/PluginInformation.tsx
  src/components/organisms/PluginManager/PluginInstallModal.tsx
  src/components/organisms/PluginManager/PluginManager.styled.tsx
  src/components/organisms/PluginManager/PluginManager.tsx
  src/components/organisms/PluginManager/index.ts
  src/components/organisms/PluginManagerDrawer/index.ts
  src/components/organisms/RenameEntityModal/RenameEntityModal.tsx
  src/components/organisms/RenameResourceModal/RenameResourceModal.tsx
  src/components/organisms/SettingsDrawer/index.ts
  src/components/organisms/SettingsManager/Settings.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/SettingsManager/index.ts
  src/components/organisms/SettingsManager/styled.tsx
  src/components/organisms/UpdateModal/UpdateModal.tsx
  src/components/organisms/index.ts
Labels: size/XL

#1233 fix: project selection small improvements
  src/components/organisms/PageHeader/ProjectSelection.tsx
Labels: size/S

#1230 fix: Kustomize schema/forms and errors related to conflicts with Flux
  package.json
  resources/schemas/kustomization.json
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/constants/constants.ts
  src/constants/tooltips.ts
  src/kindhandlers/common/customObjectKindHandler.ts
  src/redux/services/fileEntry.ts
  src/redux/services/resource.ts
Labels: size/XL

#1224 feat: configure default object/primitive value creation in form editor
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/organisms/SettingsManager/Settings.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/kindhandlers/index.ts
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/selectors.ts
  src/redux/services/__test__/schemas/flux-kustomization-schema.yaml
  src/redux/services/projectConfig.ts
  src/redux/services/schema.test.ts
  src/redux/services/schema.ts
  src/utils/electronStore.ts
Labels: size/XL

#1245 chore(release): 1.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/M

#1192 Julianne/doc/monokle/features updates 1.5.0 19 01 2022
  docs/cluster-compare.md
  docs/cluster-integration.md
  docs/features.md
  docs/helm.md
  docs/img/cluster-compare-button-1.5.0.png
  docs/img/cluster-preview-1.5.0.png
  docs/img/cluster-reload-1.5.0.png
  docs/img/cluster-save-multiple-resources-1.5.0.png
  docs/img/deploy-and-diff-buttons-1.5.0.png
  docs/img/explorer-file-actions-1.5.0.png
  docs/img/explorer-folder-actions-1.5.0.png
  docs/img/form-editor-1.5.0.png
  docs/img/helm-navigation-1.5.0.png
  docs/img/helm-preview-output-1.5.0.png
  docs/img/kust-preview-reload-1.5.0.png
  docs/img/kustomize-navigation-1.5.0.png
  docs/img/kustomize-preview-1.5.0.png
  docs/img/kustomize-preview-content-1.5.0.png
  docs/img/mac-system-menu-1.5.0.png
  docs/img/manage-multiple-projects.gif
  docs/img/monokle-settings-1.5.0.gif
  docs/img/monokle-ui-1.5.0.png
  docs/img/multiple-window-1.5.0.png
  docs/img/navigation-history-1.5.0.png
  docs/img/recent-folders-1.5.0.png
  docs/img/resource-filtering-1.5.0.png
  docs/img/resource-navigation-1-1.5.0.png
  docs/img/resource-navigation-2-1.5.0.png
  docs/img/select-multi-resource-1.5.0.png
  docs/img/source-editor-command-palette-1.5.0.png
  docs/kustomize.md
  docs/overview.md
  docs/resource-editing.md
  docs/resource-navigation.md
Labels: size/M

#1246 Update Monokle Doc 31/01/2022
  docs/hotkeys.md
  docs/overview.md
Labels: size/L
