Repository kubeshop/monokle, pull requests merged in 2022-03, with the labels that each got.

#1413 chore: update codeowners
  .github/CODEOWNERS
Labels: size/XS

#1409 Feature/favorite templates
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/utils/electronStore.ts
Labels: size/M

#1399 feat: add nucleus.sh integration
  electron/main.ts
  electron/preload.ts
  electron/utils.ts
  package-lock.json
  package.json
  src/App.tsx
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/constants/tooltips.ts
  src/models/appconfig.ts
  src/models/appstate.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/saveUnsavedResources.ts
  src/redux/thunks/setRootFolder.ts
  src/utils/electronStore.ts
  src/utils/shell.ts
  src/utils/telemetry.ts
Labels: size/L

#1411 project name added to window title
  electron/main.ts
Labels: size/XS

#1422 propagate project name changes across windows
  electron/main.ts
  src/App.tsx
  src/redux/reducers/appConfig.ts
  src/utils/global-electron-store.ts
Labels: size/M

#1431 chore: Telemetry reviews fixes
  electron/main.ts
  electron/utils.ts
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/saveUnsavedResources.ts
  src/redux/thunks/setRootFolder.ts
  src/utils/shell.ts
  src/utils/telemetry.ts
Labels: size/M

#1432 feat: Improve plugins install URL support
  electron/extensions/downloadExtension.ts
  electron/extensions/downloadExtensionEntry.ts
  electron/extensions/fileSystem.ts
  electron/extensions/loadExtension.ts
  electron/pluginService.ts
  electron/templateService.ts
  electron/utils.ts
  package-lock.json
  package.json
  src/components/organisms/PluginManager/PluginInstallModal.tsx
Labels: size/L

#1440 fix: handle plugin import model error message cache problem
  electron/extensions/downloadExtension.ts
  src/components/organisms/PluginManager/PluginInstallModal.tsx
Labels: size/XS

#1438 fix: added isNamespaced to ResourceKindHandler
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
  src/kindhandlers/ClusterRole.handler.ts
  src/kindhandlers/ClusterRoleBinding.handler.ts
  src/kindhandlers/ConfigMap.handler.ts
  src/kindhandlers/CronJob.handler.ts
  src/kindhandlers/CustomResourceDefinition.handler.ts
  src/kindhandlers/DaemonSet.handler.ts
  src/kindhandlers/Deployment.handler.ts
  src/kindhandlers/Endpoints.handler.ts
  src/kindhandlers/Ingress.handler.ts
  src/kindhandlers/Job.handler.ts
  src/kindhandlers/Namespace.handler.ts
  src/kindhandlers/NetworkPolicy.handler.ts
  src/kindhandlers/PersistentVolume.handler.ts
  src/kindhandlers/PersistentVolumeClaim.handler.ts
  src/kindhandlers/Pod.handler.ts
  src/kindhandlers/ReplicaSet.handler.ts
  src/kindhandlers/ReplicationController.handler.ts
  src/kindhandlers/Role.handler.ts
  src/kindhandlers/RoleBinding.handler.ts
  src/kindhandlers/Secret.handler.ts
  src/kindhandlers/Service.handler.ts
  src/kindhandlers/ServiceAccount.handler.ts
  src/kindhandlers/StatefulSet.handler.ts
  src/kindhandlers/VolumeAttachment.handler.ts
  src/kindhandlers/common/customObjectKindHandler.ts
  src/models/resourcekindhandler.ts
Labels: size/M

#1441 Fix nightly test
  .github/workflows/monokle-ui-tests.yml
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  tests/git.test.ts
  tests/models/mainWindow.ts
  tests/project.test.ts
Labels: size/M

#1442 fix: edge case when new project is created
  src/utils/global-electron-store.ts
Labels: size/XS

#1444 chore: update electron-unhandled version
  package-lock.json
  package.json
Labels: size/XS

#1412 feat: create/edit and run preview configurations
  src/App.tsx
  src/components/atoms/KeyValueInput/KeyValueInput.tsx
  src/components/atoms/OrderedList/OrderedList.tsx
  src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.tsx
  src/components/molecules/PreviewConfigurationDetails/index.ts
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/SectionRenderer/SectionRenderer.tsx
  src/components/molecules/SectionRenderer/styled.tsx
  src/components/molecules/index.ts
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
  src/constants/helmOptions.ts
  src/constants/tooltips.ts
  src/models/appconfig.ts
  src/models/appstate.ts
  src/navsections/HelmChartSectionBlueprint/FileItemPrefix.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/ItemPrefix.tsx
  src/navsections/HelmChartSectionBlueprint/PreviewConfigurationNameSuffix.tsx
  src/navsections/HelmChartSectionBlueprint/PreviewConfigurationQuickAction.tsx
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
  src/navsections/UnknownResourceSectionBlueprint/UnknownResourceSectionBlueprint.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/main.ts
  src/redux/selectors.ts
  src/redux/services/fileEntry.ts
  src/redux/services/preview.ts
  src/redux/services/projectConfig.ts
  src/redux/services/selection.ts
  src/redux/thunks/previewConfiguration.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/runPreviewConfiguration.ts
  src/utils/helm.ts
Labels: size/XXL, needs-ux-review

#1439 feat: initial support for sealed secrets and some bugfixes
  resources/kindhandlers/crds/bitnami/sealed-secret.yaml
  resources/kindhandlers/handlers/bitnami.com/SealedSecret.json
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/FormEditor/FormWidgets/index.ts
  src/kindhandlers/common/customObjectKindHandler.ts
  src/kindhandlers/common/outgoingRefMappers.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
  src/redux/services/schema.ts
Labels: size/L

#1434 Apply on ubuntu
  electron/commands.ts
  electron/main.ts
  electron/src/initKubeconfig.ts
  electron/utils.ts
  package.json
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
  src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.tsx
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/constants/tooltips.ts
  src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
  src/redux/services/applyMultipleResources.ts
  src/redux/services/index.ts
  src/redux/services/previewReferencedHelmChart.ts
  src/redux/services/resource.ts
  src/redux/thunks/applyFile.ts
  src/redux/thunks/applyHelmChart.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/applyYaml.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/runPreviewConfiguration.ts
  src/utils/alert.ts
  src/utils/command.ts
  src/utils/env.ts
  src/utils/helm.ts
  src/utils/index.ts
  src/utils/shell.ts
  src/utils/thread.ts
Labels: size/XL

#1446 change logo
  public/IconMonokle.svg
  src/assets/MonokleKubeshopLogo.svg
  src/assets/MonokleLogoDark.svg
  src/assets/MonokleLogoLight.svg
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/styled.tsx
Labels: size/L, needs-ux-review

#1410 #1287 Apply Changes not shown
  src/components/molecules/FilePatternList/FilePatternList.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/SettingsManager/Settings.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/main.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/M

#1443 moved reducers into thunks with related refactorings
  src/App.tsx
  src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/Monaco/useDebouncedCodeSave.ts
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/components/organisms/RenameResourceModal/RenameResourceModal.tsx
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/redux/reducers/main.ts
  src/redux/services/fileEntry.ts
  src/redux/services/fileMonitor.ts
  src/redux/services/projectConfig.ts
  src/redux/services/resource.ts
  src/redux/services/resourceRefs.ts
  src/redux/services/schema.ts
  src/redux/support/applyFileWithConfirm.tsx
  src/redux/support/replaceSelectedMatchesWithConfirm.tsx
  src/redux/thunks/applyCheckedResources.ts
  src/redux/thunks/applyMultipleResources.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/applySelectedResourceMatches.ts
  src/redux/thunks/multiplePathsAdded.ts
  src/redux/thunks/multiplePathsChanged.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/previewReferencedHelmChart.ts
  src/redux/thunks/removeResource.ts
  src/redux/thunks/renameResource.ts
  src/redux/thunks/replaceSelectedResourceMatches.ts
  src/redux/thunks/setRootFolder.ts
  src/redux/thunks/updateFileEntry.ts
  src/redux/thunks/updateManyResources.ts
  src/redux/thunks/updateResource.ts
  src/redux/thunks/utils.ts
Labels: size/XXL

#1447 fix: fixed compilation error and lint warnings
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/redux/thunks/applyMultipleResources.ts
  src/redux/thunks/previewHelmValuesFile.ts
Labels: size/M

#1450 fix: update values files in preview configurations
  src/components/atoms/OrderedList/OrderedList.tsx
  src/components/atoms/OrderedList/index.ts
  src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.tsx
  src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
  src/models/appconfig.ts
  src/redux/thunks/runPreviewConfiguration.ts
Labels: size/L

#1458 refactor: improve create project from template
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
Labels: size/M

#1459 fix: root folder name in File Explorer
  src/components/organisms/FileTreePane/FileTreePane.tsx
Labels: size/S

#1461 fix: add error message if preview configuration name is empty
  src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
  src/components/organisms/PreviewConfigurationEditor/styled.tsx
Labels: size/S

#1463 Monokle telemetry data
  docs/telemetry.md
Labels: size/S

#1468 fix: remove unused execSync
  src/redux/reducers/appConfig.ts
Labels: size/XS

#1464 Julianne/doc/monokle/needs docs issues 08 03 2022
  docs/img/select-and-manage-projects-1.5.0.png
  docs/img/select-folder-1.5.0.png
  docs/overview.md
  docs/projects.md
  docs/telemetry.md
  mkdocs.yml
Labels: size/M

#1469 fix: display error when cluster access cannot be checked
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/index.css
  src/redux/thunks/loadKubeConfig.ts
  src/utils/kubeclient.ts
Labels: size/M

#1471 feat: Release Notes modal and drawer
  resources/releaseNotes/1.5.1/1.5.1.json
  resources/releaseNotes/1.5.1/1.5.1.md
  resources/releaseNotes/1.5.1/1.5.1.svg
  resources/releaseNotes/1.6/1.6.json
  resources/releaseNotes/1.6/1.6.md
  resources/releaseNotes/1.6/1.6.svg
  src/App.tsx
  src/components/organisms/PageFooter/PageFooter.tsx
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/components/organisms/ReleaseNotes/ReleaseNotes.tsx
  src/components/organisms/ReleaseNotes/index.ts
  src/components/organisms/ReleaseNotes/styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/ui.ts
  src/styles/Colors.ts
  src/utils/appVersion.ts
  src/utils/electronStore.ts
Labels: size/L, needs-ux-review

#1474 fix: split updateResource thunk into reducer
  src/redux/reducers/main.ts
  src/redux/thunks/updateResource.ts
Labels: size/L

#1479 add release notes assets for 1.6.0
  resources/releaseNotes/1.6.0/1.6.0.json
  resources/releaseNotes/1.6.0/1.6.0.md
  resources/releaseNotes/1.6.0/1.6.0.svg
  resources/releaseNotes/1.6/1.6.json
  resources/releaseNotes/1.6/1.6.md
  resources/releaseNotes/1.6/1.6.svg
  src/components/organisms/PreviewConfigurationEditor/ValuesFilesList/SortableItem.tsx
  src/components/organisms/PreviewConfigurationEditor/ValuesFilesList/styled.tsx
Labels: size/M

#1477 Update overview.md
  docs/overview.md
Labels: size/XS

#1481 fix: add cluster access loading
  src/assets/MonokleLogoDark.svg
  src/assets/MonokleLogoLight.svg
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/models/appconfig.ts
  src/redux/reducers/appConfig.ts
  src/redux/thunks/loadKubeConfig.ts
Labels: size/M, needs-ux-review

#1482 fix: use immer in thunks to create next main state
  src/redux/reducers/main.ts
  src/redux/thunks/multiplePathsAdded.ts
  src/redux/thunks/multiplePathsChanged.ts
  src/redux/thunks/removeResource.ts
  src/redux/thunks/updateFileEntry.ts
  src/redux/thunks/updateManyResources.ts
  src/redux/thunks/updateResource.ts
Labels: size/L

#1483 Chlete replace preview configuration drawer img
  docs/img/preview-configuration-drawer.png
Labels: size/XS

#1473 docs: Helm Chart Preview Documentation
  docs/helm.md
  docs/img/helm-command-pane.png
  docs/img/helm-configuration-plus-sign.png
  docs/img/helm-preview-configurations.png
  docs/img/my-preview-configuration.png
  docs/img/preview-configuration-drawer.png
Labels: size/M

#1486 Andreiv1992/fix/cluster change loading error
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/utils/kubeclient.ts
Labels: size/S

#1490 Fix bin $PATH not set correctly
  electron/utils.ts
Labels: size/S

#1491 chore(release): 1.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#1493 fix: remove namespaces and don't add them back automatically
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/redux/reducers/appConfig.ts
  src/redux/thunks/loadKubeConfig.ts
  src/utils/electronStore.ts
  src/utils/kubeclient.ts
Labels: size/M

#1499 fix: checking missing dependencies
  electron/utils.ts
Labels: size/S

#1505 fix: panes overflow ( moving towards right )
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/Styled.tsx
  src/components/organisms/PaneManager/PaneMangerSplitView.tsx
Labels: size/S

#1504 Update link to new release blog post
  README.md
Labels: size/XS

#1509 chore: update electron and electron-builder
  package-lock.json
  package.json
Labels: size/XS

#1508 fix: cluster compare and resource diff when no namespaces is selected
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/redux/services/getClusterObjects.ts
  src/redux/thunks/applyFile.ts
  src/redux/thunks/applyMultipleResources.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/applyYaml.ts
  src/redux/thunks/loadClusterDiff.ts
Labels: size/M

#1511 chore(release): 1.6.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#1517 fix: paneConfiguration initial state and electronStore.onDidChange listener
  src/App.tsx
  src/redux/initialState.ts
  src/utils/global-electron-store.ts
Labels: size/S

#1518 fix: thunks that were mutating state directly
  src/redux/reducers/main.ts
Labels: size/L

#1519 chore(release): 1.6.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#1514 chore: allow meaningful display names for styled components in dev mode
  craco.config.js
  package-lock.json
  package.json
Labels: size/XS

#1523 chore: update codeowners
  .github/CODEOWNERS
  package-lock.json
Labels: size/XS

#1501 docs: Update Screenshots with New Logo Font
  docs/cluster-compare.md
  docs/features.md
  docs/img/cluster-compare-button-1.6.0.png
  docs/img/kust-preview-reload-1.6.0.png
  docs/img/kustomization-1.6.0.gif
  docs/img/kustomize-preview-1.6.0.png
  docs/img/kustomize-preview-content-1.6.0.png
  docs/img/manage-multiple-projects-1.6.0.gif
  docs/index.md
  docs/kustomize.md
  docs/projects.md
  docs/tutorials/how-to-create-and-edit-configmap.md
  docs/tutorials/img/image-10-1.6.0.png
  docs/tutorials/img/image-11-1.6.0.png
  docs/tutorials/img/image-12-1.6.0.png
  docs/tutorials/img/image-16-1.6.0.png
  docs/tutorials/img/image-17-1.6.0.png
  docs/tutorials/img/image-18-1.6.0.png
  docs/tutorials/img/image-7-1.6.0.png
  docs/tutorials/img/image-8-1.6.0.png
  docs/tutorials/img/image-9-1.6.0.png
  docs/tutorials/img/metadata-button-image-1.6.0.png
Labels: size/M

#1524 fix: provide output path on craco
  craco.config.js
Labels: size/XS

#1513 feat: file explorer: trancate names and add path for files
  src/components/organisms/FileTreePane/Styled.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
Labels: size/S

#1532 fix: PATH env variable
  electron/commands.ts
  electron/main.ts
  package-lock.json
  package.json
Labels: size/S

#1534 refactor: restructure electron folder
  .prettierignore
  electron/app/autoUpdater.ts
  electron/app/commands.ts
  electron/app/createWindow.ts
  electron/app/extensions/downloadExtension.ts
  electron/app/extensions/downloadExtensionEntry.ts
  electron/app/extensions/fileSystem.ts
  electron/app/extensions/loadExtension.ts
  electron/app/extensions/loadMultipleExtensions.ts
  electron/app/extensions/types.ts
  electron/app/index.ts
  electron/app/initKubeconfig.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/ipc/ipcMainRedux.ts
  electron/app/menu.ts
  electron/app/openApplication.ts
  electron/app/preload.ts
  electron/app/services/pluginService.ts
  electron/app/services/templateService.ts
  electron/app/setWindowTitle.ts
  electron/app/utils.ts
  electron/entitlements.mac.inherit.plist
  electron/main.ts
  package.json
Labels: size/XXL

#1535 fix: downgrade antd version
  package-lock.json
  package.json
Labels: size/XS

#1536 fix: electron reload path
  electron/app/createWindow.ts
Labels: size/XS

#1537 fix: relative paths in createWindow
  electron/app/createWindow.ts
Labels: size/XS
