Repository kubeshop/monokle, pull requests merged in 2022-04, with the labels that each got.

#1545 fix: updated electron and inlined fix-path dependency to avoid lockup
  electron/app/commands.ts
  electron/app/createWindow.ts
  electron/app/index.ts
  package.json
  src/utils/env.ts
  src/utils/path.ts
Labels: size/M

#1548 fix: removed enum for secret type
  resources/kindhandlers/handlers/bitnami.com/SealedSecret.json
Labels: size/S

#1540 feat: confirm cluster local modal
  src/components/molecules/ModalConfirm/ModalConfirm.tsx
  src/components/molecules/ModalConfirm/index.ts
  src/components/molecules/ModalConfirm/styled.ts
  src/components/molecules/index.ts
  src/components/organisms/AboutModal/AboutModal.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/constants/makeApplyText.ts
  src/utils/getDependencyVersion.ts
Labels: size/L

#1544 docs: Update Screenshots and Clear 'needs-docs' Issues
  docs/cluster-compare.md
  docs/cluster-integration.md
  docs/features.md
  docs/img/cluster-compare-selection-1.6.0.png
  docs/img/cluster-objects-1.6.0.gif
  docs/img/cluster-preview2-1.6.0.png
  docs/tutorials/how-to-browse-clusters.md
  docs/tutorials/img/editor-5-1.6.0.png
  mkdocs.yml
Labels: size/S

#1551 fix: absolute path for plugin/template icons
  electron/app/services/pluginService.ts
  electron/app/services/templateService.ts
Labels: size/S

#1525 feat: telemetry modal
  src/App.tsx
  src/components/molecules/NotificationMarkdown/NotificationMarkdown.tsx
  src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx
  src/components/molecules/NotificationMarkdown/styled.tsx
  src/components/organisms/MessageBox/MessageBox.tsx
  src/components/organisms/NotificationsManager/NotificationsManager.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/SettingsManager/types.ts
  src/models/alert.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/ui.ts
Labels: size/L

#1561 fix: remove existing charts on project switch
  src/redux/reducers/main.ts
Labels: size/XS

#1564 fix: values file schema remove defaults
  src/redux/services/schema.ts
Labels: size/XS

#1563 Wito/fix/filter warnings and errors
  src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
  src/redux/selectors.ts
  src/utils/filter.ts
Labels: size/M

#1565 fix: shortcuts for zoom in/out; fix view display shortcuts indicators…
  electron/app/menu.ts
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/constants/hotkeys.ts
  src/utils/defineHotkey.ts
Labels: size/M

#1566 refactor: telemetry info & links
  src/App.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/SettingsManager/styled.tsx
  src/constants/tooltips.ts
Labels: size/M

#1572 fix: set initial load parameter to disable resource update on first load
  src/components/molecules/FormEditor/FormWidgets/SecretKindResourceForm.tsx
Labels: size/M

#1571 Fix resource validation
  package-lock.json
  package.json
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/useEditorKeybindings.ts
  src/hooks/useResourceYamlSchema.ts
  src/redux/services/validation.ts
Labels: size/L

#1574 fix: telemetry notification showing only once
  src/App.tsx
Labels: size/XS

#1547 fix: allow to create multiple resources from template
  src/models/appstate.ts
  src/redux/reducers/main.ts
  src/redux/services/manifest-utils.ts
  src/redux/services/templates.ts
  src/redux/services/unsavedResource.ts
Labels: size/L

#1577 fix track events on main process and update Electron to 17.4.0
  package-lock.json
  package.json
  src/utils/telemetry.ts
Labels: size/S

#1578 fix: multi-resource delete
  src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
  src/redux/reducers/main.ts
  src/redux/thunks/removeResource.ts
  src/redux/thunks/removeResources.ts
Labels: size/L

#1582 fix: split view nav width dissapearing
  src/components/atoms/SplitView/SplitView.tsx
  src/components/atoms/SplitView/index.ts
  src/components/atoms/index.ts
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
Labels: size/XL

#1583 fix: initial state of ui pane configuration
  src/redux/initialState.ts
Labels: size/S

#1584 chore: add min width to split pane
  src/components/organisms/PaneManager/PaneManagerSplitView.styled.tsx
Labels: size/XS

#1586 chore(release): 1.6.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#1587 chore: redesign lef-menu
  src/components/atoms/MonoPaneTitle/MonoPaneTitle.tsx
  src/components/molecules/TitleBar/TitleBar.tsx
  src/components/molecules/TitleBar/styled.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/FileTreePane/styled.tsx
  src/components/organisms/HelmPane/HelmPane.tsx
  src/components/organisms/KustomizePane/KustomizePane.tsx
  src/components/organisms/PageHeader/styled.tsx
  src/components/organisms/PaneManager/MenuButton/MenuButton.tsx
  src/components/organisms/PaneManager/MenuButton/index.ts
  src/components/organisms/PaneManager/MenuButton/styled.ts
  src/components/organisms/PaneManager/PaneManagerLeftMenu.styled.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
  src/styles/Colors.ts
Labels: size/L

#1604 fix: fix switch project
  src/components/organisms/FileTreePane/FileTreePane.tsx
Labels: size/S

#1600 fix: updated to latest 18.x electron version and corresponding electron-builder
  package.json
Labels: size/XS

#1601 docs: Doc Updates for 1.6 Release
  docs/helm.md
  docs/img/add-new-plugin-1.6.0.png
  docs/img/add-plugin-modal-1.6.0.png
  docs/img/cluster-preview2-1.6.0.png
  docs/img/helm-preview-output-1.6.0.png
  docs/img/navigator-unknown-resource-options-1.6.0.png
  docs/img/open-plugin-manager-1.6.0.png
  docs/img/secret-resource-hover-1.6.0.png
  docs/img/secret-resource-hover-2-1.6.0.png
  docs/index.md
  docs/plugins.md
  docs/resource-editing.md
  docs/telemetry.md
  docs/tutorials/how-to-create-and-edit-configmap.md
  docs/tutorials/how-to-navigate-and-edit-manifests.md
Labels: size/M

#1591 fixing tests
  .github/workflows/monokle-ui-tests.yml
  src/components/organisms/ActionsPane/ActionsPane.tsx
  tests/base.test.ts
  tests/git.test.ts
  tests/models/navigatorPane.ts
  tests/project.test.ts
Labels: size/M

#1611 fix: building the helm command for preview configs
  src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.tsx
  src/redux/thunks/runPreviewConfiguration.ts
Labels: size/XS

#1612 fix: selection after deleting preview config
  src/redux/reducers/main.ts
  src/redux/thunks/previewConfiguration.ts
Labels: size/S

#1615 fix: cluster namespaces list if no kubeConfig set
  src/hooks/useTargetClusterNamespaces.ts
Labels: size/XS

#1616 fix: ignore unsatisfied refs setting
  src/redux/reducers/main.ts
Labels: size/XS

#1624 fix: added status to SealedSecret validation schema
  resources/kindhandlers/crds/bitnami/sealed-secret.yaml
  resources/kindhandlers/handlers/bitnami.com/SealedSecret.json
Labels: size/XS

#1608 Julia/feat/walkthrough
  src/App.tsx
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/WalkThrough/WalkThrough.tsx
  src/components/molecules/WalkThrough/index.ts
  src/components/molecules/WalkThrough/styled.ts
  src/components/molecules/WalkThrough/types.ts
  src/components/molecules/WalkThrough/walkThroughContent.ts
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/NavigatorPane/ClusterCompareButton.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/index.css
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
Labels: size/L

#1613 feat: add new user screen for getting started page
  src/App.tsx
  src/assets/CreateFromTemplate.svg
  src/assets/CreateScratch.svg
  src/assets/SelectFolder.svg
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/RecentProjectsPane/RecentProjectsPane.tsx
  src/components/organisms/RecentProjectsPane/index.ts
  src/components/organisms/RecentProjectsPane/styled.tsx
  src/components/organisms/StartProjectPane/Guide.styled.tsx
  src/components/organisms/StartProjectPane/Guide.tsx
  src/components/organisms/StartProjectPane/RecentProject.styled.tsx
  src/components/organisms/StartProjectPane/RecentProject.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.styled.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
  src/components/organisms/StartProjectPane/StartProjectPane.tsx
  src/components/organisms/StartProjectPane/index.ts
  src/components/organisms/StartProjectPane/styled.tsx
  src/models/appconfig.ts
  src/redux/reducers/appConfig.ts
  src/styles/Colors.ts
Labels: size/XL

#1617 Add policy resource scanning
  package-lock.json
  package.json
  resources/policies/bundle.tar.gz
  resources/policies/bundle/.manifest
  resources/policies/bundle/data.json
  resources/policies/bundle/input/lib/kubernetes.rego
  resources/policies/bundle/input/lib/utils.rego
  resources/policies/bundle/input/policies/advanced/capabilities_no_drop_at_least_one.rego
  resources/policies/bundle/input/policies/advanced/manages_etc_hosts.rego
  resources/policies/bundle/input/policies/advanced/protect_core_components_namespace.rego
  resources/policies/bundle/input/policies/advanced/protecting_pod_service_account_tokens.rego
  resources/policies/bundle/input/policies/advanced/selector_usage_in_network_policies.rego
  resources/policies/bundle/input/policies/advanced/use_limit_range.rego
  resources/policies/bundle/input/policies/advanced/use_resource_quota.rego
  resources/policies/bundle/input/policies/advanced/uses_untrusted_azure_registry.rego
  resources/policies/bundle/input/policies/advanced/uses_untrusted_ecr_registry.rego
  resources/policies/bundle/input/policies/advanced/uses_untrusted_gcr_registry.rego
  resources/policies/bundle/input/policies/advanced/uses_untrusted_public_registries.rego
  resources/policies/bundle/input/policies/general/CPU_not_limited.rego
  resources/policies/bundle/input/policies/general/CPU_requests_not_specified.rego
  resources/policies/bundle/input/policies/general/SYS_ADMIN_capability.rego
  resources/policies/bundle/input/policies/general/capabilities_no_drop_all.rego
  resources/policies/bundle/input/policies/general/file_system_not_read_only.rego
  resources/policies/bundle/input/policies/general/memory_not_limited.rego
  resources/policies/bundle/input/policies/general/memory_requests_not_specified.rego
  resources/policies/bundle/input/policies/general/mounts_docker_socket.rego
  resources/policies/bundle/input/policies/general/runs_with_GID_le_10000.rego
  resources/policies/bundle/input/policies/general/runs_with_UID_le_10000.rego
  resources/policies/bundle/input/policies/general/tiller_is_deployed.rego
  resources/policies/bundle/input/policies/general/uses_image_tag_latest.rego
  resources/policies/bundle/policy.wasm
  src/assets/ErrorIcon.svg
  src/assets/OpenPolicyAgentIcon.svg
  src/components/molecules/Monaco/codeIntel.ts
  src/components/molecules/Monaco/editorConstants.ts
  src/components/molecules/Monaco/editorHelpers.ts
  src/components/molecules/Monaco/useCodeIntel.ts
  src/components/molecules/ValidationErrorsPopover/ErrorsPopoverContent.tsx
  src/components/molecules/ValidationErrorsPopover/ValidationErrorsPopover.tsx
  src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
  src/feature-flags.json
  src/index.css
  src/models/appstate.ts
  src/models/k8sresource.ts
  src/models/policy.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSuffix.tsx
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/services/index.ts
  src/redux/services/resource.ts
  src/redux/services/validation.ts
  src/redux/store.ts
  src/redux/storeListeners.ts
  src/redux/thunks/loadPolicies.ts
  src/redux/thunks/setRootFolder.ts
  src/redux/thunks/updateFileEntry.ts
  src/redux/thunks/updateResource.ts
  src/utils/resources.ts
Labels: size/XXL

#1636 fix: project selection dropdown opening
  src/components/organisms/PageHeader/ProjectSelection.tsx
Labels: size/S

#1621 fix: ui updates colors and borders
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PaneManager/MenuButton/MenuButton.tsx
  src/components/organisms/PaneManager/MenuButton/styled.ts
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.styled.tsx
  src/components/organisms/PaneManager/PaneTooltip/PaneTooltip.tsx
  src/components/organisms/PaneManager/PaneTooltip/index.ts
  src/styles/Colors.ts
Labels: size/L

#1638 Add UI for validation configuration
  docs/hotkeys.md
  package-lock.json
  src/App.tsx
  src/assets/ValidationFigure.svg
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/OpenPolicyAgent.tsx
  src/components/atoms/Icon/Icons/SeverityHigh.tsx
  src/components/atoms/Icon/Icons/SeverityLow.tsx
  src/components/atoms/Icon/Icons/SeverityMedium.tsx
  src/components/atoms/Icon/Icons/Validation.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PaneManager/MenuButton/MenuButton.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.styled.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/ValidationOpenPolicyAgent.styled.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/ValidationOpenPolicyAgent.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/ValidationOpenPolicyAgentHeading.styled.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/ValidationOpenPolicyAgentHeading.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/ValidationOpenPolicyAgentTable.styled.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/ValidationOpenPolicyAgentTable.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/useOpenPolicyAgentTable.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationCard.styled.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationCard.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationCardUpnext.styled.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationCardUpnext.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationOverview.styled.tsx
  src/components/organisms/ValidationDrawer/Overview/ValidationOverview.tsx
  src/components/organisms/ValidationDrawer/ValidationDrawer.styled.tsx
  src/components/organisms/ValidationDrawer/ValidationDrawer.tsx
  src/components/organisms/ValidationDrawer/ValidationDrawerHeading.styled.tsx
  src/components/organisms/ValidationDrawer/ValidationDrawerHeading.tsx
  src/components/organisms/ValidationDrawer/index.ts
  src/components/organisms/ValidationDrawer/integrations.ts
  src/constants/constants.ts
  src/constants/hotkeys.ts
  src/feature-flags.json
  src/models/policy.ts
  src/models/thunk.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/reducers/ui.ts
  src/redux/services/validation.ts
  src/redux/thunks/loadPolicies.ts
  src/styles/Colors.ts
  src/utils/electronStore.ts
Labels: size/XXL

#1658 ui-tests: create project from welcome screen; from project dropdown
  src/components/molecules/WalkThrough/WalkThrough.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
  tests/models/mainWindow.ts
  tests/models/projectsDropdown.ts
Labels: size/S

#1640 fix: Error handling when renaming resource
  src/components/organisms/RenameResourceModal/RenameResourceModal.tsx
Labels: size/M

#1639 change the way we display the update modal to a notice
  src/App.tsx
  src/assets/NewUpdate.svg
  src/components/organisms/UpdateModal/UpdateModal.tsx
  src/components/organisms/UpdateModal/index.ts
  src/components/organisms/UpdateNotice/UpdateNotice.tsx
  src/components/organisms/UpdateNotice/index.ts
  src/components/organisms/UpdateNotice/styled.tsx
  src/components/organisms/index.ts
  tests/electronHelpers.ts
Labels: size/L

#1662 fix: add regex for resource names in file
  resources/schemas/1.23.3.json
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
Labels: size/XS

#1650 [Snyk] Upgrade @reduxjs/toolkit from 1.8.0 to 1.8.1
  package-lock.json
  package.json
Labels: size/XS

#1652 [Snyk] Upgrade react-redux from 7.2.6 to 7.2.7
  package-lock.json
  package.json
Labels: size/XS

#1654 fix: fix delete resource
  src/components/organisms/FileTreePane/TreeItem.tsx
Labels: size/XS

#1661 feat: add namespace helm option in preview config
  src/constants/helmOptions.ts
Labels: size/XS

#1651 [Snyk] Upgrade react-markdown from 8.0.1 to 8.0.2
  package-lock.json
  package.json
Labels: size/XS

#1663 feat: change Starting page icons
  src/assets/CreateFromTemplate.svg
  src/assets/CreateScratch.svg
  src/assets/FromFolder.svg
  src/assets/FromScratch.svg
  src/assets/FromTemplate.svg
  src/assets/SelectFolder.svg
  src/components/organisms/StartProjectPane/RecentProjectsPage.styled.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
Labels: size/L

#1648 feat: edit toggle in cluster mode
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/SettingsManager/Settings.tsx
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/utils/electronStore.ts
Labels: size/M

#1665 fix: handle deleteion of .monokle file
  src/redux/reducers/appConfig.ts
Labels: size/XS

#1664 fix: don't duplicate clusters when stopping minikube
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/redux/reducers/appConfig.ts
Labels: size/S

#1669 fix: Fix Editor buttons layout buttons
  src/components/molecules/TitleBar/TitleBar.tsx
Labels: size/XS

#1666 Helm Charts fixes and improvements
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
  tests/git.test.ts
Labels: size/L

#1667 Stan gabriel/feat/enable form editor
  src/components/molecules/FormEditor/FormEditor.tsx
Labels: size/XS

#1671 [Snyk] Upgrade react-redux from 7.2.7 to 7.2.8
  package-lock.json
  package.json
Labels: size/XS

#1676 Wito/fix/unsaved resources
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/redux/reducers/main.ts
  src/redux/thunks/saveUnsavedResources.ts
  src/utils/files.ts
Labels: size/M

#1674 chore: update electron
  package-lock.json
  package.json
Labels: size/XS

#1668 Wito/feat/rework panels
  package-lock.json
  package.json
  patches/react-reflex+4.0.6.patch
  src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/molecules/WalkThrough/types.ts
  src/components/molecules/WalkThrough/walkThroughContent.ts
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/NavigatorPane/ClusterCompareButton.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.styled.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/constants/constants.ts
  src/index.css
  src/index.tsx
  src/models/ui.ts
  src/navsections/sectionBlueprintMiddleware.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/utils/hooks.ts
Labels: size/XXL

#1678 fix: Navigator & Templates title buttons issue
  src/components/molecules/TitleBar/TitleBar.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
Labels: size/M

#1679 feat: add replay guide functionality
  src/components/organisms/PageHeader/HelpMenu.tsx
Labels: size/S

#1683 feat: disable telemetry on telemetry notification
  package-lock.json
  src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx
  src/redux/reducers/appConfig.ts
Labels: size/S

#1675 chore: update 1st walkthrough step text; make it appear only for new …
  src/App.tsx
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/WalkThrough/WalkThrough.tsx
  src/components/molecules/WalkThrough/styled.ts
  src/components/molecules/WalkThrough/walkThroughContent.ts
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/index.css
Labels: size/M

#1686 fix: console error when opening New Project from template modal
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
Labels: size/S

#1684 fix: fix kustomization error
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/Shortcuts.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/constants/constants.ts
  src/redux/thunks/previewKustomization.ts
  src/utils/command.ts
Labels: size/M
