Repository kubeshop/monokle, pull requests merged in 2022-09, with the labels that each got.

#2315 fix: updated to latest 19.x electron release
  package.json
Labels: size/XS

#2311 fix: allow "default" serviceAccountName references
  src/kindhandlers/Secret.handler.ts
  src/kindhandlers/common/outgoingRefMappers.ts
  src/redux/services/resourceRefs.ts
Labels: size/S

#2303 [Snyk] Upgrade antd from 4.22.2 to 4.22.4
  package-lock.json
  package.json
Labels: size/XS

#2316 feat: kustomize/helm icons for tree
  package-lock.json
  src/components/atoms/Icon/Icons/Helm.tsx
  src/components/atoms/Icon/Icons/Kustomize.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/ItemPrefix.tsx
Labels: size/L

#2308 feat(terminal): added ZSH shell for Linux based OS
  src/constants/terminal.ts
  src/redux/services/terminalShells.ts
Labels: size/S

#2307 feat: highlight last changed line
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/Monaco/CodeIntel/k8sResource/applyLineDecorationIntel.ts
  src/components/molecules/Monaco/CodeIntel/k8sResource/index.ts
  src/components/molecules/Monaco/CodeIntel/types.ts
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/editorConstants.ts
  src/components/molecules/Monaco/useCodeIntel.ts
  src/components/organisms/SearchPane/CreateFilteredNode.tsx
  src/components/organisms/SearchPane/styled.tsx
  src/index.css
  src/models/appstate.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/services/manifest-utils.ts
  src/redux/thunks/updateResource.ts
Labels: size/M

#2317 feat: change default shell option label
  src/components/organisms/TerminalPane/TerminalOptions.tsx
Labels: size/XS

#2320 fix: added try/catch for all schema parsing
  src/redux/services/schema.ts
Labels: size/S

#2321 [Snyk] Upgrade electron-updater from 5.2.1 to 5.2.2
  package-lock.json
  package.json
Labels: size/XS

#2322 feat: git changed files
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  package-lock.json
  src/assets/GitSelectItem.svg
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/Git.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/organisms/GitOpsView/GitView.styled.tsx
  src/components/organisms/GitOpsView/GitView.tsx
  src/components/organisms/GitOpsView/index.ts
  src/components/organisms/GitPane/GitPane.styled.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/components/organisms/GitPane/index.ts
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/feature-flags.json
  src/models/git.ts
  src/models/icons.ts
  src/models/ui.ts
  src/redux/git/git.initialState.ts
  src/redux/git/git.slice.ts
  src/redux/reducers/main.ts
  src/redux/services/fileEntry.ts
  src/redux/thunks/multiplePathsChanged.ts
  src/redux/thunks/setRootFolder.ts
  src/redux/thunks/updateFileEntry.ts
  src/redux/thunks/updateResource.ts
  src/utils/features.tsx
  src/utils/git.ts
Labels: size/XL

#2302 fix: use Monaco logic to set syntax-highlighting for non-yaml files
  src/components/molecules/Monaco/Monaco.tsx
Labels: size/S

#2326 feat: checkout remote branches
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  package-lock.json
  src/components/molecules/BranchSelect/BranchCell.styled.tsx
  src/components/molecules/BranchSelect/BranchCell.tsx
  src/components/molecules/BranchSelect/BranchSelect.tsx
  src/components/molecules/BranchSelect/BranchTable.styled.tsx
  src/components/molecules/BranchSelect/BranchTable.tsx
  src/components/molecules/BranchSelect/useBranchTable.tsx
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/models/git.ts
  src/redux/thunks/multiplePathsChanged.ts
Labels: size/L

#2334 fix: extend kind section when clicking on warnings/errors count
  package-lock.json
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameCounter.tsx
Labels: size/S

#2335 fix: getting resource content spec container name for opening terminal into pod
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
Labels: size/XS

#2338 [Snyk] Upgrade type-fest from 2.18.1 to 2.19.0
  package-lock.json
  package.json
Labels: size/XS

#2337 [Snyk] Upgrade antd from 4.22.5 to 4.22.7
  package-lock.json
  package.json
Labels: size/XS

#2346 fix: disable add resource action for kustomization files
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenu.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenuWrapper.tsx
Labels: size/L

#2345 fix: update images list when chaning resource filter
  src/redux/reducers/main.ts
Labels: size/S

#2347 [Snyk] Security upgrade git-url-parse from 12.0.0 to 13.0.0
  package-lock.json
  package.json
Labels: size/XS

#2327 feat: git init
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/Git.tsx
  src/components/atoms/Icon/Icons/GitOps.tsx
  src/components/atoms/Icon/Icons/GitProject.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/constants/tooltips.tsx
  src/models/appconfig.ts
  src/models/icons.ts
  src/redux/git/git.slice.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/main.ts
  src/redux/thunks/multiplePathsChanged.ts
Labels: size/L

#2344 feat: monitor git folder
  src/redux/reducers/appConfig.ts
  src/redux/reducers/main.ts
  src/redux/services/gitFolderMonitor.ts
  src/redux/thunks/multiplePathsChanged.ts
Labels: size/L

#2353 feat: delete local branch
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/molecules/BranchSelect/BranchCell.styled.tsx
  src/components/molecules/BranchSelect/BranchCell.tsx
  src/components/molecules/BranchSelect/BranchTable.styled.tsx
  src/components/molecules/BranchSelect/BranchTable.tsx
  src/components/molecules/BranchSelect/useBranchTable.tsx
Labels: size/L

#2356 fix: git changelist for nested folder projects
  electron/app/git/git.ts
  src/utils/git.ts
Labels: size/S

#2329 feat: Julia/feat/code form editor
  resources/form-schemas/clusterrole-ui-schema.json
  resources/form-schemas/clusterrolebinding-ui-schema.json
  resources/form-schemas/configmap-ui-schema.json
  resources/form-schemas/deployment-ui-schema.json
  resources/form-schemas/helm-chart-ui-schema.json
  resources/form-schemas/metadata-ui-schema.json
  resources/form-schemas/networkpolicy-ui-schema.json
  resources/form-schemas/role-ui-schema.json
  resources/form-schemas/rolebinding-ui-schema.json
  resources/form-schemas/secret-ui-schema.json
  resources/form-schemas/service-ui-schema.json
  src/App.tsx
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/SplitView.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/molecules/FormEditor/FormEditor.styled.tsx
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/FormEditor/FormWidgets/SecretKindResourceForm.styled.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/FormEditorModal/FormEditorModal.styled.tsx
  src/components/organisms/FormEditorModal/FormEditorModal.tsx
  src/components/organisms/FormEditorModal/index.ts
  src/constants/tooltips.tsx
  src/index.css
  src/models/icons.ts
  src/models/rootstate.ts
  src/redux/forms/index.ts
  src/redux/forms/slice.ts
  src/redux/forms/state.ts
  src/redux/store.ts
Labels: size/XL

#2361 fix: don't show 0 when there are no recent searches
  src/components/organisms/SearchPane/SearchPane.tsx
Labels: size/XS

#2359 feat: git show added/removed files
  electron/app/git/git.ts
  src/components/organisms/GitPane/GitPane.styled.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/redux/services/fileEntry.ts
  src/utils/git.ts
Labels: size/M

#2349 feat: stage and commit
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/organisms/GitPane/CommitInput.styled.tsx
  src/components/organisms/GitPane/CommitInput.tsx
  src/components/organisms/GitPane/FileList.styled.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/GitPane/GitPane.styled.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/constants/tooltips.tsx
  src/redux/services/gitFolderMonitor.ts
  src/styles/Colors.ts
Labels: size/XL

#2363 refactor: commit button label + fix antd
  package-lock.json
  src/components/organisms/ActionsPane/Scale/Scale.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/components/organisms/SettingsManager/Settings.tsx
Labels: size/S

#2365 feat: monitor added/removed files
  src/redux/reducers/main.ts
  src/redux/services/gitFolderMonitor.ts
  src/redux/thunks/multiplePathsAdded.ts
  src/redux/thunks/multiplePathsChanged.ts
Labels: size/M

#2367 feat: create branch functionality + design
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/molecules/BranchSelect/BranchTable.styled.tsx
  src/components/molecules/BranchSelect/BranchTable.tsx
  src/components/molecules/BranchSelect/CreateBranchInput.styled.tsx
  src/components/molecules/BranchSelect/CreateBranchInput.tsx
Labels: size/L

#2375 feat: push commits + publish branch
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/organisms/GitPane/BottomActions.styled.tsx
  src/components/organisms/GitPane/BottomActions.tsx
  src/components/organisms/GitPane/CommitInput.styled.tsx
  src/components/organisms/GitPane/CommitInput.tsx
  src/components/organisms/GitPane/CommitModal.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/GitPane/GitPane.styled.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/components/organisms/GitPane/RemoteInput.styled.tsx
  src/components/organisms/GitPane/RemoteInput.tsx
  src/models/git.ts
  src/redux/git/git.slice.ts
  src/redux/reducers/main.ts
  src/redux/services/gitFolderMonitor.ts
Labels: size/XL

#2379 fix: improve isGitFolder function
  electron/app/git/git.ts
Labels: size/XS

#2377 fix: create script for wait-on command
  package-lock.json
  package.json
  scripts/wait.js
Labels: size/S

#2382 feat: git changed files paths and colors
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/organisms/GitPane/FileList.styled.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/models/git.ts
  src/redux/services/gitFolderMonitor.ts
  src/redux/thunks/setRootFolder.ts
  src/styles/Colors.ts
  src/utils/git.ts
Labels: size/L

#2384 fix: schema definitions crash
  src/redux/services/schema.ts
Labels: size/XS

#2385 fix: add sanity checks in KustomizationContextMenu
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenuWrapper.tsx
Labels: size/M

#2392 feat: git improvements + fixes
  src/components/molecules/BranchSelect/BranchCell.tsx
  src/components/organisms/GitOpsView/GitView.styled.tsx
  src/components/organisms/GitOpsView/GitView.tsx
  src/components/organisms/GitPane/BottomActions.styled.tsx
  src/components/organisms/GitPane/BottomActions.tsx
  src/components/organisms/GitPane/CommitModal.tsx
  src/components/organisms/GitPane/FileList.styled.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/GitPane/GitPane.styled.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.styled.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
Labels: size/L

#2380 fix: update form on data change
  src/components/molecules/FormEditor/FormEditor.tsx
Labels: size/S

#2394 fix: create local branch
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/GitPane/GitPane.styled.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.styled.tsx
Labels: size/M

#2397 feat: warn user when checkout is not possible
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/molecules/BranchSelect/BranchSelect.tsx
Labels: size/S

#2398 feat: hide bottom actions if git repo is not found
  src/components/organisms/GitPane/GitPane.tsx
Labels: size/XS

#2403 fix: remove changed files if there is not git repo
  electron/app/git/git.ts
  package-lock.json
  src/redux/services/gitFolderMonitor.ts
Labels: size/M

#2404 fix: changed files paths properties
  electron/app/git/git.ts
  src/components/organisms/GitPane/FileList.tsx
  src/models/git.ts
  src/redux/git/git.slice.ts
  src/redux/reducers/main.ts
  src/utils/git.ts
Labels: size/M

#2405 fix: displayPath
  src/utils/git.ts
Labels: size/XS

#2414 refactor: show scale/restart only in cluster mode
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
Labels: size/S

#2396 Julia/fix/forms-rerender
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/FormEditor/FormObjectFieldTemplate.tsx
  src/components/organisms/FormEditorModal/FormEditorModal.tsx
Labels: size/M

#2350 test: telemetry/walk through
  src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx
  src/components/organisms/PageHeader/HelpMenu.tsx
  tests/base.test.ts
  tests/git.test.ts
Labels: size/M

#2422 fix: file map update
  electron/app/git/git.ts
  src/components/molecules/SectionRenderer/SectionRenderer.tsx
  src/models/navigator.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/redux/reducers/main.ts
  src/redux/services/fileEntry.ts
  src/redux/services/fileMonitor.ts
  src/redux/thunks/multiplePathsAdded.ts
  src/redux/thunks/multiplePathsChanged.ts
  src/redux/thunks/updateFileEntry.ts
  src/redux/thunks/updateResource.ts
  src/utils/git.ts
  tests/git.test.ts
Labels: size/L

#2424 feat: on git checkout error show terminal cmd
  src/components/molecules/BranchSelect/BranchSelect.tsx
  src/constants/constants.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
Labels: size/M

#2431 docs: initial page for CRDs
  docs/resource-crds.md
  mkdocs.yml
Labels: size/S

#2430 fix: show original content of git changed file
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/models/git.ts
  src/utils/git.ts
Labels: size/M

#2433 chore: release notes for 1.11
  resources/releaseNotes/1.11/1.11.json
  resources/releaseNotes/1.11/1.11.md
  resources/releaseNotes/1.11/1.11.svg
Labels: size/L

#2434 fix: disable git diff editor validation
  src/components/organisms/GitOpsView/GitView.tsx
Labels: size/XS

#2427 feat: configure CRDs Schema validation
  electron/app/createWindow.ts
  electron/app/extensions/downloadExtension.ts
  electron/app/extensions/downloadExtensionEntry.ts
  electron/app/extensions/loadExtension.ts
  electron/app/services/pluginService.ts
  electron/app/services/templateService.ts
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/CRDs.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDsSchemaValidation.styled.tsx
  src/components/organisms/ValidationPane/CRDsSchemaValidation/CRDsSchemaValidation.tsx
  src/components/organisms/ValidationPane/CRDsSchemaValidation/index.ts
  src/components/organisms/ValidationPane/OpenPolicyAgent/ValidationOpenPolicyAgent.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationCard.tsx
  src/components/organisms/ValidationPane/ValidationOverview/ValidationOverview.tsx
  src/components/organisms/ValidationPane/ValidationPane.tsx
  src/components/organisms/ValidationPane/ValidationPaneHeading/ValidationPaneHeading.styled.tsx
  src/components/organisms/ValidationPane/ValidationPaneHeading/ValidationPaneHeading.tsx
  src/components/organisms/ValidationPane/ValidationPaneHeading/index.ts
  src/kindhandlers/index.ts
  src/models/appconfig.ts
  src/models/icons.ts
  src/models/integrations.ts
  src/models/ui.ts
  src/redux/reducers/appConfig.ts
  src/redux/services/resource.ts
  src/redux/store.ts
  src/utils/crds.ts
  src/utils/fileSystem.ts
  src/utils/urls.ts
Labels: size/L

#2435 chore: add learn more url for CRDs
  src/models/integrations.ts
Labels: size/XS

#2438 fix: reset filters when switching projects
  src/redux/reducers/main.ts
Labels: size/XS

#2436 chore: update electron version to 19.1.1
  package-lock.json
  package.json
Labels: size/XS

#2455 fix: show removed file in git pane
  src/redux/services/fileMonitor.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/M

#2456 fix: make git diff editor read-only
  src/components/organisms/GitOpsView/GitView.tsx
Labels: size/XS

#2457 fix: show git pane header anytime
  src/components/organisms/GitPane/GitPane.styled.tsx
  src/components/organisms/GitPane/GitPane.tsx
Labels: size/S

#2458 Fixed placement of Git button, added button to start project from git repo on project selection dropdown
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/GitRepository.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/organisms/PageHeader/CreateProject.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/constants/tooltips.tsx
  src/models/icons.ts
Labels: size/M

#2463 feat: success modals after commit/push
  src/components/organisms/GitPane/BottomActions.tsx
  src/components/organisms/GitPane/CommitModal.tsx
  src/components/organisms/GitPane/GitPane.styled.tsx
  src/components/organisms/GitPane/GitPane.tsx
Labels: size/S

#2462 feat: disable/enable commit/push actions
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/organisms/GitPane/BottomActions.styled.tsx
  src/components/organisms/GitPane/BottomActions.tsx
  src/constants/tooltips.tsx
  src/models/git.ts
  src/redux/git/git.slice.ts
  src/redux/services/gitFolderMonitor.ts
Labels: size/L

#2464 feat: disable publish & push
  electron/app/git/git.ts
  src/components/organisms/GitPane/BottomActions.tsx
  src/components/organisms/GitPane/GitPane.tsx
Labels: size/S

#2465 feat: git sync cta
  electron/app/git/git.ts
  electron/app/git/ipc.ts
  src/components/molecules/BranchSelect/BranchSelect.tsx
  src/components/molecules/BranchSelect/CreateBranchInput.tsx
  src/components/organisms/GitPane/BottomActions.styled.tsx
  src/components/organisms/GitPane/BottomActions.tsx
  src/components/organisms/GitPane/FileList.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/constants/constants.ts
  src/constants/tooltips.tsx
  src/models/git.ts
  src/redux/git/git.slice.ts
  src/redux/services/fileMonitor.ts
  src/redux/services/gitFolderMonitor.ts
  src/redux/thunks/setRootFolder.ts
  src/utils/git.ts
  src/utils/terminal.ts
Labels: size/XL

#2469 fix: add error boundary for form
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/organisms/ErrorPage/ErrorPage.styled.tsx
Labels: size/M

#2470 fix: save crds based on group & name
  src/kindhandlers/index.ts
  src/utils/crds.ts
Labels: size/S

#2471 fix: conditional button back error boundary
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/organisms/ErrorPage/ErrorPage.tsx
Labels: size/S
