Repository kubeshop/monokle, pull requests merged in 2022-02, with the labels that each got.

#1247 fix: drawer vertical scrollbar styling
  src/components/organisms/LazyDrawer/LazyDrawer.tsx
  src/components/organisms/LazyDrawer/styled.tsx
Labels: size/S

#1248 fix: helm chart templates form data
  src/components/organisms/TemplateModal/TemplateModal.tsx
Labels: size/XS

#1258 fix: deploy resource to other namespace
  src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
  src/redux/services/applyMultipleResources.ts
  src/redux/thunks/applyResource.ts
Labels: size/S

#1266 fix: correct namespace validation for rolebinding subject refs
  src/kindhandlers/ClusterRoleBinding.handler.ts
  src/kindhandlers/RoleBinding.handler.ts
Labels: size/S

#1259 fix: create namespace only if deploy is successful
  src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
  src/redux/services/applyMultipleResources.ts
  src/redux/thunks/applyCheckedResources.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/applySelectedResourceMatches.ts
  src/redux/thunks/applyYaml.ts
  src/redux/thunks/utils.ts
Labels: size/L

#1270 fix: wrap folder name with quotes
  electron/commands.ts
  src/redux/services/previewReferencedHelmChart.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/previewHelmValuesFile.ts
Labels: size/S

#1277 chore: update codeowners
  .github/CODEOWNERS
Labels: size/XS

#1276 fix: disable validation for go templates
  src/hooks/useResourceYamlSchema.ts
  src/redux/services/helm.ts
Labels: size/XS

#1278 refactor: actions pane footer
  src/components/atoms/SplitView/SplitView.tsx
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ActionsPane/ActionsPaneFooter.styled.tsx
  src/components/organisms/ActionsPane/ActionsPaneFooter.tsx
  src/constants/constants.ts
  src/models/ui.ts
  src/redux/reducers/ui.ts
  src/styles/Colors.ts
Labels: size/L

#1291 fix Helm chart folder recognition
  src/components/molecules/SectionRenderer/SectionRenderer.tsx
  src/components/molecules/SectionRenderer/styled.tsx
  src/models/navigator.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/sectionBlueprintMiddleware.ts
  src/redux/services/helm.ts
Labels: size/M

#1300 chore: add intro video to readme
  README.md
  docs/img/monokle-intro-thumbnail.png
Labels: size/XS

#1297 fix: helm charts/values removal
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
Labels: size/M

#1288 feat: Add Zoom In and Zoom Out functionality and hotkeys
  docs/hotkeys.md
  electron/menu.ts
  src/constants/hotkeys.ts
  src/redux/reducers/ui.ts
Labels: size/M

#1298 Misc Edits to 1.5.0 Doc
  docs/cluster-integration.md
  docs/features.md
  docs/img/cluster-preview2-1.5.0.png
  docs/img/cluster-selector-1.5.0.png
  docs/img/clusters-tab-1.5.0.png
  docs/img/deploy-and-diff-buttons-1.5.0.png
  docs/img/explorer-file-actions-1.5.0.png
  docs/img/helm-navigation-1.5.0.png
  docs/img/monokle-settings-1.5.0.gif
  docs/img/resource-navigation-1-1.5.0.png
  docs/img/source-editor-auto-complete-1.5.0.png
  docs/overview.md
  docs/resource-editing.md
Labels: size/M

#1303 chore: README updates
  README.md
Labels: size/M

#1306 fix: ensured passing of main process env to kubeclient exec authenticator
  electron/main.ts
  package.json
  src/App.tsx
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/redux/reducers/main.ts
  src/redux/services/getClusterObjects.ts
  src/redux/services/resource.ts
  src/redux/thunks/loadClusterDiff.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/utils.ts
  src/utils/env.ts
  src/utils/kubeclient.ts
Labels: size/L

#1283 feat: add Preview action for file explorer
  package-lock.json
  src/components/molecules/QuickActionPreview/QuickActionPreview.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/Styled.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/FileTreePane/types.tsx
Labels: size/XL

#1310 add testing.md to mk docs
  mkdocs.yml
Labels: size/XS

#1307 fix: rewrote template interpolation to use sandboxed VM
  docs/templates.md
  electron/commands.ts
  electron/main.ts
  package.json
  src/redux/services/previewReferencedHelmChart.ts
  src/redux/services/templates.ts
Labels: size/M

#1334 chore: fix thumbnail size in README
  README.md
  docs/img/monokle-intro-thumbnail.png
Labels: size/XS

#1335 fix: enable select a template button on back
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
Labels: size/L

#1325 fix: added more properties to ignore during validation
  src/constants/clusterResource.ts
  src/redux/services/__test__/manifests/invalid-deployment/invalid-deployment.yaml
  src/redux/services/validation.ts
Labels: size/M

#1333 fix: adding/removing Chart.yaml and values files
  src/components/molecules/SectionRenderer/styled.tsx
  src/constants/constants.ts
  src/redux/services/fileEntry.test.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
Labels: size/L

#1336 fix: reprocess kustomizations on addPath
  src/redux/services/fileEntry.ts
  src/redux/services/resource.ts
Labels: size/XS

#1340 chore(release): 1.5.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#1338 refactor: create subsections for helm charts
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/SectionRenderer/SectionRenderer.tsx
  src/components/molecules/SectionRenderer/styled.tsx
  src/components/organisms/HelmPane/HelmPane.tsx
  src/constants/constants.ts
  src/models/navigator.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/index.ts
  src/navsections/sectionBlueprintMiddleware.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
Labels: size/L

#1317 refactor: Closes #1272 Upgrade electron to 17.0.x and Upgrade node to 16.13.2
  .npmrc
  .nvmrc
  package-lock.json
  package.json
  src/utils/promises.ts
Labels: enhancement, size/S

#1343 re-parsing of invalid resources improvements
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
  src/constants/constants.ts
  src/redux/services/kustomize.ts
  src/redux/services/resource.ts
Labels: size/M

#1345 fix: added link to keyboard shortcuts in help menus and documentation…
  docs/hotkeys.md
  electron/menu.ts
  mkdocs.yml
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/utils/shell.ts
Labels: size/M

#1347 feat: added markdown rendering of notifications for readmore link to …
  electron/main.ts
  package.json
  src/components/molecules/NotificationMarkdown/NotificationMarkdown.tsx
  src/components/molecules/NotificationMarkdown/index.ts
  src/components/organisms/MessageBox/MessageBox.tsx
  src/components/organisms/NotificationsManager/NotificationsManager.tsx
  src/constants/constants.ts
  src/utils/shell.ts
Labels: size/M

#1341 Andreiv1992/feat/work with git folder
  .github/workflows/monokle-ui-tests.yml
  docs/testing.md
  playwright.config.ts
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/UpdateModal/UpdateModal.tsx
  src/navsections/KustomizePatchSectionBlueprint/KustomizePatchSectionBlueprint.ts
  tests/base.test.ts
  tests/electronHelpers.ts
  tests/git.test.ts
  tests/models/helmPane.ts
  tests/models/kustomizePane.ts
  tests/models/mainWindow.ts
  tests/models/navigatorPane.ts
  tests/models/projectsDropdown.ts
  tests/models/startProjectPane.ts
  tests/models/util.ts
  tests/project.test.ts
Labels: size/L

#1348 show Chart.yaml, improve helm pane styling and section blueprint functionality
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/SectionRenderer/SectionRenderer.tsx
  src/components/molecules/SectionRenderer/styled.tsx
  src/components/organisms/PaneManager/MenuButton.tsx
  src/models/navigator.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
Labels: size/L

#1354 Helm and Kustomize panes fixes
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionEmptyDisplay.tsx
  src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionEmptyDisplay.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationSectionBlueprint.ts
  src/navsections/KustomizationSectionBlueprint/KustomizationSectionEmptyDisplay.tsx
Labels: size/M

#1352 Olelensmar/feat/helm chart form editors
  resources/form-schemas/helm-chart-schema.json
  resources/form-schemas/helm-chart-ui-schema.json
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/hooks/useResourceYamlSchema.ts
  src/redux/services/fileEntry.ts
  src/redux/services/schema.ts
  src/utils/files.ts
Labels: size/L

#1356 fix: updated to electron 17.0.1
  package.json
Labels: size/XS

#1364 fix: use projectConfig instead of appConfig when parsing folder
  src/redux/reducers/main.ts
  src/redux/services/fileEntry.ts
  src/redux/services/fileMonitor.ts
  src/redux/services/helm.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/M

#1365 fix: enabled form editors for selected file and deploy for kustomizations
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/XS

#1370 fix: update helm chart name on file change
  src/components/molecules/SectionRenderer/SectionRenderer.tsx
  src/models/navigator.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/sectionBlueprintMiddleware.ts
  src/redux/reducers/main.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
Labels: size/L

#1373 fix: added namespaces from currently selected cluster to list of selectable namespaces
  src/components/molecules/FormEditor/FormWidgets/NamespaceSelection.tsx
  src/redux/services/resource.ts
Labels: size/M

#1375 fix: disable namespace selection elements if a namespace is being dep…
  src/components/molecules/FormEditor/FormWidgets/ResourceSelection.tsx
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
Labels: size/S

#1378 refactor: helm charts sections styling
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/SectionRenderer/styled.tsx
  src/components/molecules/SectionRenderer/useSectionCustomization.ts
  src/models/navigator.ts
  src/navsections/HelmChartSectionBlueprint/CollapseSectionPrefix.tsx
  src/navsections/HelmChartSectionBlueprint/FileItemPrefix.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
Labels: size/L

#1383 Monokle Documentation Update 17/02/2022
  docs/apply-and-diff.md
  docs/architecture.md
  docs/cluster-compare.md
  docs/cluster-integration.md
  docs/creating-resources.md
  docs/development.md
  docs/faq.md
  docs/features.md
  docs/file-explorer.md
  docs/getting-started.md
  docs/helm.md
  docs/hotkeys.md
  docs/img/cluster-objects-1.5.0.gif
  docs/img/diff-7-1.5.0.png
  docs/img/diff-button-1.5.0.png
  docs/img/diff-tble-8-1.5.0.png
  docs/img/expand.gif
  docs/img/find-file-and-dead-links-1.5.0.gif
  docs/img/kustomization-1.5.0.gif
  docs/img/name-project-1.5.0.png
  docs/img/navigator-1.5.0.gif
  docs/img/quick-filter-popup-1.5.0.png
  docs/img/start-with-template-1.5.0.png
  docs/img/template-selection-1.5.0.png
  docs/img/upstream-downstream-1.5.0.gif
  docs/img/welcome-1.5.0.png
  docs/index.md
  docs/kustomize.md
  docs/overview.md
  docs/plugins.md
  docs/resource-editing.md
  docs/resource-navigation.md
  docs/resource-validation.md
  docs/templates.md
  docs/testing.md
  docs/tutorials/how-to-browse-clusters.md
  docs/tutorials/how-to-configure-monokle.md
  docs/tutorials/how-to-create-and-edit-configmap.md
  docs/tutorials/how-to-navigate-and-edit-manifests.md
  docs/tutorials/img/add-resource-1.5.0.png
  docs/tutorials/img/browse-3-1.5.0.png
  docs/tutorials/img/image-16-1.5.0.png
  docs/tutorials/img/kubeconfig-2-1.5.0.png
  docs/tutorials/img/resource-diff-1.4.0.png
  docs/tutorials/img/start-with-template-1.5.0.png
  mkdocs.yml
Labels: size/L

#1386 Fix mkdocs.yml error
  docs/overview.md
  docs/testing.md
  mkdocs.yml
Labels: size/S

#1381 PvConf#3 - feat: UI for preview configuration editor
  src/App.tsx
  src/components/atoms/KeyValueInput/KeyValueEntryRenderer.tsx
  src/components/atoms/KeyValueInput/KeyValueInput.tsx
  src/components/atoms/KeyValueInput/ValueInput.tsx
  src/components/atoms/KeyValueInput/constants.ts
  src/components/atoms/KeyValueInput/styled.tsx
  src/components/atoms/KeyValueInput/types.ts
  src/components/atoms/OrderedList/OrderedList.tsx
  src/components/atoms/OrderedList/index.ts
  src/components/atoms/OrderedList/styled.tsx
  src/components/atoms/index.ts
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
  src/components/organisms/PreviewConfigurationEditor/styled.tsx
  src/constants/constants.ts
  src/constants/helmOptions.ts
  src/constants/tooltips.ts
  src/models/appstate.ts
  src/models/ui.ts
  src/navsections/HelmChartSectionBlueprint/PreviewConfigurationQuickAction.tsx
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/reducers/ui.ts
  src/utils/array.ts
Labels: size/XL

#1380 PvConf#2 - feat: preview configuration drawer
  src/App.tsx
  src/components/atoms/KeyValueInput/KeyValueEntryRenderer.tsx
  src/components/atoms/KeyValueInput/KeyValueInput.tsx
  src/components/atoms/KeyValueInput/ValueInput.tsx
  src/components/atoms/KeyValueInput/constants.ts
  src/components/atoms/KeyValueInput/styled.tsx
  src/components/atoms/KeyValueInput/types.ts
  src/components/atoms/OrderedList/OrderedList.tsx
  src/components/atoms/OrderedList/index.ts
  src/components/atoms/OrderedList/styled.tsx
  src/components/atoms/index.ts
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
  src/components/organisms/PreviewConfigurationEditor/index.ts
  src/components/organisms/PreviewConfigurationEditor/styled.tsx
  src/constants/constants.ts
  src/constants/helmOptions.ts
  src/constants/tooltips.ts
  src/models/appstate.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/PreviewConfigurationQuickAction.tsx
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/utils/array.ts
Labels: size/XL

#1379 PvConf#1 - feat: add preview configurations sections
  src/App.tsx
  src/components/atoms/KeyValueInput/KeyValueEntryRenderer.tsx
  src/components/atoms/KeyValueInput/KeyValueInput.tsx
  src/components/atoms/KeyValueInput/ValueInput.tsx
  src/components/atoms/KeyValueInput/constants.ts
  src/components/atoms/KeyValueInput/styled.tsx
  src/components/atoms/KeyValueInput/types.ts
  src/components/atoms/OrderedList/OrderedList.tsx
  src/components/atoms/OrderedList/index.ts
  src/components/atoms/OrderedList/styled.tsx
  src/components/atoms/index.ts
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/SectionRenderer/SectionRenderer.tsx
  src/components/molecules/SectionRenderer/styled.tsx
  src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
  src/components/organisms/PreviewConfigurationEditor/index.ts
  src/components/organisms/PreviewConfigurationEditor/styled.tsx
  src/constants/constants.ts
  src/constants/helmOptions.ts
  src/constants/tooltips.ts
  src/models/appstate.ts
  src/models/navigator.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/PreviewConfigurationQuickAction.tsx
  src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
  src/navsections/sectionBlueprintMap.ts
  src/navsections/sectionBlueprintMiddleware.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/utils/array.ts
Labels: size/XL

#1388 Olelensmar/feat/values files in subfolders
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/constants/constants.ts
  src/constants/tooltips.ts
  src/hooks/useResourceYamlSchema.ts
  src/kindhandlers/index.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/HelmChartSectionBlueprint/RootHelmChartsSectionBlueprint.ts
  src/navsections/sectionBlueprintMap.ts
  src/redux/reducers/main.ts
  src/redux/reducers/navigator.ts
  src/redux/services/fileEntry.test.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
  src/redux/services/manifest-utils.ts
  src/redux/services/resource.ts
  src/redux/services/unsavedResource.ts
  src/redux/services/validation.ts
  src/redux/storeListeners.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/setRootFolder.ts
  src/utils/yaml.ts
Labels: size/XL

#1318 Support multiple k8s versions
  electron/main.ts
  electron/utils.ts
  package-lock.json
  package.json
  resources/schemas/1.23.3.json
  resources/schemas/objectmetadata.json
  src/App.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/PaneManager/PaneMangerSplitView.tsx
  src/components/organisms/SettingsManager/Settings.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/SettingsManager/styled.tsx
  src/constants/constants.ts
  src/hooks/useResourceYamlSchema.ts
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/main.ts
  src/redux/services/fileEntry.ts
  src/redux/services/k8sVersionService.ts
  src/redux/services/projectConfig.ts
  src/redux/services/resource.ts
  src/redux/services/schema.ts
  src/redux/services/validation.test.ts
  src/redux/services/validation.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/setRootFolder.ts
  src/redux/thunks/utils.ts
  src/utils/electronStore.ts
Labels: size/XXL

#1396 chore: change "apply" to "deploy" in tooltips
  src/constants/tooltips.ts
Labels: size/XS

#1395 fix: template schema parsing error feedback
  src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
Labels: size/XS

#1304 feat: add confirm dialog on window close with unsaved files
  electron/main.ts
  electron/utils.ts
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/redux/selectors.ts
Labels: size/M

#1403 Change "ConfigMap Properties Form" to generic "Kubernetes Resources Properties Form"
  docs/form-editor.md
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/S

#1400 Monokle Documentation Updates 1.5.0
  docs/apply-and-diff.md
  docs/cluster-integration.md
  docs/creating-resources.md
  docs/features.md
  docs/file-explorer.md
  docs/form-editor.md
  docs/getting-started.md
  docs/helm.md
  docs/img/deploy-to-cluster-1.5.0.png
  docs/img/error-details-popup-1.5.0.png
  docs/img/helm-settings-1.5.0.png
  docs/img/invoke-kustomize-setting-1.5.0.png
  docs/img/kubeconfig-setting-1.5.0.png
  docs/img/kustomize-settings-1.5.0.png
  docs/img/link-syntax-errors-image-1-1.5.0.png
  docs/img/metadata-button-image-1.5.0.png
  docs/img/namespace-selector-1.5.0.png
  docs/img/navigator-broken-links-list-1.5.0.png
  docs/img/navigator-link-and-syntax-errors-header-1.5.0.png
  docs/img/navigator-link-syntax-errors-1.5.0.png
  docs/img/navigator-resource-check-box-1.5.0.png
  docs/img/navigator-resource-cluster-actions-1.5.0.png
  docs/img/navigator-resource-options-1.5.0.png
  docs/img/navigator-select-cluster-resources-1.5.0.png
  docs/img/navigator-syntax-errors-list-1.5.0.png
  docs/img/resource-navigation-1-1.5.0.png
  docs/img/source-editor-pane-1.5.0.png
  docs/kustomize.md
  docs/overview.md
  docs/resource-editing.md
  docs/resource-navigation.md
  docs/resource-validation.md
  docs/source-editor.md
  mkdocs.yml
  source-editor.md
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/L
