Repository kubeshop/monokle, pull requests merged in 2022-05, with the labels that each got.

#1685 fix: remove welcome modal
  src/App.tsx
  src/components/atoms/IconMonokle/IconMonokle.tsx
  src/components/atoms/IconMonokle/index.ts
  src/components/atoms/index.ts
  src/components/organisms/AboutModal/AboutModal.tsx
  src/components/organisms/ReleaseNotes/ReleaseNotes.tsx
  src/components/organisms/StartupModal/StartupModal.tsx
  src/components/organisms/StartupModal/index.ts
  src/components/organisms/index.ts
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/utils/electronStore.ts
  tests/electronHelpers.ts
  tests/git.test.ts
Labels: size/L

#1687 chore: temp alternative telemetry
  .github/workflows/monokle-build-nightly.yml
  .github/workflows/monokle-publish-downloads.yml
  .github/workflows/monokle-publish.yml
  electron/app/index.ts
  electron/app/utils.ts
Labels: size/M

#1692 fix: fix left menu layout height
  src/components/molecules/TitleBar/TitleBar.tsx
  src/components/molecules/TitleBar/styled.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/styled.tsx
  src/components/organisms/KustomizePane/KustomizePane.tsx
  src/components/organisms/KustomizePane/styled.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
  src/components/organisms/ValidationDrawer/ValidationDrawer.styled.tsx
  src/constants/constants.ts
Labels: size/L

#1688 chore: add release notes for 1.7
  resources/releaseNotes/1.7/1.7.json
  resources/releaseNotes/1.7/1.7.md
  resources/releaseNotes/1.7/1.7.svg
  src/components/organisms/AboutModal/AboutModal.tsx
Labels: size/L

#1693 fix: amend fix left menu layout height
  src/components/organisms/KustomizePane/KustomizePane.tsx
  src/components/organisms/KustomizePane/styled.tsx
Labels: size/S

#1691 feat: separate walkthrough for new users and release features
  src/App.tsx
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/WalkThrough/WalkThrough.tsx
  src/components/molecules/WalkThrough/newReleaseFeaturesContent.ts
  src/components/molecules/WalkThrough/types.ts
  src/components/molecules/WalkThrough/walkThroughNoviceContent.ts
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/NavigatorPane/ClusterCompareButton.tsx
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
Labels: size/L

#1694 fix: fix reading packageJson in production builds
  src/components/organisms/AboutModal/AboutModal.tsx
  src/utils/getDependencyVersion.ts
Labels: size/M

#1699 chore: add MONOKLE_INSTALLS_URL env to workflow
  .github/workflows/monokle-build-nightly.yml
  .github/workflows/monokle-publish-downloads.yml
  .github/workflows/monokle-publish.yml
Labels: size/XS

#1701 fix: go directly to values file if there is just one link
  src/components/molecules/Monaco/codeIntel.ts
Labels: size/S

#1702 fix: deviceId value for telemetry
  electron/app/utils.ts
Labels: size/XS

#1706 chore: add help links
  src/components/organisms/StartProjectPane/Guide.tsx
Labels: size/S

#1709 chore(release): 1.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS

#1714 refactor: guide styling
  src/components/organisms/StartProjectPane/Guide.styled.tsx
  src/components/organisms/StartProjectPane/Guide.tsx
Labels: size/S

#1716 chore: direct download links in readme + small updates
  README.md
Labels: size/M

#1705 fix: fix filter scroll style
  src/index.css
Labels: size/S

#1726 telemetry: setup Amplitude
  .github/workflows/monokle-build-nightly.yml
  .github/workflows/monokle-publish-downloads.yml
  .github/workflows/monokle-publish.yml
  electron/app/amplitude.ts
  electron/app/createWindow.ts
  electron/app/index.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/utils.ts
  package-lock.json
  package.json
Labels: size/M

#1727 chore(release): 1.7.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS

#1736 fix: enabled OPA validation for preview resources
  src/redux/services/validation.ts
Labels: size/XS

#1740 fix: text typo
  src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
Labels: size/XS

#1730 refactor: show footer on start page + recent projects
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/StartProjectPane/Guide.styled.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.styled.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
Labels: size/S

#1633 docs: add draft policy validation
  docs/img/opa-error-editor-1.7.0.png
  docs/img/opa-error-navigator-1.7.0.png
  docs/img/opa-table-1.7.0.png
  docs/img/validation-overview-1.7.0.png
  docs/resource-validation.md
Labels: documentation, size/M

#1742 fix: recent projects overflow
  src/components/organisms/StartProjectPane/RecentProjectsPage.styled.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
Labels: size/XS

#1743 fix: nucleus telemetry
  electron/app/index.ts
  electron/app/utils.ts
Labels: size/XS

#1747 chore(release): 1.7.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#1750 feat: logs to file
  electron/app/menu.ts
  electron/app/openApplication.ts
  electron/main.ts
  package-lock.json
  package.json
  src/utils/logToFile.ts
  src/utils/shell.ts
Labels: size/M

#1751 [Snyk] Upgrade yaml from 2.0.0-10 to 2.0.1
  package-lock.json
  package.json
Labels: size/XS

#1748 feat: add hide unsupported files setting
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/SettingsManager/Settings.tsx
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/services/projectConfig.ts
  src/utils/electronStore.ts
Labels: size/M

#1757 fix: long alert message
  electron/app/menu.ts
  src/App.tsx
  src/components/molecules/NotificationMarkdown/NotificationMarkdown.tsx
  src/components/molecules/NotificationMarkdown/NotificationModalTitle.styled.tsx
  src/components/molecules/NotificationMarkdown/NotificationModalTitle.tsx
  src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx
  src/components/molecules/NotificationMarkdown/styled.tsx
  src/components/organisms/MessageBox/MessageBox.tsx
  src/components/organisms/NotificationsManager/Notification.styled.tsx
  src/components/organisms/NotificationsManager/Notification.tsx
  src/components/organisms/NotificationsManager/NotificationsManager.tsx
  src/components/organisms/NotificationsManager/styled.tsx
  src/components/organisms/index.ts
  src/redux/reducers/ui.ts
Labels: size/XL

#1759 fix: add update notice container z-index
  package-lock.json
  src/components/organisms/UpdateNotice/styled.tsx
Labels: size/XS

#1761 [Snyk] Upgrade redux from 4.1.2 to 4.2.0
  package-lock.json
  package.json
Labels: size/XS

#1715 feat: add top-level error boundary
  package-lock.json
  package.json
  src/App.tsx
  src/assets/figures/crash.svg
  src/components/organisms/ErrorPage/ErrorPage.styled.tsx
  src/components/organisms/ErrorPage/ErrorPage.tsx
  src/components/organisms/ErrorPage/ErrorStack.styled.tsx
  src/components/organisms/ErrorPage/ErrorStack.tsx
  src/components/organisms/ErrorPage/index.ts
  src/index.tsx
  src/redux/store.ts
  src/utils/logToFile.ts
Labels: size/L

#1744 feat: add feature flags
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/PaneManager/PaneManagerRightMenu.tsx
  src/utils/features.tsx
Labels: size/M

#1763 fix: fix shortcuts for windows
  src/utils/defineHotkey.ts
Labels: size/XS

#1774 Fixes for release
  electron/app/commands.ts
  electron/app/ipc/ipcListeners.ts
  package-lock.json
  src/components/organisms/ErrorPage/ErrorPage.tsx
  src/components/organisms/ErrorPage/ErrorStack.styled.tsx
  src/components/organisms/ErrorPage/ErrorStack.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/index.tsx
  src/utils/features.tsx
Labels: size/M

#1781 chore(release): 1.7.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#1778 refactor: remove global scrollbar style
  src/components/atoms/PaneContainer/PaneContainer.tsx
  src/components/molecules/ClusterDiff/ClusterDiff.styled.tsx
  src/components/molecules/ClusterDiff/ClusterDiff.tsx
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/NotificationMarkdown/styled.tsx
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/molecules/ValidationErrorsPopover/ErrorsPopoverContent.tsx
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
  src/components/organisms/ErrorPage/ErrorStack.styled.tsx
  src/components/organisms/HelmPane/styled.tsx
  src/components/organisms/KustomizePane/styled.tsx
  src/components/organisms/LazyDrawer/styled.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
  src/components/organisms/NavigatorPane/WarningAndErrorsDisplay.styled.tsx
  src/components/organisms/PageHeader/ClusterSelectionTable.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/ReleaseNotes/styled.tsx
  src/components/organisms/SettingsManager/styled.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
  src/components/organisms/TemplateModal/styled.tsx
  src/components/organisms/ValidationDrawer/ValidationDrawer.styled.tsx
  src/index.css
  src/utils/scrollbar.ts
Labels: size/L

#1776 refactor: errors/warnings highlighting
  src/components/molecules/Monaco/codeIntel/applyErrorIntel.ts
  src/components/molecules/Monaco/codeIntel/applyPolicyIntel.ts
  src/components/molecules/Monaco/codeIntel/applyRefIntel.ts
  src/components/molecules/Monaco/codeIntel/index.ts
  src/components/molecules/Monaco/editorConstants.ts
  src/index.css
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameCounter.styled.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameCounter.tsx
  src/styles/Colors.ts
Labels: size/XL

#1793 Wito/feat/compare everything
  electron/tsconfig.json
  package-lock.json
  src/App.tsx
  src/assets/figures/compareDouble.svg
  src/assets/figures/compareSingle.svg
  src/components/organisms/CompareModal/CompareActionBar.styled.tsx
  src/components/organisms/CompareModal/CompareActionBar.tsx
  src/components/organisms/CompareModal/CompareFigure.styled.tsx
  src/components/organisms/CompareModal/CompareFigure.tsx
  src/components/organisms/CompareModal/CompareModal.tsx
  src/components/organisms/CompareModal/CompareModalComparing.tsx
  src/components/organisms/CompareModal/CompareModalFooter.tsx
  src/components/organisms/CompareModal/CompareModalSelecting.styled.tsx
  src/components/organisms/CompareModal/CompareModalSelecting.tsx
  src/components/organisms/CompareModal/ComparisonList.styled.tsx
  src/components/organisms/CompareModal/ComparisonList.tsx
  src/components/organisms/CompareModal/DiffActionBar.styled.tsx
  src/components/organisms/CompareModal/DiffActionBar.tsx
  src/components/organisms/CompareModal/ResourceList.styled.tsx
  src/components/organisms/CompareModal/ResourceList.tsx
  src/components/organisms/CompareModal/ResourceSetSelector.styled.tsx
  src/components/organisms/CompareModal/ResourceSetSelector.tsx
  src/components/organisms/CompareModal/index.ts
  src/components/organisms/NavigatorPane/CompareButton.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/feature-flags.json
  src/models/rootstate.ts
  src/redux/listeners/base.ts
  src/redux/reducers/compare.ts
  src/redux/services/compare/compareResources.ts
  src/redux/services/compare/fetchResources.ts
  src/redux/store.ts
  src/styles/Colors.ts
  src/utils/features.tsx
  src/utils/yaml.ts
Labels: size/XXL

#1787 feat: restart preview shortcut for Monaco editor
  docs/hotkeys.md
  electron/app/openApplication.ts
  src/App.tsx
  src/components/molecules/Monaco/useEditorKeybindings.ts
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/constants/hotkeys.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartQuickAction.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationQuickAction.tsx
  src/utils/restartEditorPreview.ts
Labels: size/M

#1797 Wito/feat/add resource sets
  package-lock.json
  package.json
  src/components/organisms/CompareModal/CompareModal.tsx
  src/components/organisms/CompareModal/CompareModalSelecting.styled.tsx
  src/components/organisms/CompareModal/CompareModalSelecting.tsx
  src/components/organisms/CompareModal/ComparisonList.tsx
  src/components/organisms/CompareModal/ResourceSetSelector.styled.tsx
  src/components/organisms/CompareModal/ResourceSetSelector.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ClusterContextSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmChartSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmValuesSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/KustomizeSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.styled.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/index.ts
  src/components/organisms/CompareModal/types.ts
  src/redux/reducers/compare.ts
  src/redux/services/compare/fetchResources.ts
Labels: size/XL

#1798 fix codeintel folders
  src/components/molecules/Monaco/codeIntel/applyErrorIntel.ts
  src/components/molecules/Monaco/codeIntel/applyPolicyIntel.ts
  src/components/molecules/Monaco/codeIntel/applyRefIntel.ts
  src/components/molecules/Monaco/codeIntel/index.ts
Labels: size/XL

#1802 fix: add applyErrorIntel back
  package-lock.json
  src/components/molecules/Monaco/CodeIntel/k8sResource.ts
Labels: size/S

#1796 feat: search by multiple resource kinds
  src/components/molecules/ChangeFiltersConfirmModal/ChangeFiltersConfirmModal.tsx
  src/components/molecules/Monaco/symbolProcessing.ts
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/organisms/QuickSearchActions/QuickSearchActions.tsx
  src/models/appstate.ts
  src/redux/reducers/main.ts
  src/utils/resources.ts
Labels: size/M

#1801 Wito/feat/add operations and search
  src/App.tsx
  src/components/organisms/CompareModal/CompareActionBar.styled.tsx
  src/components/organisms/CompareModal/CompareActionBar.tsx
  src/components/organisms/NavigatorPane/CompareButton.tsx
  src/redux/reducers/compare.ts
  src/redux/services/compare/compareResources.ts
  src/redux/services/compare/filterComparisons.ts
  src/redux/store.ts
Labels: size/L

#1795 Wito/feat/analytics opa
  src/components/organisms/ValidationDrawer/Overview/ValidationOverview.tsx
  src/redux/reducers/main.ts
  src/utils/telemetry.ts
Labels: size/M

#1804 fix: hotfix build
  src/utils/telemetry.ts
Labels: size/XS

#1799 fix: enable resource search when focus in editor
  src/components/molecules/Monaco/useEditorKeybindings.ts
Labels: size/S

#1810 refactor: show force reload shortcut instead of reload
  electron/app/menu.ts
Labels: size/XS

#1806 fix: highlight file explorer for helm value file
  src/components/organisms/PaneManager/MenuButton/MenuButton.tsx
Labels: size/S

#1803 fix: display same selected resource when reloading cluster
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/redux/reducers/main.ts
  src/redux/services/helm.ts
  src/redux/services/preview.ts
Labels: size/S

#1807 refactor: actions pane header
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.styled.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
Labels: size/L

#1785 feat: images pane
  electron/app/menu.ts
  src/App.tsx
  src/assets/OutgoingImageRefIcon.svg
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/DockerImages.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/molecules/Monaco/CodeIntel/k8sResource.ts
  src/components/molecules/Monaco/CodeIntel/types.ts
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/editorConstants.ts
  src/components/molecules/Monaco/useCodeIntel.ts
  src/components/molecules/ResourceRefsIconPopover/RefLink.styled.tsx
  src/components/molecules/ResourceRefsIconPopover/RefLink.tsx
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.styled.tsx
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/DockerImagesPane/DockerImagesPane.styled.tsx
  src/components/organisms/DockerImagesPane/DockerImagesPane.tsx
  src/components/organisms/DockerImagesPane/index.ts
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/components/organisms/RenameResourceModal/RenameResourceModal.tsx
  src/components/organisms/ReplaceImageModal/ReplaceImageModal.tsx
  src/components/organisms/ReplaceImageModal/index.ts
  src/components/organisms/index.ts
  src/feature-flags.json
  src/index.css
  src/kindhandlers/common/outgoingRefMappers.ts
  src/models/appstate.ts
  src/models/image.ts
  src/models/k8sresource.ts
  src/models/navigator.ts
  src/models/resourcekindhandler.ts
  src/models/ui.ts
  src/navsections/DockerImagesSectionBlueprint/DockerImagesQuickAction.styled.tsx
  src/navsections/DockerImagesSectionBlueprint/DockerImagesQuickAction.tsx
  src/navsections/DockerImagesSectionBlueprint/DockerImagesSectionBlueprint.ts
  src/navsections/DockerImagesSectionBlueprint/DockerImagesSectionEmptyDisplay.tsx
  src/navsections/DockerImagesSectionBlueprint/DockerImagesSectionNameDisplay.styled.tsx
  src/navsections/DockerImagesSectionBlueprint/DockerImagesSectionNameDisplay.tsx
  src/navsections/DockerImagesSectionBlueprint/index.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/reducers/ui.ts
  src/redux/services/fileEntry.ts
  src/redux/services/resourceRefs.test.ts
  src/redux/services/resourceRefs.ts
  src/redux/services/selection.ts
  src/redux/store.ts
  src/redux/thunks/replaceImageTag.ts
  src/redux/thunks/replaceSelectedResourceMatches.ts
  src/redux/thunks/selectionHistory.ts
  src/redux/thunks/updateMultipleResources.ts
  src/utils/features.tsx
Labels: size/XXL

#1813 Updated Subject's Name with the Certificate Actual Subject
  package.json
Labels: size/XS

#1812 fix: monaco editor select image
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/useCodeIntel.ts
  src/models/appstate.ts
  src/navsections/DockerImagesSectionBlueprint/DockerImagesSectionBlueprint.ts
  src/redux/reducers/main.ts
  src/redux/thunks/selectionHistory.ts
Labels: size/M

#1814 Wito/feat/extend comparison filter
  package-lock.json
  package.json
  src/components/molecules/FilterPopover/FilterPopover.stories.tsx
  src/components/molecules/FilterPopover/FilterPopover.tsx
  src/components/molecules/FilterPopover/index.ts
  src/components/molecules/FilterPopover/keyValueInput/KeyValueInput.style.ts
  src/components/molecules/FilterPopover/keyValueInput/KeyValueInput.tsx
  src/components/molecules/FilterPopover/keyValueInput/NewKeyValueInput.tsx
  src/components/molecules/FilterPopover/keyValueInput/index.ts
  src/components/organisms/CompareModal/CompareActionBar.tsx
  src/components/organisms/CompareModal/ComparisonList.tsx
  src/components/organisms/CompareModal/types.ts
  src/redux/reducers/compare.ts
  src/redux/services/compare/filterComparisons.ts
  src/utils/filter.ts
Labels: size/XL

#1818 refactor: separate resource code intel
  src/components/molecules/Monaco/CodeIntel/k8sResource/applyErrorIntel.ts
  src/components/molecules/Monaco/CodeIntel/k8sResource/applyPolicyIntel.ts
  src/components/molecules/Monaco/CodeIntel/k8sResource/applyRefIntel.ts
  src/components/molecules/Monaco/CodeIntel/k8sResource/index.ts
Labels: size/L

#1828 refactor: rename docker image
  electron/app/menu.ts
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/Images.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/molecules/Monaco/CodeIntel/k8sResource/index.ts
  src/components/molecules/Monaco/CodeIntel/types.ts
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/useCodeIntel.ts
  src/components/molecules/ResourceRefsIconPopover/RefLink.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/DockerImagesPane/DockerImagesPane.tsx
  src/components/organisms/DockerImagesPane/index.ts
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/ImagesPane/ImagesPane.styled.tsx
  src/components/organisms/ImagesPane/ImagesPane.tsx
  src/components/organisms/ImagesPane/index.ts
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/components/organisms/ReplaceImageModal/ReplaceImageModal.tsx
  src/components/organisms/index.ts
  src/feature-flags.json
  src/models/appstate.ts
  src/models/image.ts
  src/models/ui.ts
  src/navsections/DockerImagesSectionBlueprint/DockerImagesSectionEmptyDisplay.tsx
  src/navsections/DockerImagesSectionBlueprint/index.ts
  src/navsections/ImagesSectionBlueprint/ImagesQuickAction.styled.tsx
  src/navsections/ImagesSectionBlueprint/ImagesQuickAction.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionBlueprint.ts
  src/navsections/ImagesSectionBlueprint/ImagesSectionEmptyDisplay.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.styled.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.tsx
  src/navsections/ImagesSectionBlueprint/index.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/services/fileEntry.ts
  src/redux/services/selection.ts
  src/redux/store.ts
  src/redux/thunks/replaceImageTag.ts
  src/redux/thunks/selectionHistory.ts
  src/utils/features.tsx
Labels: size/L

#1829 fix: fix warnings
  src/components/molecules/FilterPopover/FilterPopover.stories.tsx
  src/components/molecules/WalkThrough/WalkThrough.tsx
  src/components/organisms/KeyboardShortcuts/KeyboardShortcuts.tsx
  src/kindhandlers/common/customMatchers.ts
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenuWrapper.tsx
  src/redux/services/fileEntry.test.ts
Labels: size/M

#1836 chore(release): 1.7.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#1834 fix: replace deprecated placement prop for antd dropdown
  src/components/molecules/ContextMenu/ContextMenu.tsx
  src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
Labels: size/S

#1831 Wito/feat/add transfer
  src/components/molecules/FilterPopover/FilterPopover.tsx
  src/components/organisms/CompareModal/CompareActionBar.tsx
  src/components/organisms/CompareModal/CompareModal.tsx
  src/components/organisms/CompareModal/CompareModalComparing.tsx
  src/components/organisms/CompareModal/CompareModalSelecting.styled.tsx
  src/components/organisms/CompareModal/CompareModalSelecting.tsx
  src/components/organisms/CompareModal/ComparisonList.styled.tsx
  src/components/organisms/CompareModal/ComparisonList.tsx
  src/components/organisms/CompareModal/DiffActionBar.tsx
  src/components/organisms/CompareModal/ResourceList.styled.tsx
  src/components/organisms/CompareModal/ResourceList.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.tsx
  src/components/organisms/CompareModal/TransferButton.tsx
  src/components/organisms/CompareModal/types.ts
  src/constants/constants.ts
  src/models/k8sresource.ts
  src/redux/reducers/compare.ts
  src/redux/reducers/main.ts
  src/redux/services/clusterResource.ts
  src/redux/services/compare/compareResources.ts
  src/redux/services/compare/transferResource.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/utils.ts
Labels: size/XL

#1838 Compare everything: namespace override and improved inspection
  src/components/organisms/CompareModal/CompareActionBar.tsx
  src/components/organisms/CompareModal/CompareModal.tsx
  src/components/organisms/CompareModal/CompareModalComparing.tsx
  src/components/organisms/CompareModal/ComparisonInspection.tsx
  src/components/organisms/CompareModal/ComparisonList.styled.tsx
  src/components/organisms/CompareModal/ComparisonList.tsx
  src/components/organisms/CompareModal/DiffActionBar.tsx
  src/redux/reducers/compare.ts
  src/redux/services/compare/compareResources.ts
  src/redux/services/compare/transferResource.ts
  src/redux/thunks/utils.ts
Labels: size/L

#1840 Wito/feature/transfer single resource
  package-lock.json
  package.json
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/Monaco/useDebouncedCodeSave.ts
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/CompareModal/CompareModal.tsx
  src/components/organisms/CompareModal/ComparisonList.styled.tsx
  src/components/organisms/CompareModal/ComparisonList.tsx
  src/components/organisms/CompareModal/InspectionActionBar.styled.tsx
  src/components/organisms/CompareModal/InspectionActionBar.tsx
  src/components/organisms/CompareModal/TransferButton.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/components/organisms/NavigatorPane/CompareButton.tsx
  src/feature-flags.json
  src/models/appstate.ts
  src/models/k8sresource.ts
  src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
  src/redux/reducers/compare.ts
  src/redux/reducers/main.ts
  src/redux/services/compare/compareResources.ts
  src/redux/services/compare/transferResource.ts
  src/redux/services/manifest-utils.ts
  src/redux/services/resource.test.ts
  src/redux/services/templates.ts
  src/redux/services/validation.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/renameResource.ts
  src/redux/thunks/updateResource.ts
  src/redux/thunks/utils.ts
Labels: size/L

#1841 Wito/feature/helm quick compare
  electron/app/commands.ts
  src/components/molecules/QuickActionCompare/QuickActionCompare.tsx
  src/components/molecules/QuickActionCompare/index.ts
  src/components/molecules/QuickActionCompare/styled.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmChartSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmValuesOrConfigSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/index.ts
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartQuickAction.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationQuickAction.tsx
  src/redux/reducers/compare.ts
  src/redux/selectors.ts
  src/redux/services/compare/fetchResources.ts
  src/redux/thunks/applyHelmChart.ts
  src/redux/thunks/applyYaml.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/previewReferencedHelmChart.ts
  src/redux/thunks/runPreviewConfiguration.ts
  src/utils/command.ts
  src/utils/kubeclient.ts
Labels: size/L

#1755 draft: Wito/fix/fix config merge
  electron/app/initKubeconfig.ts
  src/feature-flags.json
  src/redux/services/projectConfig.ts
Labels: size/M

#1850 fix: add tooltips delay
  src/components/molecules/FilePatternList/FilePatternList.tsx
  src/components/molecules/NotificationMarkdown/NotificationModalTitle.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/NotificationsManager/Notification.tsx
  src/components/organisms/PluginManager/PluginManager.tsx
  src/components/organisms/SettingsManager/Settings.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/StartProjectPane/RecentProject.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
  src/components/organisms/ValidationDrawer/OpenPolicyAgent/useOpenPolicyAgentTable.tsx
  src/navsections/HelmChartSectionBlueprint/PreviewConfigurationNameSuffix.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionNameSuffix.tsx
Labels: size/M

#1823 feat: filters preset
  src/App.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/organisms/FiltersPresetModal/FiltersPresetModal.styled.tsx
  src/components/organisms/FiltersPresetModal/FiltersPresetModal.tsx
  src/components/organisms/FiltersPresetModal/index.ts
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/index.ts
  src/constants/tooltips.tsx
  src/index.css
  src/models/appstate.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/reducers/ui.ts
  src/styles/Colors.ts
  src/utils/electronStore.ts
Labels: size/L

#1854 chore(release): 1.7.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/M

#1852 Wito/feat/compare wrapup
  electron/app/commands.ts
  electron/app/ipc/ipcListeners.ts
  src/App.tsx
  src/components/molecules/QuickActionCompare/QuickActionCompare.tsx
  src/components/organisms/CompareModal/CompareActionBar.tsx
  src/components/organisms/CompareModal/CompareModal.styled.tsx
  src/components/organisms/CompareModal/CompareModal.tsx
  src/components/organisms/CompareModal/CompareModalSelecting.styled.tsx
  src/components/organisms/CompareModal/CompareModalSelecting.tsx
  src/components/organisms/CompareModal/ComparisonInspection.tsx
  src/components/organisms/CompareModal/ComparisonList.tsx
  src/components/organisms/CompareModal/InspectionActionBar.tsx
  src/components/organisms/CompareModal/ResourceList.styled.tsx
  src/components/organisms/CompareModal/ResourceList.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ClusterContextSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmChartSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/HelmSelect/HelmValuesOrConfigSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/KustomizeSelect.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx
  src/components/organisms/CompareModal/TransferButton.tsx
  src/components/organisms/NavigatorPane/CompareButton.tsx
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/feature-flags.json
  src/models/rootstate.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartQuickAction.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationQuickAction.tsx
  src/redux/compare/index.ts
  src/redux/compare/listeners.ts
  src/redux/compare/selectors.ts
  src/redux/compare/slice.ts
  src/redux/compare/state.ts
  src/redux/compare/thunks.ts
  src/redux/compare/utils.ts
  src/redux/reducers/compare.ts
  src/redux/reducers/main.ts
  src/redux/services/compare/compareResources.ts
  src/redux/services/compare/fetchResources.ts
  src/redux/services/compare/filterComparisons.ts
  src/redux/services/compare/transferResource.ts
  src/redux/store.ts
  src/redux/thunks/applyHelmChart.ts
  src/redux/thunks/applyYaml.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/previewReferencedHelmChart.ts
  src/redux/thunks/runPreviewConfiguration.ts
  src/redux/thunks/utils.ts
  src/utils/commands/execute.ts
  src/utils/commands/helm.ts
  src/utils/commands/index.ts
  src/utils/error.ts
  src/utils/kubeclient.ts
  src/utils/telemetry.ts
Labels: size/XXL

#1858 Redesign top panel
  package-lock.json
  package.json
  src/assets/FolderSmallPlusWhite.svg
  src/assets/FolderSmallWhite.svg
  src/assets/PlusIcon.svg
  src/assets/TemplateSmallWhite.svg
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/CreateProject.styled.tsx
  src/components/organisms/PageHeader/CreateProject.tsx
  src/components/organisms/PageHeader/HelpMenu.styled.tsx
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/styles/Colors.ts
Labels: size/XXL

#1863 fix: Flickering documentation link
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/XS

#1862 Wito/fix/fix cluste transfer
  src/redux/services/compare/fetchResources.ts
  src/redux/services/compare/transferResource.ts
  src/utils/commands/execute.ts
  src/utils/commands/kubectl.ts
  src/utils/yaml.ts
Labels: size/L

#1842 stan-gabriel/feat/key-for-deleting
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/constants/hotkeys.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
Labels: size/M

#1856 [Snyk] Upgrade @rjsf/core from 4.1.0 to 4.2.0
  package-lock.json
  package.json
Labels: size/XS

#1857 [Snyk] Upgrade @rjsf/antd from 4.1.0 to 4.2.0
  package-lock.json
  package.json
Labels: size/XS

#1865 feat: add different color themes for different preview modes
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/styles/Colors.ts
Labels: size/S

#1859 Divide settings pane into 3 tabs
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/SettingsManager/styled.tsx
  src/components/organisms/SettingsManager/types.ts
Labels: size/M

#1817 feat: images info pane
  package-lock.json
  package.json
  src/components/molecules/ImageDetails/ImageDetails.styled.tsx
  src/components/molecules/ImageDetails/ImageDetails.tsx
  src/components/molecules/ImageDetails/ImageTags.styled.tsx
  src/components/molecules/ImageDetails/ImageTags.tsx
  src/components/molecules/ImageDetails/index.ts
  src/components/molecules/index.ts
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetSelector.tsx
  src/constants/tooltips.tsx
  src/feature-flags.json
  src/models/image.ts
  src/styles/Colors.ts
  src/utils/features.tsx
Labels: size/L

#1864 chore: remove workflow condition in favor of website re-runs
  .github/workflows/monokle-publish-updater.yml
Labels: size/XS
