Repository kubeshop/monokle, pull requests merged in 2022-07, with the labels that each got.

#2028 fix: Namespace help link goes to wrong kubernetes docs page
  src/utils/shell.ts
Labels: size/XS

#2026 [Snyk] Security upgrade git-url-parse from 11.6.0 to 12.0.0
  package-lock.json
  package.json
Labels: size/XS

#1957 Upgrade devDependencies packages
  package-lock.json
  package.json
  patches/react-reflex+4.0.6.patch
  patches/react-reflex+4.0.9.patch
  src/App.tsx
  src/components/atoms/Row/Row.tsx
  src/components/molecules/ContextMenu/ContextMenu.tsx
  src/components/molecules/FilterPopover/FilterPopover.tsx
  src/components/molecules/GraphView/GraphView.tsx
  src/components/molecules/GraphView/Sidebar.tsx
  src/components/molecules/TitleBar/TitleBar.tsx
  src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/CompareModal/CompareFigure.tsx
  src/components/organisms/LazyDrawer/LazyDrawer.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/components/organisms/NavigatorPane/ClusterCompareButton.tsx
  src/components/organisms/NavigatorPane/CompareButton.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/components/organisms/PaneManager/react-reflex/package.json
  src/components/organisms/PaneManager/react-reflex/readme.md
  src/components/organisms/PaneManager/react-reflex/types.d.ts
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/redux/compare/slice.ts
  src/utils/features.tsx
Labels: size/L

#2035 feat: added EndpointSlice handler
  src/kindhandlers/EndpointSlice.handler.ts
  src/kindhandlers/Endpoints.handler.ts
  src/kindhandlers/index.ts
Labels: size/M

#2039 fix: fix FileTree type issue
  package-lock.json
  package.json
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/FileTreePane/types.tsx
Labels: size/S

#2025 feat: resources popover for images
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/molecules/ValidationErrorsPopover/ErrorsPopoverContent.tsx
  src/navsections/ImagesSectionBlueprint/ImageOutgoingResourcesPopover.styled.tsx
  src/navsections/ImagesSectionBlueprint/ImageOutgoingResourcesPopover.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameSuffix.styled.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameSuffix.tsx
  src/utils/refs.ts
Labels: size/L

#1948 Show the file name to be created when adding a new resource and save to folder #1263
  src/components/organisms/NewResourceWizard/NewResourceWizard.styled.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
Labels: size/L

#2043 chore: update package-lock.json
  package-lock.json
Labels: size/XS

#2038 feat: configurable sibling matchers
  resources/kindhandlers/handlers/cert-manager.io/Certificate.json
  resources/kindhandlers/handlers/cert-manager.io/CertificateRequest.json
  src/kindhandlers/common/customMatchers.ts
  src/kindhandlers/common/customObjectKindHandler.ts
  src/models/resourcekindhandler.ts
  src/redux/services/__test__/manifests/issuerRefs/testkube-operator-selfsigned-issuer.yaml
  src/redux/services/__test__/manifests/issuerRefs/testkube-operator-serving-cert-fbtng.yaml
  src/redux/services/resourceRefs.test.ts
  src/redux/services/resourceRefs.ts
Labels: size/L

#2044 feat: added more native resource kinds to navigator
  src/kindhandlers/HorizontalPodAutoscaler.handler.ts
  src/kindhandlers/LimitRange.handler.ts
  src/kindhandlers/ResourceQuota.handler.ts
  src/kindhandlers/StorageClass.handler.ts
  src/kindhandlers/VolumeAttachment.handler.ts
  src/kindhandlers/index.ts
Labels: size/L

#2046 fix: mentioned the file path only once
  src/components/molecules/Monaco/CodeIntel/helmChartFile.ts
  src/components/molecules/Monaco/CodeIntel/helmValues.ts
  src/components/molecules/Monaco/editorHelpers.ts
Labels: size/S

#2047 fix: hover disposable instead of link
  src/components/molecules/Monaco/CodeIntel/helmChartFile.ts
Labels: size/S

#2050 fix: reprocess helm value file/template
  src/components/molecules/Monaco/CodeIntel/helmChartFile.ts
  src/components/molecules/Monaco/CodeIntel/helmValues.ts
  src/components/molecules/Monaco/CodeIntel/types.ts
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/useCodeIntel.ts
  src/components/molecules/Monaco/useDebouncedCodeSave.ts
  src/models/appstate.ts
  src/models/helm.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/services/fileEntry.test.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
  src/redux/thunks/setRootFolder.ts
  src/redux/thunks/updateFileEntry.ts
Labels: size/L

#2056 style: added margin to telemetry buttons content in notification box
  src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx
  src/components/molecules/NotificationMarkdown/styled.tsx
Labels: size/XS

#2033 chore: add watcher
  electron/app/initKubeconfig.ts
  electron/app/kubeConfigMonitor.ts
  jest.env.js
  package-lock.json
  package.json
  src/App.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/selectors.ts
  src/redux/services/compare/fetchResources.ts
  src/redux/services/kubeConfigMonitor.ts
  src/redux/thunks/loadClusterDiff.ts
  src/redux/thunks/loadKubeConfig.ts
  src/utils/helpers.ts
  src/utils/kubeclient.ts
Labels: size/XL

#2059 chore: listen project kubeconfig path
  electron/app/initKubeconfig.ts
  src/redux/services/kubeConfigMonitor.ts
  src/redux/services/projectConfig.ts
Labels: size/M

#1832 feat: Search and Replace functionality
  package-lock.json
  package.json
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/Search.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/molecules/Monaco/CodeIntel/fileWithMatchesIntel.ts
  src/components/molecules/Monaco/CodeIntel/index.ts
  src/components/molecules/Monaco/CodeIntel/types.ts
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/editorConstants.ts
  src/components/molecules/Monaco/useCodeIntel.ts
  src/components/molecules/Monaco/useDebouncedCodeSave.ts
  src/components/organisms/FileTreePane/CreateNode.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/FileTreePane/types.tsx
  src/components/organisms/NavigatorPane/OPAValidationStatus.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PaneManager/MenuButton/styled.ts
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/components/organisms/SearchPane/CreateFilteredNode.tsx
  src/components/organisms/SearchPane/QueryMatchParams.tsx
  src/components/organisms/SearchPane/RecentSearch.tsx
  src/components/organisms/SearchPane/SearchPane.tsx
  src/components/organisms/SearchPane/index.ts
  src/components/organisms/SearchPane/styled.tsx
  src/components/organisms/StartProjectPane/RecentProject.styled.tsx
  src/hooks/fileTreeHooks/index.ts
  src/hooks/fileTreeHooks/useCreate.tsx
  src/hooks/fileTreeHooks/useDelete.tsx
  src/hooks/fileTreeHooks/useDuplicate.tsx
  src/hooks/fileTreeHooks/useFileSelect.tsx
  src/hooks/fileTreeHooks/useHighlightNode.ts
  src/hooks/fileTreeHooks/usePreview.tsx
  src/hooks/fileTreeHooks/useProcessing.tsx
  src/index.css
  src/models/appstate.ts
  src/models/fileentry.ts
  src/models/icons.ts
  src/models/ui.ts
  src/navsections/ImagesSectionBlueprint/ImagesQuickAction.styled.tsx
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/reducers/ui.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
  src/redux/thunks/updateFileEntry.ts
  src/styles/Colors.ts
  src/utils/filterQuery.ts
  src/utils/replaceInFiles.ts
Labels: size/XXL

#2063 feat: cluster environments colors
  package-lock.json
  src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
  src/components/molecules/ModalConfirm/ModalConfirm.tsx
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.styled.tsx
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/ClusterResourceDiffModal/styled.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/components/organisms/LocalResourceDiffModal/styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/ClusterSelectionTable.styled.tsx
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/constants/constants.ts
  src/constants/makeApplyText.ts
  src/constants/makeApplyText.tsx
  src/index.css
  src/models/appconfig.ts
  src/models/cluster.ts
  src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.styled.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.tsx
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionNameSuffix.styled.tsx
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionNameSuffix.tsx
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/selectors.ts
  src/styles/Colors.ts
  src/utils/electronStore.ts
Labels: size/XXL

#2051 enhancement : Disable Deploy, Cluster Compare, Diff actions if cluster is no…
  electron/app/menu.ts
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/CompareModal/ResourceSetSelector/ResourceSetTypeSelect.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/NavigatorPane/CompareButton.tsx
  src/constants/tooltips.tsx
Labels: size/M

#2065 chore: fix test type error + update package-lock
  package-lock.json
  tests/git.test.ts
Labels: size/XS

#2060 fix: fixed displaying list of FilePatternListItem in cluster when editing context
  src/components/molecules/FilePatternList/FilePatternList.tsx
Labels: size/S

#2068 Update CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#2073 fix: do not flat arrays & compare arrays
  src/redux/reducers/appConfig.ts
  src/redux/services/projectConfig.ts
Labels: size/S

#2075 fix: fix test errors
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
Labels: size/XS

#2074 feat: kustomize/helm context menu
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/SearchPane/SearchPane.tsx
  src/hooks/fileTreeHooks/index.ts
  src/hooks/fileTreeHooks/useDelete.tsx
  src/hooks/fileTreeHooks/useDuplicate.tsx
  src/hooks/fileTreeHooks/useFileSelect.tsx
  src/hooks/fileTreeHooks/useFilterByFileOrFolder.tsx
  src/hooks/fileTreeHooks/usePreview.tsx
  src/hooks/fileTreeHooks/useRename.tsx
  src/kindhandlers/StorageClass.handler.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenuWrapper.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenu.tsx
  src/redux/services/kustomize.ts
  src/utils/files.ts
Labels: size/XL

#2076 fix: reprocess kustomizations on duplicate
  package-lock.json
  src/redux/services/fileEntry.ts
  src/redux/services/kustomize.ts
  src/redux/services/resource.ts
Labels: size/S

#2079 fix: telemetry
  electron/app/createWindow.ts
  electron/app/index.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/utils.ts
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/redux/reducers/appConfig.ts
  src/utils/segment.ts
  src/utils/telemetry.ts
Labels: size/M

#2072 fix: update file content for Monaco editor when deleting its resource
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/useDebouncedCodeSave.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/redux/reducers/main.ts
Labels: size/XS

#2077 chore: remove old blog post from README
  README.md
Labels: size/XS

#2011 feat: image selection ui widget
  docs/templates.md
  resources/form-schemas/deployment-ui-schema.json
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/FormEditor/FormWidgets/ImageSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/NamespaceSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/index.ts
  src/scripts/generate-schema.ts
Labels: size/L

#2081 chore: update package-lock
  package-lock.json
Labels: size/XS

#2090 feat: add feedback option to help menu
  src/components/organisms/PageHeader/HelpMenu.styled.tsx
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/constants/tooltips.tsx
Labels: size/M

#2088 chore: release notes for 1.9
  docs/index.md
  resources/releaseNotes/1.9/1.9.json
  resources/releaseNotes/1.9/1.9.md
  resources/releaseNotes/1.9/1.9.svg
Labels: size/L

#2091 refactor: resources links icon color for selected
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameSuffix.tsx
Labels: size/XS

#2092 fix: added media queries and fixed styling in StartProjectPage
  src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
  src/styles/Device.ts
Labels: size/M

#2094 chore: change Search to Find in release notes
  resources/releaseNotes/1.9/1.9.json
  resources/releaseNotes/1.9/1.9.md
Labels: size/XS

#2095 fix: added new media query stop to fix Entry screen
  src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
  src/styles/Device.ts
Labels: size/XS

#2096 fix: removed media query and displaying title always in two lines after investigation with @julio
  src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
Labels: size/XS

#2097 chore(release): 1.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#2102 fix: add null checker for isKustomizationFile function
  package-lock.json
  src/redux/services/kustomize.ts
Labels: size/XS

#2103 chore(release): 1.9.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS

#2107 docs: Update Screenshots
  docs/features.md
  docs/img/comparing-resources-1.9.png
  docs/img/diff-button-1.9.png
  docs/img/find-file-and-dead-links-1.9.gif
  docs/img/kustomization-1.9.gif
  docs/img/manage-multiple-projects-1.9.gif
  docs/img/monokle-settings-1.9.gif
  docs/img/monokle-ui-1.9.png
  docs/img/name-project-1.9.png
  docs/img/navigator-1.9.png
  docs/img/new-user-start-screen-1.9.png
  docs/img/returning-user-start-screen-1.9.png
  docs/img/select-comparing-resources-1.9.png
  docs/img/start-with-template-1.9.png
  docs/img/template-selection-1.9.png
  docs/img/upstream-downstream-1.9.gif
  docs/index.md
  docs/overview.md
Labels: size/L

#2106 [Snyk] Upgrade electron-log from 4.4.6 to 4.4.8
  package-lock.json
  package.json
Labels: size/XS

#2105 Julia/feat/search and replace shortcuts
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/SearchPane/SearchPane.tsx
  src/constants/hotkeys.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
Labels: size/M

#2111 refactor: molecules components until FilePatternList
  src/components/molecules/ChangeFiltersConfirmModal/ChangeFiltersConfirmModal.tsx
  src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
  src/components/molecules/ClusterDiff/ClusterDiff.styled.tsx
  src/components/molecules/ClusterDiff/ClusterDiff.tsx
  src/components/molecules/ClusterDiff/ClusterDiffNamespaceFilter.styled.tsx
  src/components/molecules/ClusterDiff/ClusterDiffNamespaceFilter.tsx
  src/components/molecules/ContextMenu/ContextMenu.tsx
  src/components/molecules/FilePatternList/FilePatternList.styled.tsx
  src/components/molecules/FilePatternList/FilePatternList.tsx
  src/components/molecules/FilePatternList/FilePatternListItem.styled.tsx
  src/components/molecules/FilePatternList/FilePatternListItem.tsx
  src/components/organisms/FileTreePane/types.tsx
Labels: size/L

#2112 chore: update package-lock
  package-lock.json
Labels: size/XS

#2098 fix: Kubeconfig path not changing
  src/App.tsx
  src/components/organisms/SettingsManager/Settings.tsx
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
Labels: size/M

#2118 docs: Update Screenshots for Release 1.9
  docs/creating-resources.md
  docs/file-explorer.md
  docs/form-editor.md
  docs/img/add-resource-1.9.png
  docs/img/error-details-popup-1.9.png
  docs/img/expand-1.9.gif
  docs/img/explorer-file-actions-1.9.png
  docs/img/explorer-folder-actions-1.9.png
  docs/img/filter-from-editor-1.9.png
  docs/img/form-editor-1.9.png
  docs/img/link-syntax-errors-image-1-1.9.png
  docs/img/metadata-button-image-1.9.png
  docs/img/navigation-history-1.9.png
  docs/img/navigator-broken-links-list-1.9.png
  docs/img/navigator-link-and-syntax-errors-header-1.9.png
  docs/img/navigator-link-syntax-errors-1.9.png
  docs/img/navigator-resource-options-1.9.png
  docs/img/navigator-syntax-errors-list-1.9.png
  docs/img/navigator-unknown-resource-options-1.9.png
  docs/img/opa-error-editor-1.9.png
  docs/img/opa-error-navigator-1.9.png
  docs/img/opa-table-1.9.png
  docs/img/quick-filter-popup-1.9.png
  docs/img/recent-folders-1.9.png
  docs/img/rename-1.9.png
  docs/img/resource-filtering-1.9.png
  docs/img/resource-navigation-1-1.9.png
  docs/img/resource-navigation-2-1.9.png
  docs/img/save-resource-1.9.png
  docs/img/secret-resource-hover-2-1.9.png
  docs/img/select-multi-resource-1.9.png
  docs/img/source-editor-auto-complete-1.9.png
  docs/img/source-editor-context-hover-1.9.png
  docs/img/template-1.9.png
  docs/img/unsaved-resource-1.9.png
  docs/img/validation-overview-1.9.png
  docs/resource-editing.md
  docs/resource-navigation.md
  docs/resource-validation.md
Labels: size/L

#2119 fix: recentSearch boolean check added to child component
  src/components/organisms/SearchPane/SearchPane.tsx
Labels: size/XS

#2120 fix: select hover in search fixed
  src/components/organisms/SearchPane/styled.tsx
Labels: size/XS

#2116 Julia/feat/edit text files
  package-lock.json
  package.json
  src/components/organisms/FileTreePane/CreateNode.tsx
  src/components/organisms/FileTreePane/types.tsx
  src/components/organisms/SearchPane/CreateFilteredNode.tsx
  src/components/organisms/SearchPane/SearchPane.tsx
  src/constants/hotkeys.ts
  src/hooks/fileTreeHooks/useFileSelect.tsx
  src/models/fileentry.ts
  src/models/ui.ts
  src/redux/initialState.ts
  src/redux/reducers/main.ts
  src/redux/reducers/ui.ts
  src/redux/services/fileEntry.test.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
Labels: size/M

#2127 [Snyk] Upgrade react-monaco-editor from 0.46.0 to 0.49.0
  package.json
Labels: size/XS

#2128 [Snyk] Upgrade type-fest from 2.14.0 to 2.15.1
  package-lock.json
  package.json
Labels: size/XS

#2129 [Snyk] Upgrade @reduxjs/toolkit from 1.8.2 to 1.8.3
  package-lock.json
  package.json
Labels: size/XS

#2131 feat: add/delete namespace from cluster selection
  src/redux/reducers/appConfig.ts
Labels: size/S

#2124 docs: Update Screenshots for 1.9 Release
  docs/cluster-compare.md
  docs/cluster-integration.md
  docs/helm.md
  docs/img/cluster-compare-button-1.9.png
  docs/img/cluster-preview-1.9.png
  docs/img/cluster-preview2-1.9.png
  docs/img/cluster-selector-1.9.png
  docs/img/clusters-tab-1.9.png
  docs/img/helm-navigation-1.9.png
  docs/img/helm-preview-action-1.9.png
  docs/img/helm-preview-configurations-1.9.png
  docs/img/helm-preview-output-1.9.png
  docs/img/helm-preview-reload-1.9.png
  docs/img/helm-settings-1.9.png
  docs/img/invoke-kustomize-setting-1.9.png
  docs/img/kubeconfig-setting-1.9.png
  docs/img/kust-preview-reload-1.9.png
  docs/img/kustomize-navigation-1.9.png
  docs/img/kustomize-outgoing-links-1.9.png
  docs/img/kustomize-preview-1.9.png
  docs/img/kustomize-preview-action-1.9.png
  docs/img/kustomize-preview-content-1.9.png
  docs/img/kustomize-settings-1.9.png
  docs/img/navigator-resource-check-box-1.9.png
  docs/img/navigator-resource-cluster-actions-1.9.png
  docs/img/navigator-select-cluster-resources-1.9.png
  docs/img/preview-configuration-drawer-1.9.png
  docs/img/resource-compare-button-1.9.png
  docs/img/resource-compare-options-1.9.png
  docs/img/resource-compare-selection-1.9.png
  docs/img/select-and-manage-projects-1.9.png
  docs/img/select-folder-1.9.png
  docs/kustomize.md
  docs/projects.md
  mkdocs.yml
Labels: size/M

#2135 feat: update package-lock
  package-lock.json
Labels: size/XS

#2140 fix: enable markdown for see more notification content
  src/components/molecules/NotificationMarkdown/NotificationMarkdown.tsx
Labels: size/XS

#2136 refactor: molecules components part two
  src/components/molecules/HelmChartModalConfirmWithNamespaceSelect/HelmChartModalConfirmWithNamespaceSelect.styled.tsx
  src/components/molecules/HelmChartModalConfirmWithNamespaceSelect/HelmChartModalConfirmWithNamespaceSelect.tsx
  src/components/molecules/ModalConfirm/ModalConfirm.styled.tsx
  src/components/molecules/ModalConfirm/ModalConfirm.tsx
  src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.styled.tsx
  src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.tsx
  src/components/molecules/PreviewDropdown/PreviewDropdown.styled.tsx
  src/components/molecules/PreviewDropdown/PreviewDropdown.tsx
  src/components/molecules/PreviewDropdown/PreviewMenu.tsx
  src/components/molecules/QuickActionCompare/QuickActionCompare.styled.tsx
  src/components/molecules/QuickActionCompare/QuickActionCompare.tsx
  src/components/molecules/QuickActionCompare/index.ts
  src/components/molecules/QuickActionPreview/QuickActionPreview.styled.tsx
  src/components/molecules/QuickActionPreview/QuickActionPreview.tsx
  src/components/molecules/QuickActionPreview/styled.tsx
  src/components/molecules/index.ts
  src/models/helm.ts
  src/models/kustomize.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartQuickAction.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationQuickAction.tsx
Labels: size/L

#2141 feat: kill terminal
  electron/app/createWindow.ts
  electron/app/ipc/ipcListeners.ts
  package-lock.json
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
  src/components/organisms/TerminalPane/TerminalPane.styled.tsx
  src/components/organisms/TerminalPane/TerminalPane.tsx
  src/constants/tooltips.tsx
  src/models/appstate.ts
  src/models/rootstate.ts
  src/models/terminal.ts
  src/redux/initialState.ts
  src/redux/reducers/extension.ts
  src/redux/reducers/main.ts
  src/redux/reducers/terminal.ts
  src/redux/store.ts
Labels: size/L

#2143 docs: Update Docs for Release 1.9
  docs/apply-and-diff.md
  docs/img/add-new-plugin-1.9.png
  docs/img/default-templates-1.9.gif
  docs/img/deploy-and-diff-buttons-1.9.png
  docs/img/diff-tble-8-1.9.png
  docs/img/open-plugin-manager-1.9.png
  docs/img/view-template-icon-1.9.png
  docs/plugins.md
  docs/templates.md
  docs/tutorials/how-to-browse-clusters.md
  docs/tutorials/how-to-configure-monokle.md
  docs/tutorials/how-to-create-and-edit-configmap.md
  docs/tutorials/how-to-fix-broken-links.md
  docs/tutorials/how-to-navigate-and-edit-manifests.md
  docs/tutorials/img/add-pattern-1.9.png
  docs/tutorials/img/add-pattern-7-1.9.png
  docs/tutorials/img/add-resource-save-options-1.9.png
  docs/tutorials/img/browse-1.9.png
  docs/tutorials/img/cluster-mode-1-1.9.png
  docs/tutorials/img/config-map-add-resource-1.9.png
  docs/tutorials/img/deploy-1-1.9.png
  docs/tutorials/img/deploy-1.9.png
  docs/tutorials/img/diff-7-1.9.png
  docs/tutorials/img/editor-5-1.9.png
  docs/tutorials/img/exit-9-1.9.png
  docs/tutorials/img/image-10-1.9.png
  docs/tutorials/img/image-11-1.9.png
  docs/tutorials/img/image-12-1.9.png
  docs/tutorials/img/image-13-1.9.png
  docs/tutorials/img/image-14-1.9.png
  docs/tutorials/img/image-15-1.9.png
  docs/tutorials/img/image-16-1.9.png
  docs/tutorials/img/image-17-1.9.png
  docs/tutorials/img/image-18-1.9.png
  docs/tutorials/img/image-19-1.9.png
  docs/tutorials/img/image-20-1.9.png
  docs/tutorials/img/image-21-1.9.png
  docs/tutorials/img/image-22-1.9.png
  docs/tutorials/img/image-4-1.9.png
  docs/tutorials/img/image-6-1.9.png
  docs/tutorials/img/image-7-1.9.png
  docs/tutorials/img/image-8-1.9.png
  docs/tutorials/img/image-9-1.9.png
  docs/tutorials/img/imaged-3-1.9.gif
  docs/tutorials/img/imaged-4-1.9.png
  docs/tutorials/img/imaged-5-1.9.png
  docs/tutorials/img/imaged-6-1.9.png
  docs/tutorials/img/imaged-7-1.9.png
  docs/tutorials/img/kubeconfig-1.9.png
  docs/tutorials/img/new-user-start-screen-1.9.png
  docs/tutorials/img/new-user-start-screen.png
  docs/tutorials/img/ok-1.9.png
  docs/tutorials/img/ok-8-1.9.png
  docs/tutorials/img/resource-link-4-1.9.gif
  docs/tutorials/img/resources-6-1.9.png
  docs/tutorials/img/settings-1.9.png
  docs/tutorials/img/startup-1.9.png
  docs/tutorials/img/tutorial-cluster-selector-1.9.png
  docs/tutorials/img/tutorial-diff-tble-8-1.9.png
  docs/tutorials/img/tutorial-metadata-button-image-1.9.png
Labels: size/L

#2022 docs: updates for 1.8 & 1.9
  docs/cluster-compare.md
  docs/compare-sync.md
  docs/helm.md
  docs/images.md
  docs/img/compare-sync-configure-1-9-1.png
  docs/img/compare-sync-overview-1-9-1.png
  docs/img/helm-templates-1-8-0.png
  docs/img/helm-templates-unsatisfied-1-8-0.png
  docs/img/helm-values-reference-1-8-0.png
  docs/img/images-panel-1-8-0.png
  docs/img/images-panel-hover-1-8-0.png
  docs/img/images-panel-replace-1-8-0.png
  mkdocs.yml
Labels: size/L

#2142 refactor: molecules component 3
  src/App.tsx
  src/components/molecules/FilterPopover/FilterPopover.tsx
  src/components/molecules/ResourceDiff/ResourceDiff.styled.tsx
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/components/molecules/ResourceFilterIconWithPopover/ResourceFilterIconWithPopover.tsx
  src/components/molecules/ResourceNamespaceFilter/ResourceNamespaceFilter.tsx
  src/components/molecules/ResourceRefsIconPopover/RefIcon.tsx
  src/components/molecules/ResourceRefsIconPopover/RefLink.tsx
  src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.styled.tsx
  src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.styled.tsx
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/TitleBar/TitleBar.styled.tsx
  src/components/molecules/TitleBar/TitleBar.tsx
  src/components/molecules/ValidationErrorsPopover/ErrorsPopoverContent.styled.tsx
  src/components/molecules/ValidationErrorsPopover/ErrorsPopoverContent.tsx
  src/components/molecules/ValidationErrorsPopover/ValidationErrorLink.styled.tsx
  src/components/molecules/ValidationErrorsPopover/ValidationErrorLink.tsx
  src/components/molecules/ValidationErrorsPopover/ValidationErrorsPopover.tsx
  src/components/molecules/WalkThrough/index.ts
  src/components/molecules/Walkthrough/Walkthrough.styled.tsx
  src/components/molecules/Walkthrough/Walkthrough.tsx
  src/components/molecules/Walkthrough/content/index.ts
  src/components/molecules/Walkthrough/content/newReleaseFeatures.ts
  src/components/molecules/Walkthrough/content/novice.ts
  src/components/molecules/Walkthrough/index.ts
  src/components/molecules/index.ts
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ClusterDiffModal/ClusterDiffModal.tsx
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/MessageBox/MessageBox.tsx
  src/components/organisms/NavigatorPane/CompareButton.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/NotificationsManager/Notification.tsx
  src/components/organisms/PageHeader/ClusterSelectionTable.tsx
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/SettingsManager/Settings.tsx
  src/models/walkthrough.ts
  src/navsections/ClusterDiffSectionBlueprint/ResourceMatchNameDisplay.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenuWrapper.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSuffix.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenu.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenuWrapper.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationPrefix.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationSuffix.tsx
  src/navsections/KustomizePatchSectionBlueprint/KustomizePatchPrefix.tsx
  src/navsections/KustomizePatchSectionBlueprint/KustomizePatchSuffix.tsx
  src/redux/reducers/ui.ts
Labels: size/XL

#2145 fix: spacing in compare-sync.md
  docs/compare-sync.md
Labels: size/L

#2148 [Snyk] Upgrade vm2 from 3.9.9 to 3.9.10
  package-lock.json
  package.json
Labels: size/XS

#2149 Erdikose/feat/show age status
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/useItemCustomization.ts
  src/models/navigator.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindInformation.styled.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindInformation.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
  src/navsections/UnknownResourceSectionBlueprint/UnknownResourceSectionBlueprint.ts
Labels: size/M

#2151 refactor: rename WalkThrough to Walkthrough
  src/App.tsx
  src/components/molecules/Walkthrough/Walkthrough.tsx
  src/components/molecules/Walkthrough/content/newReleaseFeatures.ts
  src/components/molecules/Walkthrough/content/novice.ts
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/models/walkthrough.ts
  src/redux/reducers/ui.ts
Labels: size/M

#2153 feat: new feedback tooltip text
  src/constants/tooltips.tsx
Labels: size/XS

#2150 feat: multiple terminals
  electron/app/ipc/ipcListeners.ts
  package-lock.json
  src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/TerminalPane/TerminalPane.styled.tsx
  src/components/organisms/TerminalPane/TerminalPane.tsx
  src/constants/tooltips.tsx
  src/models/terminal.ts
  src/redux/initialState.ts
  src/redux/reducers/terminal.ts
Labels: size/L

#2144 Julia/feat/logs for pods
  src/components/atoms/TabHeader/TabHeader.tsx
  src/components/molecules/Logs/Logs.styled.ts
  src/components/molecules/Logs/Logs.tsx
  src/components/molecules/Logs/index.tsx
  src/components/molecules/index.ts
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/redux/services/manifest-utils.ts
Labels: size/L

#2154 feat: add image selection placeholder
  src/components/molecules/FormEditor/FormWidgets/ImageSelection.tsx
Labels: size/XS

#2155 fix: warning
  src/navsections/K8sResourceSectionBlueprint/ResourceKindInformation.styled.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindInformation.tsx
Labels: size/XS

#2156 chore: update package-lock
  package-lock.json
Labels: size/XS
