Repository kubeshop/monokle, pull requests merged in 2023-05, with the labels that each got.

#3830 fix: glitches related to cluster-resource updates and cluster-mode
  src/editor/listeners/editorSelection.listener.ts
  src/editor/listeners/editorTextUpdate.listener.ts
  src/redux/services/clusterResourceWatcher.ts
  src/redux/thunks/utils.ts
Labels: size/S

#3828 fix: connect to default namespace when nonexistence namespace
  src/redux/cluster/thunks/connect.ts
  src/redux/thunks/cluster/loadClusterResources.ts
Labels: size/S

#3832 fix: skip checking all namespaces existence
  src/redux/cluster/thunks/connect.ts
  src/redux/thunks/cluster/loadClusterResources.ts
Labels: size/S

#3833 fix: update electron menu typescript
  src/shared/models/rootState.ts
  src/shared/utils/selectors.ts
Labels: size/S

#3838 fix: prioritize connecting to last namespace
  src/components/organisms/PageHeader/ClusterControl/Buttons.tsx
  src/redux/cluster/thunks/connect.ts
Labels: size/S

#3827 fix: load custom resource items in dashboard
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/kindhandlers/CustomResourceDefinition.handler.ts
Labels: size/M

#3844 fix: check values file if it is associated with a Helm Chart
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
Labels: size/XS

#3841 Small fixes and changes
  electron/app/menu.ts
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/organisms/AboutModal/AboutModal.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/editor/editor.utils.ts
  src/editor/enhancers/k8sResource/symbols.ts
Labels: size/L

#3846 fix: cluster validation
  src/components/organisms/ValidationPane/ValidationPane.tsx
  src/redux/reducers/main/mainSlice.ts
Labels: size/S

#3847 refactor: show logs error if any
  src/components/molecules/Logs/Logs.styled.ts
  src/components/molecules/Logs/Logs.tsx
  src/components/organisms/NavigatorPane/ResourceNavigator.tsx
Labels: size/S

#3849 Update CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#3851 refactor: tooltip_delay
  src/components/molecules/ResourcePopover/ResourcePopover.tsx
Labels: size/XS

#3856 fix handling of worker events
  electron/app/ipc/ipcMainRedux.ts
  electron/app/utils/promises.ts
  src/redux/parsing/parser.thunks.ts
  src/redux/thunks/cluster/loadClusterResources.ts
  src/redux/validation/validation.thunks.ts
  src/shared/utils/promises.ts
  src/utils/promises.ts
  src/utils/worker.ts
Labels: size/L

#3858 fix: <all> namespace cluster resources
  src/redux/thunks/cluster/loadClusterResources.ts
Labels: size/XS

#3860 fix: show name of overlay folder instead of filename in navigator
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeList.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx
  src/redux/selectors/kustomizeSelectors.ts
Labels: size/XS

#3861 fix: add menu divider
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
Labels: size/L

#3854 fix: check folder existence before opening it
  src/redux/appConfig/appConfig.slice.ts
Labels: size/XS

#3853 fix: reset validation count when switching projects
  src/redux/validation/validation.slice.ts
Labels: size/XS

#3868 fix: reset validation counts
  src/redux/validation/validation.slice.ts
Labels: size/XS

#3866 fix: remove parsedDoc cache and improve handling of timestamp in files
  src/redux/services/resource.ts
  src/redux/thunks/utils.ts
Labels: size/M

#3869 refactor: log unknown cluster error reason
  electron/app/services/cluster/handlers/setup.ts
  src/index.tsx
Labels: size/S

#3867 feat: download progress bar
  src/assets/NoDataFound.svg
  src/components/organisms/Dashboard/Tableview/NoResourcesFound.tsx
  src/components/organisms/Dashboard/Tableview/Tableview.tsx
  src/components/organisms/DashboardPane/DashboardFilteredMenu.tsx
  src/components/organisms/DashboardPane/MenuItem.tsx
  src/components/organisms/PageHeader/DownloadProgress.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
Labels: size/L

#3863 fix: pass files to refs parser
  src/redux/parsing/parser.thunks.ts
  src/redux/parsing/parser.worker.ts
  src/redux/parsing/parser.worker.types.ts
  src/redux/validation/validation.thunks.ts
Labels: size/M

#3874 fix: create monokle new window
  electron/app/menu.ts
Labels: size/XS

#3876 fix: mark unresolved optional-links as warnings for now
  src/redux/validation/validation.thunks.ts
Labels: size/XS

#3875 fix: show latest 100 events on dashboard
  src/components/organisms/Dashboard/Overview/Activity.styled.tsx
  src/components/organisms/Dashboard/Overview/Activity.tsx
Labels: size/L

#3883 refactor: allotment resizable library
  package-lock.json
  package.json
  patches/react-reflex+4.0.9.patch
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/TerminalPane/TerminalPane.tsx
  src/index.tsx
Labels: size/L

#3887 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#3888 fix: removed unused settings
  src/components/organisms/SettingsPane/Settings/Settings.tsx
  src/redux/initialState.ts
  src/redux/services/projectConfig.ts
  src/shared/models/config.ts
Labels: size/M

#3889 fix: new version notice
  electron/app/autoUpdater.ts
  src/components/molecules/NewVersionNotice/NewVersionNotice.tsx
Labels: size/S

#3892 fix: keep transient resources on reload
  src/components/organisms/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
  src/components/organisms/ExplorerPane/FilePane/useSetFolderFromMainThread.ts
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeContextMenu.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/SettingsPane/Settings/Settings.tsx
  src/redux/appConfig/appConfig.slice.ts
  src/redux/reducers/main/mainSlice.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/M

#3891 refactor: get default kubeconfig
  electron/app/services/cluster/utils/getDefaultKubeConfig.ts
Labels: size/XS

#3890 fix: closable explorer left pane only
  src/components/organisms/PaneManager/PaneManager.tsx
Labels: size/XS

#3893 fix: added/fixed a bunch of telemetry events
  src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/CreateFileFolderModal/CreateFileFolderModal.tsx
  src/components/organisms/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImageRenderer/ImageRenderer.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationRenderer.tsx
  src/components/organisms/NavigatorPane/KindRenderer/KindRenderer.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/NavigatorPane/ResourceRenderer/ResourceRenderer.tsx
  src/components/organisms/PageHeader/ClusterControl/NamespaceSelect.tsx
  src/components/organisms/PageHeader/K8sVersionSelection.tsx
  src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
  src/components/organisms/SettingsPane/Settings/Settings.tsx
  src/components/organisms/ValidationPane/ValidationPane.tsx
  src/components/organisms/ValidationSettings/CRDsSchemaValidation/CRDsSchemaValidation.tsx
  src/components/organisms/ValidationSettings/ValidationOpenPolicyAgent/ValidationOpenPolicyAgent.tsx
  src/components/organisms/ValidationSettings/ValidationOpenPolicyAgent/useOpenPolicyAgentTable.tsx
  src/components/organisms/ValidationSettings/ValidationOverview/ValidationCard.tsx
  src/hooks/menuItemsHooks/useNewTerminalMenuItems.tsx
  src/shared/models/telemetry.ts
Labels: size/L

#3896 refactor: pane manager
  package-lock.json
  package.json
  src/components/molecules/ClosedPanePlaceholder/ClosedPanePlaceholder.tsx
  src/components/molecules/ClosedPanePlaceholder/index.ts
  src/components/molecules/index.ts
  src/components/organisms/BottomPaneManager/BottomPaneManager.styled.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/constants/constants.ts
  src/shared/constants/constants.ts
  src/shared/models/ui.ts
Labels: size/M

#3894 fix: updated to latest Kustomize schema and enable helm by default
  resources/schemas/kustomization.json
  src/shared/constants/electronStore.ts
Labels: size/XL

#3897 fix: showing closed pane placeholder
  src/components/organisms/PaneManager/PaneManager.tsx
Labels: size/S

#3898 refactor: throttling incremental validation
  src/redux/validation/validation.listeners.tsx
Labels: size/M

#3899 fix: resizable bottom terminal
  package-lock.json
  package.json
  src/components/organisms/PaneManager/PaneManager.tsx
Labels: size/S

#3900 fix: reset collapsedResourceKinds on previews
  src/redux/reducers/ui.ts
Labels: size/S

#3882 refactor: use new editor in cluster dashboard
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/EditorTab.styled.tsx
  src/components/organisms/Dashboard/Tableview/EditorTab.tsx
  src/editor/CodeEditor/CodeEditor.tsx
  src/editor/editor.constants.ts
  src/editor/editor.instance.ts
  src/editor/editor.types.ts
  src/editor/enhancers/k8sResource/refs.ts
  src/editor/enhancers/k8sResource/symbols.ts
  src/editor/listeners/editorSelection.listener.ts
Labels: size/L

#3881 fix: filter out resources that should not be sent to validation core
  src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx
  src/redux/selectors/fileMapGetters.ts
  src/redux/selectors/resourceMapGetters.ts
  src/redux/services/resource.ts
  src/redux/thunks/replaceImageTag.ts
  src/redux/validation/validation.thunks.ts
Labels: size/L

#3902 fix: added more telemetry to app start panels
  electron/app/ipc/ipcListeners.ts
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/ProjectCard/ProjectCard.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/GitCloneModal/GitCloneModal.tsx
  src/components/organisms/LearnPage/LearnPage.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/StartPage/StartPage.tsx
  src/editor/enhancers/k8sResource/refs.ts
  src/shared/models/telemetry.ts
Labels: size/M

#3905 fix: show cluster connection error description
  electron/app/services/cluster/handlers/debugProxy.ts
  electron/kubernetes/ProxyInstance.ts
Labels: size/XS

#3901 chore: remove unused code
  src/components/organisms/Dashboard/Tableview/InfoTab.tsx
  src/hooks/menuItemsHooks/index.ts
  src/hooks/menuItemsHooks/useRefDropdownMenuItems.tsx
Labels: size/L

#3909 fix: remove use kubectl proxy option
  src/components/organisms/SettingsPane/GlobalSettings/GlobalSettings.tsx
  src/redux/appConfig/appConfig.slice.ts
  src/redux/initialState.ts
  src/shared/models/config.ts
Labels: size/S

#3906 fix: hotkeys
  electron/app/menu.ts
  package-lock.json
  package.json
  src/components/atoms/HotkeyLabel/HotkeyLabel.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/KeyboardShortcuts/BoardKeys/BoardKeys.tsx
  src/components/organisms/KeyboardShortcuts/KeyboardShortcuts.tsx
  src/constants/tooltips.tsx
  src/shared/constants/hotkeys.ts
  src/shared/models/rootState.ts
  src/shared/utils/hotkey.ts
Labels: size/L

#3907 chore: add telemetry for code changes
  src/editor/CodeEditor/CodeEditor.tsx
  src/editor/editor.instance.ts
  src/editor/editor.slice.ts
  src/shared/models/telemetry.ts
Labels: size/S

#3911 refactor: center scroll
  src/components/organisms/DashboardPane/DashboardFilteredMenu.tsx
Labels: size/XS

#3910 fix: rendering of kustomization name when in root folder
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx
Labels: size/XS

#3913 refactor: remove New File/Folder from file context menu
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
Labels: size/S

#3912 chore: 2.1 release notes
  resources/releaseNotes/2.1/2.1.json
  resources/releaseNotes/2.1/2.1.md
  resources/releaseNotes/2.1/2.1.svg
Labels: size/L

#3918 refactor: show "Preview" without hovering
  src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.styled.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.styled.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.styled.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationRenderer.tsx
Labels: size/L

#3923 chore(release): 2.1.0
  CHANGELOG.md
Labels: size/S

#3927 fix: improve telemetry of cluster dashboard
  src/components/organisms/Dashboard/Overview/Activity.tsx
  src/components/organisms/Dashboard/Overview/Overview.tsx
  src/components/organisms/Dashboard/Overview/Status.tsx
  src/shared/models/telemetry.ts
Labels: size/S

#3929 refactor: separator border color
  src/index.css
Labels: size/XS

#3940 fix: don't ask for permission on windows installer
  package.json
Labels: size/S

#3941 fix: bring back differentialPackage
  package.json
Labels: size/XS

#3942 fix: tracking event when clicking on the same option currently selected
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
Labels: size/S

#3939 chore: fix local builds
  craco.config.js
Labels: size/S

#3945 fix: excluded files
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
  src/redux/services/fileEntry.ts
Labels: size/M

#3947 fix: extract resources only for files not excluded
  src/components/atoms/FilePatternList/FilePatternList.tsx
  src/components/organisms/SettingsPane/Settings/Settings.tsx
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
Labels: size/M

#3952 fix: catch crd dir exists error
  src/utils/crds.ts
Labels: size/S

#3951 chore: update vm2
  electron/app/ipc/ipcListeners.ts
  package-lock.json
  package.json
  src/components/organisms/NavigatorPane/KindRenderer/ResourceCounter.tsx
  src/redux/reducers/main/previewReducers.ts
  src/redux/services/preview.ts
  src/redux/services/selection.ts
Labels: size/M

#3946 refactor: new project start page
  src/assets/newProject/ClusterLive.svg
  src/assets/newProject/FromFolder.svg
  src/assets/newProject/FromGit.svg
  src/assets/newProject/FromSampleProject.svg
  src/assets/newProject/FromScratch.svg
  src/assets/newProject/FromTemplate.svg
  src/components/organisms/GitCloneModal/GitCloneModal.tsx
  src/components/organisms/NewProject/NewProject.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/StartPage/StartPage.tsx
  src/components/organisms/StartPage/StartPageHeader.tsx
  src/redux/git/git.slice.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/models/git.ts
  src/shared/models/ui.ts
  src/shared/styles/colors.ts
Labels: size/L

#3956 fix: kubeconfig path browse loading
  src/components/organisms/SettingsPane/Settings/Settings.tsx
Labels: size/M

#3955 fix: improve dashboard telemetry and main thread logging
  electron/app/commands.ts
  electron/app/extensions/downloadExtension.ts
  electron/app/extensions/downloadExtensionEntry.ts
  electron/app/extensions/loadExtension.ts
  electron/app/index.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/openApplication.ts
  electron/app/services/cluster/daemons/kubeconfigWatcher.ts
  electron/app/services/cluster/handlers/setup.ts
  electron/app/services/pluginService.ts
  electron/app/services/templateService.ts
  electron/app/utils.ts
  electron/app/utils/ipc.ts
  electron/kubernetes/ProxyInstance.ts
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/ErrorCell.tsx
  src/components/organisms/Dashboard/Tableview/InfoTab.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.tsx
  src/components/organisms/Dashboard/Tableview/Tableview.tsx
  src/components/organisms/PageHeader/ClusterControl/NamespaceSelect.tsx
  src/redux/dashboard/slice.ts
  src/redux/thunks/cluster/loadClusterResources.ts
  src/shared/models/dashboard.ts
  src/shared/models/telemetry.ts
Labels: size/M

#3957 fix: keep leftMenuActive status when changing options
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
Labels: size/S

#3969 Update README.md
  README.md
Labels: size/XS

#3970 refactor: add back dark mode logo
  README.md
Labels: size/XS

#3974 fix: validation when remove resource
  src/redux/validation/validation.listeners.tsx
Labels: size/XS

#3976 fix: kustomize name in compare dropdown
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx
  src/components/organisms/ResourceSetSelector/KustomizeSelect.tsx
  src/utils/kustomize.ts
Labels: size/S

#3978 chore: update dependencies
  notarization/afterSignHook.js
  package-lock.json
  package.json
  patches/webpack-dev-server+4.15.0.patch
Labels: size/L

#3973 fix: switching projects in cluster mode
  src/redux/cluster/thunks/connect.ts
  src/redux/parsing/parser.thunks.ts
  src/redux/parsing/resourceParser.ts
  src/redux/reducers/main/mainSlice.ts
  src/redux/thunks/setRootFolder.ts
  src/redux/validation/validation.listeners.tsx
  src/redux/validation/validation.thunks.ts
Labels: size/M

#3980 feat: match cluster namespace with the graph filter namespace
  package-lock.json
  package.json
  src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx
Labels: size/S

#3979 feat: cluster resource actions
  package-lock.json
  package.json
  src/components/atoms/StyledComponents/SecondaryButton.tsx
  src/components/organisms/ActionsPane/Restart/Restart.tsx
  src/components/organisms/ActionsPane/Scale/Scale.tsx
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.styled.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/InfoTab.styled.tsx
  src/components/organisms/Dashboard/Tableview/ResourceActions.tsx
  src/components/organisms/Dashboard/Tableview/ResourceActionsDropdown.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.tsx
  src/components/organisms/Dashboard/Tableview/Tableview.styled.tsx
  src/components/organisms/Dashboard/Tableview/utils.tsx
  src/components/organisms/GlobalModals/GlobalModals.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/NavigatorPane/ResourceRenderer/ResourceContextMenu.tsx
  src/components/organisms/ScaleModal/ScaleModal.tsx
  src/components/organisms/ScaleModal/index.ts
  src/components/organisms/index.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/models/telemetry.ts
  src/shared/models/ui.ts
Labels: size/XL

#3985 fix: add modal confirms when transferring in compare
  src/components/organisms/CompareSyncPane/CompareSyncPane.tsx
  src/components/organisms/CompareSyncPane/ComparisonList/ComparisonList.tsx
  src/components/organisms/CompareSyncPane/InspectionActionBar/InspectionActionBar.styled.tsx
  src/components/organisms/CompareSyncPane/TransferButton/TransferButton.tsx
Labels: size/M

#3981 style: UI rework validation tab
  src/components/organisms/ValidationSettings/ValidationOverview/ValidationCard.styled.tsx
  src/components/organisms/ValidationSettings/ValidationOverview/ValidationCardUpNext.styled.tsx
  src/components/organisms/ValidationSettings/ValidationSettings.styled.tsx
  src/components/organisms/ValidationSettings/ValidationSettings.tsx
  src/shared/styles/device.ts
Labels: size/M

#3991 fix: show k8s version in cluster mode
  src/components/organisms/Dashboard/Overview/InventoryInfo.tsx
Labels: size/M

#3990 fix: on selecting a file, expand tree accordingly
  src/components/organisms/ExplorerPane/HelmPane/HelmContextMenu.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeContextMenu.tsx
  src/redux/reducers/ui.ts
  src/shared/utils/file.ts
  src/shared/utils/index.ts
Labels: size/M

#3989 feat: added Update Dependencies command to Helm Chart navigator item
  src/components/organisms/ExplorerPane/HelmPane/HelmContextMenu.tsx
  src/components/organisms/ValidationSettings/ValidationOverview/ValidationCard.styled.tsx
  src/components/organisms/ValidationSettings/ValidationOverview/ValidationCardUpNext.styled.tsx
  src/components/organisms/ValidationSettings/ValidationSettings.styled.tsx
  src/components/organisms/ValidationSettings/ValidationSettings.tsx
  src/redux/reducers/main/previewReducers.ts
  src/redux/reducers/ui.ts
  src/redux/services/preview.ts
  src/redux/thunks/previewCommand.ts
  src/redux/thunks/runHelmCommand.ts
  src/redux/validation/validation.listeners.tsx
  src/shared/models/telemetry.ts
Labels: size/L

#3993 refactor: logs
  src/components/molecules/Logs/Logs.styled.ts
  src/components/molecules/Logs/Logs.tsx
  src/components/organisms/Dashboard/Tableview/TerminalTab.styled.tsx
  src/shared/models/dashboard.ts
Labels: size/L

#3994 fix: added select_project telemetry and improved project filtering on…
  src/components/organisms/StartPage/StartPageHeader.tsx
  src/shared/models/telemetry.ts
Labels: size/XS

#4001 fix: saving code changes on helm values files
  src/editor/CodeEditor/handleCodeChanges.ts
Labels: size/XS

#4000 Quick search projects
  src/assets/figures/thunderIcon.svg
  src/components/molecules/ProjectCard/ProjectCard.styled.tsx
  src/components/molecules/ProjectCard/ProjectCard.tsx
  src/components/molecules/ProjectsList/ProjectsList.styled.tsx
  src/components/molecules/ProjectsList/ProjectsList.tsx
Labels: size/L

#4004 fix: avoid reset form tab
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/S

#4005 fix: preview helm configuration
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationRenderer.styled.tsx
  src/utils/helm.ts
Labels: size/XS

#3992 feat: add graph view in cluster dashboard
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/GraphTab.tsx
  src/shared/models/dashboard.ts
Labels: size/M

#4009 fix: reset actions tab when changing file
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/S

#3972 feat: Generate resources using AI
  package-lock.json
  package.json
  src/assets/AIRobot.svg
  src/assets/AIRobotColored.svg
  src/components/molecules/AIGenerationModal/AIGenerationModal.styled.tsx
  src/components/molecules/AIGenerationModal/AIGenerationModal.tsx
  src/components/molecules/AIGenerationModal/ApiKeyModal.tsx
  src/components/molecules/AIGenerationModal/ai.client.ts
  src/components/molecules/AIGenerationModal/ai.completion.ts
  src/components/molecules/AIGenerationModal/ai.prompt.ts
  src/components/molecules/AIGenerationModal/constants.ts
  src/components/molecules/AIGenerationModal/index.ts
  src/components/molecules/AIGenerationModal/utils.ts
  src/components/organisms/GlobalModals/GlobalModals.tsx
  src/hooks/menuItemsHooks/useNewResourceMenuItems.tsx
  src/redux/appConfig/appConfig.slice.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/constants/electronStore.ts
  src/shared/models/config.ts
  src/shared/models/ui.ts
  src/utils/objects.ts
Labels: size/XL

#4012 chore: add telemetry for AI modal
  src/components/molecules/AIGenerationModal/AIGenerationModal.tsx
  src/components/molecules/AIGenerationModal/ai.prompt.ts
  src/redux/reducers/ui.ts
  src/shared/models/telemetry.ts
Labels: size/M

#4014 fix: preview configuration multiple fixes
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationQuickAction.tsx
  src/redux/thunks/previewConfiguration.ts
Labels: size/M

#3948 refactor: is hovered renderers + change preview to dry-run
  src/components/molecules/QuickActionCompare/QuickActionCompare.styled.tsx
  src/components/molecules/QuickActionPreview/QuickActionPreview.styled.tsx
  src/components/molecules/QuickActionPreview/QuickActionPreview.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNode.styled.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFile.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.styled.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImageFilteredTag.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.styled.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx
  src/components/organisms/PageHeader/PreviewControl/PreviewLabel.tsx
  src/redux/ipcRendererRedux.ts
  src/redux/reducers/main/selectors.ts
Labels: size/L

#4016 fix: validation listeren when starting a preview + make thunks
  src/components/molecules/CommandPreview/PreviewSavedCommand.tsx
  src/components/molecules/QuickActionPreview/QuickActionPreview.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/Dashboard/Tableview/ErrorCell.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueQuickAction.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeQuickAction.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationQuickAction.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/PreviewControl/ExitButton.tsx
  src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
  src/hooks/fileTreeHooks/useFileSelect.tsx
  src/hooks/fileTreeHooks/usePreview.tsx
  src/redux/reducers/main/previewReducers.ts
  src/redux/reducers/ui.ts
  src/redux/services/compare/fetchResources.ts
  src/redux/services/preview.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/preview/deletePreviewConfiguration.ts
  src/redux/thunks/preview/index.ts
  src/redux/thunks/preview/previewHelmValuesFile.ts
  src/redux/thunks/preview/previewKustomization.ts
  src/redux/thunks/preview/previewSavedCommand.ts
  src/redux/thunks/preview/restartPreview.ts
  src/redux/thunks/preview/startPreview.ts
  src/redux/thunks/preview/stopPreview.ts
  src/redux/validation/validation.listeners.tsx
  src/utils/restartEditorPreview.ts
Labels: size/L

#4015 Excessive space accordion
  src/components/organisms/ExplorerPane/AccordionPanel/AccordionPanel.tsx
  src/components/organisms/ExplorerPane/ExplorerPane.tsx
  src/components/organisms/ExplorerPane/FilePane/FilePane.styled.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmList.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImagesPane.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeList.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationList.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationPane.tsx
Labels: size/S

#4017 fix: support for identifying child/parent charts
  src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.tsx
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
  src/shared/models/helm.ts
Labels: size/M
