Repository kubeshop/monokle, pull requests merged in 2023-07, with the labels that each got.

#4113 chore: remove unused code
  src/redux/validation/validation.thunks.ts
  src/utils/fluxStandardAction.ts
  src/utils/hooks.ts
  src/utils/resources.ts
  src/utils/sleep.ts
  src/utils/workerify.ts
Labels: size/L

#4115 chore: release notes for 2.3
  resources/releaseNotes/2.3/2.3.json
  resources/releaseNotes/2.3/2.3.md
  resources/releaseNotes/2.3/2.3.svg
Labels: size/L

#4117 chore(release): 2.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS

#4123 fix: prevent dispatch to destroyed window
  electron/app/ipc/ipcMainRedux.ts
Labels: size/XS

#4124 fix: segment error handler
  src/shared/utils/segment.ts
Labels: size/XS

#4125 fix: read file safely
  electron/app/utils/git.ts
Labels: size/XS

#4127 Olelensmar/fix/newsfeed ordering and telemetry
  src/components/organisms/StartPage/StartPage.tsx
  src/components/organisms/StartPage/useNewsFeed.ts
  src/shared/models/telemetry.ts
Labels: size/S

#4121 fix: validate incremental telemetry
  src/redux/validation/validation.listeners.tsx
Labels: size/S

#4129 chore: console function for machine id
  src/index.tsx
Labels: size/XS

#4130 chore(release): 2.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#4131 fix: skip noisy errors from sentry
  src/redux/appConfig/appConfig.slice.ts
  src/shared/constants/sentry.ts
Labels: size/S

#4134 Cluster Proxy improvements
  electron/app/ipc/ipcListeners.ts
  electron/app/kubectl.ts
  electron/kubernetes/ProxyInstance.ts
  package-lock.json
  package.json
  src/components/organisms/ProblemPane/ProblemPane.tsx
  src/components/organisms/SettingsPane/GlobalSettings/GlobalSettings.tsx
  src/components/organisms/SettingsPane/Settings/Settings.tsx
  src/redux/services/clusterDashboard.ts
  src/redux/thunks/cluster/stopClusterConnection.ts
  src/shared/constants/electronStore.ts
  src/shared/utils/commands/kubectl.ts
Labels: size/L

#4135 chore(release): 2.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#4141 refactor: build test action
  .github/workflows/monokle-publish-test.yml
Labels: size/XS

#4137 fix: project summary overview
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ActionsPane/ProjectOverview/ProjectOverview.tsx
  src/components/organisms/ActionsPane/ProjectOverview/index.ts
  src/components/organisms/ActionsPane/ProjectOverview/styled.tsx
  src/redux/selectors.tsx
  src/shared/models/telemetry.ts
Labels: size/L

#4133 fix: cluster left menu
  package-lock.json
  package.json
  src/components/organisms/PageHeader/ClusterControl/ContextSelect.tsx
  src/components/organisms/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms/PaneManager/activities.tsx
  src/shared/models/ui.ts
Labels: size/M

#4143 fix: ENV kubeconfig with multiple files
  electron/app/services/cluster/ipc.ts
  electron/app/services/cluster/utils/getDefaultKubeConfig.ts
  src/redux/cluster/listeners/kubeconfig.ts
  src/redux/cluster/selectors.ts
  src/redux/cluster/service/kube-control.ts
Labels: size/M

#4140 fix helm cluster arguments
  electron/app/services/cluster/handlers/debugProxy.ts
  electron/app/services/cluster/ipc.ts
  electron/kubernetes/ProxyService.ts
  src/components/organisms/Dashboard/HelmReleaseDetails/HelmReleaseTabs/HelmReleaseHooks.tsx
  src/components/organisms/Dashboard/HelmReleaseDetails/HelmReleaseTabs/HelmReleaseManifest.tsx
  src/components/organisms/Dashboard/HelmReleaseDetails/HelmReleaseTabs/HelmReleaseNotes.tsx
  src/components/organisms/Dashboard/HelmReleaseDetails/HelmReleaseTabs/HelmReleaseValues.tsx
  src/components/organisms/Dashboard/HelmReleaseDetails/HelmReleaseTabs/HelmRevisionsTable.tsx
  src/components/organisms/Dashboard/HelmReleaseDetails/SelectedHelmReleaseDetails.tsx
  src/components/organisms/Dashboard/HelmReleaseDetails/UpgradeHelmReleaseModal.tsx
  src/components/organisms/HelmRepoPane/HelmChartDetails/HelmChartDetails.tsx
  src/components/organisms/HelmRepoPane/HelmChartDetails/HelmChartTabs/HelmTemplate.tsx
  src/components/organisms/HelmRepoPane/HelmChartDetails/HelmChartTabs/HelmValues.tsx
  src/components/organisms/HelmRepoPane/HelmChartsView.tsx
  src/components/organisms/HelmRepoPane/HelmReposView.tsx
  src/hooks/useGetHelmChartChangelog.ts
  src/hooks/useGetHelmChartInfo.ts
  src/hooks/useSearchHelmCharts.ts
  src/redux/appConfig/appConfig.slice.ts
  src/redux/cluster/getters.ts
  src/redux/cluster/listeners/clusterArgsChanged.ts
  src/redux/cluster/listeners/index.ts
  src/redux/cluster/service/kube-control.ts
  src/redux/services/compare/fetchResources.ts
  src/redux/thunks/InstallHelmRepoChart.ts
  src/redux/thunks/cluster/loadClusterHelmReleases.ts
  src/redux/thunks/cluster/stopClusterConnection.ts
  src/redux/thunks/pullHelmChart.ts
  src/shared/models/commands.ts
  src/shared/models/config.ts
  src/shared/utils/commands/helm.ts
  src/shared/utils/commands/index.ts
  src/utils/cluster.ts
  src/utils/helm.ts
Labels: size/XL

#4147 chore: improved production debugging
  src/redux/store.ts
  src/utils/helm.ts
  src/utils/ipc.ts
Labels: size/L

#4148 fix: helm kubeconfig argument
  src/components/organisms/HelmRepoPane/HelmChartsView.tsx
  src/redux/cluster/getters.ts
  src/redux/cluster/listeners/clusterArgsChanged.ts
  src/utils/cluster.ts
Labels: size/M

#4149 chore(release): 2.3.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#4150 chore: improve compare telemetry
  src/redux/compare/slice.ts
  src/shared/models/telemetry.ts
Labels: size/XS

#4155 minor fixes and improvements
  package-lock.json
  package.json
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationAdd.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationPane.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationRenderer.styled.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/PaneManager/activities.tsx
  src/components/organisms/StartPage/StartPage.tsx
  src/redux/reducers/main/mainSlice.ts
Labels: size/M

#4156 feat: install action for helm configurations
  src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/constants/tooltips.tsx
  src/redux/reducers/main/previewReducers.ts
  src/redux/reducers/ui.ts
  src/redux/services/compare/fetchResources.ts
  src/redux/thunks/preview/startPreview.ts
  src/redux/thunks/runPreviewConfiguration.ts
  src/redux/validation/validation.listeners.tsx
  src/shared/models/commands.ts
  src/shared/models/telemetry.ts
  src/utils/helm.ts
Labels: size/L

#4158 chore(release): 2.3.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S
