Repository kubeshop/monokle, pull requests merged in 2023-10, with the labels that each got.

#4179 chore(release): 2.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/M

#4180 docs: remove conflict marker and fixed the incorrect edit link editor
  docs/docs/cluster-issues.md
  docs/docusaurus.config.js
  docs/package-lock.json
Labels: size/S

#4182 Olelensmar/feat/vap handlers
  package.json
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/editor/listeners/editorSelection.listener.ts
  src/kindhandlers/ValidatingAdmissionPolicy.handler.ts
  src/kindhandlers/ValidatingAdmissionPolicyBinding.handler.ts
  src/kindhandlers/index.ts
  src/shared/constants/k8s.ts
Labels: size/L

#4183 update electron deps, remove old CLI & fix selection bug
  .npmrc
  .nvmrc
  cli/terminal.ts
  electron/app/index.ts
  package-lock.json
  package.json
  resources/icon.png
  src/components/organisms/ExplorerPane/DryRunsPane/usePreviewTrigger.tsx
  src/redux/reducers/main/clusterReducers.ts
  src/redux/reducers/main/mainSlice.ts
  src/redux/reducers/main/previewReducers.ts
  src/redux/reducers/main/selectionReducers.ts
Labels: size/L

#4185 chore(release): 2.4.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#4186 refactor: update validation package
  package-lock.json
  package.json
  src/redux/validation/validation.loader.ts
  src/redux/validation/validation.worker.ts
  src/redux/validation/validator.ts
Labels: size/M

#4187 add setting for binary configuration & fix kubectl path splitting
  electron/app/services/cluster/utils/getDefaultKubeConfig.ts
  src/components/organisms/SettingsPane/GlobalSettings/GlobalSettings.tsx
  src/redux/cluster/selectors.ts
  src/shared/constants/electronStore.ts
  src/shared/utils/commands/execute.ts
Labels: size/M

#4188 fix: updated description and synopsis
  package.json
Labels: size/XS

#4190 Setting to disable cluster validation & added table pagination
  src/components/organisms/Dashboard/TableView/TableView.tsx
  src/components/organisms/SettingsPane/GlobalSettings/GlobalSettings.tsx
  src/redux/validation/validation.listeners.tsx
  src/shared/constants/electronStore.ts
Labels: size/M
