Repository kubeshop/monokle, pull requests merged in 2023-02, with the labels that each got.

#3059 refactor: update navigator title
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
Labels: size/XS

#3060 refactor: default k8s version change
  src/components/organisms/PageHeader/K8sVersionSelection.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
Labels: size/S

#3070 fix: update LearnPage component
  package-lock.json
  package.json
  src/components/organisms_new/LearnPage/LearnPage.tsx
  src/components/organisms_new/LearnPage/WalkThroughModal.tsx
  src/components/organisms_new/LearnPage/index.ts
  src/components/organisms_new/StartPage/StartPage.tsx
  src/components/organisms_new/index.ts
  src/hooks/useStartPageOptions.tsx
  src/redux/reducers/ui.ts
  src/shared/constants/walkthrough.ts
  src/shared/models/ui.ts
Labels: size/L

#3090 Remove unnecessary file reads
  electron/app/utils/git.ts
  src/redux/reducers/main/mainSlice.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
  src/redux/thunks/updateFileEntry.ts
  src/shared/models/fileEntry.ts
  src/utils/filterQuery.ts
  src/utils/replaceInFiles.ts
Labels: size/L

#3094 fix use namespaces
  src/hooks/useNamespaces.ts
Labels: size/XS

#3098 feat: sarif viewer
  package-lock.json
  package.json
  src/components/organisms/GitPane/GitPane.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PageHeader/K8sVersionSelection.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms_new/PaneManager/PaneManager.tsx
  src/components/organisms_new/ProblemPane/ProblemPane.styled.tsx
  src/components/organisms_new/ProblemPane/ProblemPane.tsx
  src/components/organisms_new/ProblemPane/index.ts
  src/components/organisms_new/ValidationPane/ValidationPane.tsx
  src/components/organisms_new/index.ts
  src/constants/tooltips.tsx
  src/hooks/fileTreeHooks/useHighlightNode.ts
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenuWrapper.tsx
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionEmptyDisplay.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenu.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenuWrapper.tsx
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/ui.ts
  src/redux/validation/validation.listeners.ts
  src/redux/validation/validation.listeners.tsx
  src/redux/validation/validation.slice.ts
  src/redux/validation/validation.thunks.ts
  src/shared/constants/electronStore.ts
  src/shared/constants/hotkeys.ts
  src/shared/constants/k8s.ts
  src/shared/models/ui.ts
  src/shared/styles/colors.ts
Labels: size/L

#3101 Razvantopliceanu/fix/errors
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms_new/PaneManager/activities.tsx
  src/redux/initialState.ts
  src/redux/reducers/main/imageListeners.ts
  src/redux/reducers/ui.ts
  src/redux/validation/validation.listeners.tsx
  src/shared/models/ui.ts
Labels: size/M

#3104 feat: title bar errors warnings + opa chip count
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/NavigatorPane/NavigatorTitle.styled.tsx
  src/components/organisms/NavigatorPane/NavigatorTitle.tsx
  src/components/organisms/NavigatorPane/WarningAndErrorsDisplay.styled.tsx
  src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
  src/components/organisms/PageHeader/OPAChip.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
  src/hooks/menuItemsHooks/useRefDropdownMenuItems.tsx
  src/redux/validation/validation.slice.ts
Labels: size/L

#3068 Update README.md
  README.md
Labels: size/S

#3106 refactor: remove file search matches logic
  src/components/molecules/Monaco/CodeIntel/fileWithMatchesIntel.ts
  src/components/molecules/Monaco/CodeIntel/index.ts
  src/components/molecules/Monaco/CodeIntel/types.ts
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/useCodeIntel.ts
  src/components/organisms/FileTreePane/types.tsx
  src/components/organisms_new/ExplorerPane/FilePane/types.tsx
  src/redux/initialState.ts
  src/redux/reducers/main/mainSlice.ts
  src/shared/models/appState.ts
  src/shared/models/fileEntry.ts
Labels: size/L

#3108 feat: errors warnings dropdown
  package-lock.json
  package.json
  src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
  src/components/molecules/ValidationErrorsPopover/ErrorsPopoverContent.styled.tsx
  src/components/molecules/ValidationErrorsPopover/ErrorsPopoverContent.tsx
  src/components/molecules/ValidationErrorsPopover/ValidationErrorLink.styled.tsx
  src/components/molecules/ValidationErrorsPopover/ValidationErrorLink.tsx
  src/components/molecules/ValidationErrorsPopover/ValidationErrorsPopover.tsx
  src/components/molecules/ValidationErrorsPopover/index.ts
  src/components/molecules/ValidationPopover/ValidationPopover.tsx
  src/components/molecules/ValidationPopover/ValidationPopoverContent.styled.tsx
  src/components/molecules/ValidationPopover/ValidationPopoverContent.tsx
  src/components/molecules/ValidationPopover/index.ts
  src/components/molecules/index.ts
  src/components/organisms/NavigatorPane/NavigatorTitle.styled.tsx
  src/components/organisms/NavigatorPane/NavigatorTitle.tsx
  src/hooks/useValidationLevel.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSuffix.tsx
  src/shared/styles/colors.ts
Labels: size/L

#3109 refactor type guards for resource / origin / selection / preview
  src/shared/models/k8sResource.ts
  src/shared/models/origin.ts
  src/shared/models/preview.ts
  src/shared/models/selection.ts
Labels: size/L

#3107 fix: incremental validation triggers for file actions
  src/redux/reducers/main/mainSlice.ts
  src/redux/services/fileEntry.ts
  src/redux/thunks/multiplePathsAdded.ts
  src/redux/thunks/multiplePathsChanged.ts
  src/redux/thunks/replaceImageTag.ts
  src/redux/thunks/updateFileEntry.ts
  src/redux/thunks/updateMultipleResources.ts
  src/redux/validation/validation.listeners.tsx
Labels: size/L

#3110 fix: #3102 #3100
  package-lock.json
  package.json
  src/components/organisms_new/CompareSyncPane/CompareSyncPane.tsx
  src/components/organisms_new/PaneManager/activities.tsx
  src/components/organisms_new/ResourceSetSelector/ResourceSetSelectColor.styled.tsx
Labels: size/S

#3111 Razvantopliceanu/chore/remove settings plugin manager
  src/App.tsx
  src/components/atoms/FilePatternList/FilePatternList.tsx
  src/components/molecules/NotificationMarkdown/TelemetryButtons.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/OPAChip.styled.tsx
  src/components/organisms/PageHeader/OPAChip.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PluginManager/PluginInformation.styled.tsx
  src/components/organisms/PluginManager/PluginInformation.tsx
  src/components/organisms/PluginManager/PluginInstallModal.tsx
  src/components/organisms/PluginManager/PluginManager.styled.tsx
  src/components/organisms/PluginManager/PluginManager.tsx
  src/components/organisms/PluginManager/index.ts
  src/components/organisms/SettingsManager/Settings.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/SettingsManager/index.ts
  src/components/organisms/SettingsManager/styled.tsx
  src/components/organisms/index.ts
  src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.tsx
  src/components/organisms_new/SettingsPane/Settings/Settings.tsx
  src/constants/tooltips.tsx
  src/hooks/menuItemsHooks/useHelpMenuItems.tsx
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionEmptyDisplay.tsx
  src/redux/initialState.ts
  src/redux/reducers/extension.ts
  src/redux/reducers/ui.ts
  src/shared/models/extension.ts
  src/shared/models/ui.ts
Labels: size/XXL

#3069 fix: update resource filter component
  package-lock.json
  src/components/molecules/ChangeFiltersConfirmModal/ChangeFiltersConfirmModal.tsx
  src/components/molecules/Monaco/symbolProcessing.ts
  src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/molecules/ResourceFilterIconWithPopover/ResourceFilterIconWithPopover.tsx
  src/components/molecules/ResourceFilterIconWithPopover/index.ts
  src/components/molecules/ResourceNamespaceFilter/ResourceNamespaceFilter.tsx
  src/components/molecules/index.ts
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/components/organisms/QuickSearchActions/QuickSearchActions.tsx
  src/hooks/useFolderTreeSelectData.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
  src/redux/reducers/main/filterReducers.ts
  src/redux/services/resource.ts
  src/shared/models/appState.ts
  src/shared/utils/filter.ts
  src/utils/resources.ts
Labels: size/XL

#3114 feat: workerify utility
  src/utils/workerify.ts
Labels: size/L

#3112 fix: resource & file highlights
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
  src/redux/reducers/main/selectionReducers.ts
Labels: size/M

#3118 refactor: core validation popover
  package-lock.json
  package.json
  src/components/molecules/ValidationPopover/ValidationPopover.tsx
  src/components/molecules/ValidationPopover/ValidationPopoverContent.styled.tsx
  src/components/molecules/ValidationPopover/ValidationPopoverContent.tsx
  src/components/molecules/ValidationPopover/index.ts
  src/components/molecules/index.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
Labels: size/L

#3122 feat: run validation using web worker
  src/redux/validation/validation.services.ts
  src/redux/validation/validation.thunks.ts
  src/redux/validation/validation.worker.ts
  src/redux/validation/validation.worker.types.ts
  tsconfig.json
Labels: size/L

#3116 Erdikose/fix/dashboard left menu
  src/components/organisms/Dashboard/Tableview/TableCells.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
Labels: size/M

#3120 feat: explorer accordions
  package-lock.json
  src/components/organisms/FileTreePane/types.tsx
  src/components/organisms/HelmPane/HelmPane.tsx
  src/components/organisms/HelmPane/index.ts
  src/components/organisms/ImagesPane/ImagesPane.tsx
  src/components/organisms/KustomizePane/KustomizePane.tsx
  src/components/organisms/KustomizePane/index.ts
  src/components/organisms/index.ts
  src/components/organisms_new/ExplorerPane/AccordionPanel/AccordionPanel.styled.tsx
  src/components/organisms_new/ExplorerPane/AccordionPanel/AccordionPanel.tsx
  src/components/organisms_new/ExplorerPane/AccordionPanel/AccordionTitleBarContainer.tsx
  src/components/organisms_new/ExplorerPane/AccordionPanel/index.ts
  src/components/organisms_new/ExplorerPane/ExplorerPane.tsx
  src/components/organisms_new/ExplorerPane/FilePane/CreateNode.styled.tsx
  src/components/organisms_new/ExplorerPane/FilePane/CreateNode.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.styled.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FilePaneTree.styled.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FilePaneTree.tsx
  src/components/organisms_new/ExplorerPane/FilePane/TreeItem.styled.tsx
  src/components/organisms_new/ExplorerPane/FilePane/TreeItem.tsx
  src/components/organisms_new/ExplorerPane/FilePane/types.tsx
  src/components/organisms_new/ExplorerPane/HelmConfigPane/HelmConfigPane.tsx
  src/components/organisms_new/ExplorerPane/HelmConfigPane/index.ts
  src/components/organisms_new/ExplorerPane/HelmPane/HelmPane.styled.tsx
  src/components/organisms_new/ExplorerPane/ImagePane/ImagePane.tsx
  src/components/organisms_new/ExplorerPane/ImagePane/index.ts
  src/components/organisms_new/ExplorerPane/ImagesPane/ImagesPane.styled.tsx
  src/components/organisms_new/ExplorerPane/ImagesPane/ImagesPane.tsx
  src/components/organisms_new/ExplorerPane/ImagesPane/index.ts
  src/components/organisms_new/ExplorerPane/KustomizePane/KustomizePane.styled.tsx
  src/components/organisms_new/ExplorerPane/KustomizePane/KustomizePane.tsx
  src/components/organisms_new/PaneManager/activities.tsx
  src/components/organisms_new/index.ts
  src/hooks/fileTreeHooks/useTreeKeys.ts
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationPrefix.tsx
  src/redux/selectors.ts
  src/shared/models/explorer.ts
  src/shared/models/fileExplorer.ts
  src/utils/files.ts
Labels: size/XXL

#3123 chore: remove unsatisfied refs icon
  src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
Labels: size/S

#3124 fix: validation for all resource storages
  package-lock.json
  package.json
  src/redux/validation/validation.listeners.tsx
  src/redux/validation/validation.thunks.ts
  src/redux/validation/validation.worker.ts
  src/shared/models/validation.ts
  src/utils/objects.ts
Labels: size/L

#3125 fix header and navigator styling
  src/components/molecules/SectionRenderer/SectionRenderer.tsx
  src/components/molecules/SectionRenderer/styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionNameDisplay.tsx
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionNameSuffix.styled.tsx
  src/navsections/UnknownResourceSectionBlueprint/UnknownResourceNameDisplay.tsx
  src/navsections/UnknownResourceSectionBlueprint/UnknownResourceSectionBlueprint.ts
  src/redux/reducers/main/previewReducers.ts
Labels: size/L

#3126 fix cluster dashboard error icon
  src/components/organisms/Dashboard/Tableview/ErrorCell.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.tsx
Labels: size/M

#3132 fix: selection of helm values
  src/components/molecules/Monaco/Monaco.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartSectionBlueprint.ts
  src/redux/reducers/main/selectionReducers.ts
Labels: size/S

#3133 fix: resource guards
  src/components/molecules/Monaco/CodeIntel/k8sResource/applyRefIntel.ts
  src/components/organisms/FormEditorModal/FormEditorModal.tsx
  src/components/organisms_new/ExplorerPane/ExplorerPane.tsx
  src/redux/services/resource.ts
  src/shared/models/k8sResource.ts
  src/utils/resources.ts
Labels: size/L

#3134 fix: reorder activities
  src/components/organisms_new/PaneManager/activities.tsx
Labels: size/S

#3121 fix: long running loading
  src/assets/monokleprogressbar.gif
  src/components/organisms_new/CompareSyncPane/CompareModalSelecting/CompareModalSelecting.styled.tsx
  src/components/organisms_new/CompareSyncPane/CompareModalSelecting/CompareModalSelecting.tsx
  src/components/organisms_new/CompareSyncPane/CompareModalSelecting/Loading.tsx
  src/components/organisms_new/CompareSyncPane/CompareSyncPane.styled.tsx
  src/components/organisms_new/CompareSyncPane/CompareSyncPane.tsx
  src/components/organisms_new/CompareSyncPane/ComparisonList/ComparisonList.tsx
Labels: size/M

#3135 feat: configure errors warnings
  package-lock.json
  package.json
  src/components/organisms_new/ExplorerPane/ExplorerPane.tsx
  src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationLevelSelect.styled.tsx
  src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationLevelSelect.tsx
  src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationOpenPolicyAgent.tsx
  src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationOpenPolicyAgentTable.styled.tsx
  src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationOpenPolicyAgentTable.tsx
  src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/useOpenPolicyAgentTable.tsx
  src/constants/tooltips.tsx
  src/redux/validation/validation.listeners.tsx
  src/redux/validation/validation.selectors.ts
  src/redux/validation/validation.slice.ts
  src/shared/models/validation.ts
Labels: size/L

#3136 refactor: section/item blueprint performance boost
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/SectionRenderer/SectionRenderer.tsx
  src/components/molecules/SectionRenderer/useSectionCustomization.ts
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms_new/ExplorerPane/HelmPane/HelmPane.tsx
  src/components/organisms_new/ExplorerPane/ImagesPane/ImagesPane.tsx
  src/components/organisms_new/ExplorerPane/KustomizePane/KustomizePane.tsx
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionNameDisplay.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSuffix.tsx
  src/redux/services/fileEntry.ts
Labels: size/L

#3119 fix: update bg color across the app
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/FormEditorModal/FormEditorModal.styled.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
  src/components/organisms_new/PaneManager/PaneManager.styled.tsx
  src/components/organisms_new/PaneManager/PaneManagerLeftMenu.tsx
  src/utils/monaco.ts
Labels: size/M

#3137 refactor: initial state
  src/components/organisms_new/ValidationPane/ValidationPane.tsx
  src/redux/validation/validation.initialState.ts
Labels: size/M

#3138 feat: validation overview loading
  src/components/organisms_new/ValidationPane/ValidationPane.tsx
  src/redux/validation/validation.slice.ts
  src/redux/validation/validation.worker.ts
Labels: size/M

#3139 fix: accordion height
  src/components/organisms_new/ExplorerPane/AccordionPanel/AccordionPanel.tsx
Labels: size/S

#3140 Razvantopliceanu/fix/monokle validation reimplement
  src/components/organisms/Dashboard/Overview/Status.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.styled.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/NavigatorPane/OPAValidationStatus.styled.tsx
  src/components/organisms/NavigatorPane/OPAValidationStatus.tsx
Labels: size/L

#3141 fix: disable namespaces for which the resource doesn't exist
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
Labels: size/XS

#3145 fix: UI issues
  package-lock.json
  package.json
  src/assets/GitSelectItem.svg
  src/assets/SelectItemFromLeft.svg
  src/components/atoms/SelectItemImage/SelectItemImage.styled.tsx
  src/components/atoms/SelectItemImage/SelectItemImage.tsx
  src/components/atoms/SelectItemImage/index.ts
  src/components/atoms/StyledComponents/TitleBarWrapper.tsx
  src/components/atoms/index.ts
  src/components/molecules/PreviewConfigurationDetails/PreviewConfigurationDetails.styled.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
  src/components/molecules_new/ProjectsList/ProjectsList.styled.tsx
  src/components/molecules_new/ProjectsList/ProjectsList.tsx
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/FileTreePane/styled.tsx
  src/components/organisms/GitOpsView/GitView.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms_new/CompareSyncPane/CompareSyncPane.styled.tsx
  src/components/organisms_new/PaneManager/PaneManager.tsx
  src/components/organisms_new/PaneManager/activities.tsx
  src/components/organisms_new/ProblemPane/ProblemPane.tsx
  src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.styled.tsx
  src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.tsx
  src/components/organisms_new/SettingsPane/SettingsPane.styled.tsx
  src/components/organisms_new/SettingsPane/SettingsPane.tsx
  src/components/organisms_new/StartPage/StartPage.styled.tsx
  src/components/organisms_new/StartPage/StartPageHeader.tsx
  src/components/organisms_new/StartPage/StatePageHeader.styled.tsx
  src/components/organisms_new/ValidationPane/ValidationPane.tsx
  src/hooks/menuItemsHooks/useHelpMenuItems.tsx
Labels: size/XL

#3146 fix: close table drawer when changing namespace
  src/redux/dashboard/slice.ts
Labels: size/XS

#3147 fix: solve nightly build issue
  .github/workflows/monokle-build-nightly.yml
  .github/workflows/monokle-publish-test.yml
Labels: size/XS

#3151 fix: incremental validation
  src/redux/validation/validation.thunks.ts
  src/redux/validation/validation.worker.ts
  src/redux/validation/validation.worker.types.ts
Labels: size/S

#3158 fix validation for CRDs
  src/components/organisms_new/ValidationSettings/ValidationOverview/ValidationCard.tsx
  src/kindhandlers/common/customObjectKindHandler.ts
  src/kindhandlers/index.ts
  src/redux/validation/crdListener.ts
  src/redux/validation/validation.services.ts
  src/redux/validation/validation.worker.types.ts
  src/shared/models/integrations.ts
Labels: size/L

#3159 chore: add additional telemetry events
  src/redux/services/previewCommand.ts
  src/redux/thunks/cluster/loadClusterResources.ts
  src/redux/thunks/previewHelmValuesFile.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/runPreviewConfiguration.ts
  src/shared/models/telemetry.ts
Labels: size/M

#3150 fix: dashboard status box
  src/components/atoms/StyledComponents/TitleBarWrapper.tsx
  src/components/organisms/Dashboard/Overview/Status.styled.tsx
Labels: size/S

#3160 revert titlebar styles and fix CellAge from Dashboard
  src/components/atoms/StyledComponents/TitleBarWrapper.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.tsx
Labels: size/S

#3162 feat: process refs in web worker
  src/redux/parsing/parser.thunks.ts
  src/redux/parsing/parser.worker.ts
  src/redux/parsing/parser.worker.types.ts
  src/redux/parsing/resourceParser.ts
  src/redux/reducers/main/mainSlice.ts
  src/redux/validation/crdListener.ts
  src/redux/validation/validation.selectors.ts
  src/redux/validation/validation.thunks.ts
  src/redux/validation/validation.worker.ts
  src/redux/validation/validation.worker.types.ts
  src/redux/validation/validator.ts
  src/shared/models/validation.ts
  src/utils/resources.ts
  src/utils/worker.ts
Labels: size/L

#3166 [Snyk] Upgrade yargs from 17.6.0 to 17.6.2
  package-lock.json
  package.json
Labels: size/XS

#3167 [Snyk] Upgrade @kubernetes/client-node from 0.18.0 to 0.18.1
  package-lock.json
  package.json
Labels: size/XS

#3168 [Snyk] Upgrade @types/analytics-node from 3.1.9 to 3.1.10
  package-lock.json
  package.json
Labels: size/XS

#3169 [Snyk] Upgrade @monokle/validation from 0.10.3 to 0.11.0
  package-lock.json
  package.json
Labels: size/XS

#3178 fix: config selectors re-rendering
  src/redux/selectors.ts
Labels: size/S

#3177 fix: get started actions
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionEmptyDisplay.tsx
Labels: size/M

#3175 fix: loading when changing branches
  src/redux/git/git.slice.ts
Labels: size/XS

#3172 fix: FilePane title bar buttons
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
Labels: size/XS

#3173 feat: validation problems count badge
  src/components/organisms_new/PaneManager/activities.tsx
Labels: size/S

#3170 fix: killing terminal session for windows
  electron/app/ipc/ipcListeners.ts
  package-lock.json
  package.json
Labels: size/S

#3179 fix: resizing resource filters
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
Labels: size/S

#3180 chore: small fixes
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
  src/utils/hooks.ts
Labels: size/XS

#3182 fix: expand/collapse folders in FilePane
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
Labels: size/M

#3183 Razvantopliceanu/refactor/file tree styling
  package-lock.json
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.styled.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.styled.ts
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNode.styled.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFile.tsx
Labels: size/L

#3186 fix: background-color
  src/components/organisms_new/PaneManager/PaneManagerLeftMenu.tsx
Labels: size/XS

#3187 fix: saving resources
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/useDebouncedCodeSave.ts
  src/redux/reducers/main/mainSlice.ts
  src/redux/services/resource.ts
  src/redux/thunks/updateMultipleResources.ts
  src/redux/thunks/updateResource.ts
Labels: size/L

#3184 fix: saving transient resources to folder / file
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/redux/reducers/main/mainSlice.ts
  src/redux/services/fileEntry.ts
Labels: size/L

#3164 chore: cluster dashboard updates
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/Overview/Overview.styled.tsx
  src/components/organisms/Dashboard/Overview/Overview.tsx
  src/components/organisms/Dashboard/Overview/Status.styled.tsx
Labels: size/M

#3188 refactor: improve Monaco apply/clear code intel
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/useCodeIntel.ts
Labels: size/M

#3144 fix: maximum hook update
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/FormEditor/FormWidgets/ApiGroupSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/ImageSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/NamespaceSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/PodSelectorSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/ResourceSelection.tsx
  src/components/molecules/FormEditor/FormWidgets/SecretKindSelection.tsx
  src/redux/thunks/readResourceFile.ts
  src/redux/thunks/saveFormEditorResource.ts
Labels: size/L

#3171 feat: add BackToProjects button to quick cluster preview
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms_new/PaneManager/activities.tsx
Labels: size/M

#3190 fix: unescape if statement
  src/components/molecules/FormEditor/FormWidgets/NamespaceSelection.tsx
Labels: size/XS

#3191 fix: increase the top height
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
Labels: size/XS

#3196 fix: select branch after creation
  src/components/molecules/BranchSelect/CreateBranchInput.tsx
Labels: size/S

#3195 fix: check undefined object
  src/components/molecules/Monaco/Monaco.tsx
Labels: size/XS

#3192 fix: scroll top when change the problem
  src/components/organisms_new/ProblemPane/ProblemPane.tsx
Labels: size/XS

#3193 fix: change error badges
  src/components/organisms/Dashboard/Overview/Status.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.styled.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/shared/models/dashboard.ts
Labels: size/M

#3201 refactor: show errors first
  src/components/organisms/Dashboard/Tableview/ErrorCell.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationPrefix.tsx
Labels: size/XS

#3202 fix: show warnings & errors in Monaco
  src/components/molecules/Monaco/CodeIntel/k8sResource/applyErrorIntel.ts
  src/components/molecules/Monaco/CodeIntel/k8sResource/applyPolicyIntel.ts
  src/components/molecules/Monaco/CodeIntel/k8sResource/applyValidationIntel.ts
  src/components/molecules/Monaco/CodeIntel/k8sResource/index.ts
  src/redux/reducers/main/selectionReducers.ts
  src/redux/validation/validation.listeners.tsx
  src/utils/monaco.ts
Labels: size/L

#3203 fix image selection & highlight of it's resources
  src/navsections/ImagesSectionBlueprint/ImagesSectionBlueprint.ts
  src/redux/reducers/main/selectionReducers.ts
Labels: size/M

#3200 fix: autosave direct when the form event get called
  src/components/molecules/FormEditor/FormEditor.tsx
Labels: size/M

#3204 Razvantopliceanu/refactor/file folders sorting
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
  src/components/organisms_new/SettingsPane/GlobalSettings/GlobalSettings.tsx
Labels: size/M

#3205 fix: search validation by ruleId
  package-lock.json
  package.json
Labels: size/XS

#3206 fix: validation for k8s schema
  src/components/molecules/FormEditor/FormWidgets/ApiGroupSelection.tsx
  src/redux/reducers/appConfig.ts
  src/redux/services/resource.ts
  src/redux/store.ts
  src/redux/validation/validation.worker.ts
  src/redux/validation/validation.worker.types.ts
  src/redux/validation/validator.ts
Labels: size/M

#3197 fix: ellipsis
  package-lock.json
  src/components/organisms_new/ValidationPane/ValidationPane.tsx
Labels: size/M

#3209 small general fixes
  src/App.tsx
  src/components/molecules/SectionRenderer/SectionHeader.tsx
  src/components/molecules/Walkthrough/Walkthrough.styled.tsx
  src/components/molecules/Walkthrough/Walkthrough.tsx
  src/components/molecules/Walkthrough/content/index.ts
  src/components/molecules/Walkthrough/content/newReleaseFeatures.ts
  src/components/molecules/Walkthrough/content/novice.ts
  src/components/molecules/Walkthrough/index.ts
  src/components/molecules/index.ts
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/PageHeader/K8sVersionSelection.style.tsx
  src/components/organisms/PageHeader/K8sVersionSelection.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNode.styled.tsx
  src/hooks/menuItemsHooks/useHelpMenuItems.tsx
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/models/ui.ts
Labels: size/L

#3211 Razvantopliceanu/fix/item renderer hover menu
  package-lock.json
  package.json
  src/components/atoms/Dots/Dots.styled.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNode.styled.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFile.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFolder.tsx
Labels: size/M

#3212 refactor: empty dashboard cluster connection svg
  src/assets/ClusterIndication.svg
  src/assets/ConnectClusterDashboard.svg
  src/assets/LoadClusterDashboard.svg
  src/components/organisms/Dashboard/EmptyDashboard.styled.tsx
  src/components/organisms/Dashboard/EmptyDashboard.tsx
Labels: size/L

#3213 fix: trigger menu on click
  src/components/organisms_new/StartPage/StartPageHeader.tsx
Labels: size/XS

#3217 fix: dispose Monaco model on file/resource change
  src/components/molecules/Monaco/Monaco.tsx
Labels: size/XS

#3216 chore: remove unused
  package-lock.json
  package.json
Labels: size/S

#3218 fix: disable search projects auto focus
  src/components/organisms_new/StartPage/StartPageHeader.tsx
Labels: size/XS

#3219 Razvantopliceanu/refactor/new resource
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
  src/constants/tooltips.tsx
  src/hooks/menuItemsHooks/useNewResourceMenuItems.tsx
Labels: size/M

#3221 Razvantopliceanu/refactor/use core text ellipsis
  package-lock.json
  package.json
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
  src/components/organisms/PreviewConfigurationEditor/ValuesFilesList/styled.tsx
  src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.styled.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
Labels: size/M

#3222 fix: create resources for multi-manifest template
  src/redux/services/templates.ts
Labels: size/M

#3223 Razvantopliceanu/fix/template select resource icon
  src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
  src/components/organisms_new/TemplateExplorer/CreatedResources/CreatedResources.tsx
Labels: size/XS

#3226 feat: save resources created by a template directly to a folder
  src/components/organisms_new/CompareSyncPane/CompareSyncPane.tsx
  src/components/organisms_new/TemplateExplorer/CreatedResources/CreatedResources.tsx
  src/components/organisms_new/TemplateExplorer/CreatedResources/SaveToFolderModal.tsx
  src/redux/reducers/main/mainSlice.ts
Labels: size/L

#3227 feat: icon for creating folder on Files titlebar
  src/components/organisms_new/ExplorerPane/FilePane/FilePane.tsx
Labels: size/S

#3230 fix: handle namespaces change gracefuly for cluster dashboard
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/Tableview/Tableview.tsx
Labels: size/S

#3234 fix: scrollbar for template explorer
  package-lock.json
  package.json
  src/components/organisms_new/TemplateExplorer/TemplateExplorer.styled.tsx
  src/components/organisms_new/TemplateExplorer/TemplateExplorer.tsx
Labels: size/S

#3236 fix: memoisation of resource maps selectors
  src/redux/selectors/resourceMapSelectors.ts
  src/redux/selectors/resourceSelectors.ts
Labels: size/L

#3235 fix: open shell in pod
  electron/app/ipc/ipcListeners.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
Labels: size/S

#3237 fix: shell height
  src/components/organisms/Dashboard/Tableview/TerminalTab.tsx
Labels: size/XS

#3238 fix: init only if terminal ref doesn't exist
  src/components/organisms/Dashboard/Tableview/TerminalTab.tsx
Labels: size/XS

#3228 Release Notes for 2.0
  package.json
  resources/releaseNotes/2.0/2.0.json
  resources/releaseNotes/2.0/2.0.md
  resources/releaseNotes/2.0/2.0.svg
  src/redux/services/fileEntry.ts
Labels: size/L

#3240 chore(release): 2.0.0
  CHANGELOG.md
  package-lock.json
Labels: size/S

#3243 [Snyk] Upgrade @reduxjs/toolkit from 1.9.1 to 1.9.2
  package-lock.json
  package.json
Labels: size/XS

#3246 [Snyk] Upgrade redux from 4.2.0 to 4.2.1
  package-lock.json
  package.json
Labels: size/XS

#3248 Razvantopliceanu/chore/update dependencies
  package-lock.json
  package.json
  src/components/organisms/GitPane/CommitModal.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/PreviewConfigurationEditor/ValuesFilesList/ValuesFilesList.tsx
Labels: size/M

#3229 docs: Additional Updates for the New Releases
  docs/apply-and-diff.md
  docs/cluster-integration.md
  docs/cluster-issues.md
  docs/cluster-mode.md
  docs/compare-sync.md
  docs/helm.md
  docs/img/add-new-plugin-2.0.png
  docs/img/add-plugin-modal-2.0.png
  docs/img/cluster-compare-button-2.0.png
  docs/img/cluster-mode-navigation-2.0.png
  docs/img/cluster-preview-2.0.png
  docs/img/cluster-preview2-2.0.png
  docs/img/cluster-selector-2.0.png
  docs/img/clusters-tab-2.0.png
  docs/img/default-templates-2.0.png
  docs/img/deploy-and-diff-buttons-2.0.png
  docs/img/helm-configuration-plus-sign-2.0.png
  docs/img/helm-navigation-2.0.png
  docs/img/helm-preview-action-2.0.png
  docs/img/helm-preview-configurations-2.0.png
  docs/img/helm-preview-output-2.0.png
  docs/img/helm-preview-reload-2.0.png
  docs/img/helm-settings-2.0.png
  docs/img/helm-templates-2.0.png
  docs/img/helm-values-reference-2.0.png
  docs/img/kubeconfig-setting-2.0.png
  docs/img/namespace-selector-2.0.png
  docs/img/open-plugin-manager-2.0.png
  docs/img/preview-configuration-drawer-2.0.png
  docs/img/select-template-2.0.png
  docs/plugins.md
  docs/templates.md
Labels: size/M

#3261 feat: add new telemetry events
  src/components/organisms_new/ExplorerPane/ExplorerPane.tsx
  src/components/organisms_new/PaneManager/PaneManagerLeftMenu.tsx
  src/shared/models/telemetry.ts
Labels: size/S

#3247 fix: handling InputNumber onStep
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/hooks/menuItemsHooks/useTerminalOptionsMenuItems.tsx
Labels: size/M

#3275 fix: navigation pane ellipsis
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
Labels: size/S

#3276 refactor: change message
  src/components/organisms/Dashboard/EmptyDashboard.styled.tsx
  src/components/organisms/Dashboard/EmptyDashboard.tsx
Labels: size/XS

#3277 refactor: install button on plugins manager
  src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.styled.tsx
  src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.tsx
Labels: size/S

#3278 fix: styling of Scale/Restart buttons
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/ActionsPane/Restart/Restart.tsx
  src/components/organisms/ActionsPane/Scale/Scale.tsx
Labels: size/M

#3280 fix: show/hide namespace tag based on filter
  src/navsections/K8sResourceSectionBlueprint/ResourceKindPrefix.tsx
Labels: size/XS

#3282 fix: path exists error when creating project
  src/components/organisms_new/CreateProjectModal/CreateProjectModal.tsx
Labels: size/M

#3281 fix: clean item name sign
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
Labels: size/XS

#3283 fix: template explorer scrolling
  src/components/organisms_new/TemplateExplorer/TemplateExplorer.styled.tsx
  src/components/organisms_new/TemplateExplorer/TemplateForm/TemplateForm.styled.tsx
Labels: size/XS

#3287 fix: navigator search responsivness
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
Labels: size/XS

#3288 fix: navigator search responsivness
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
Labels: size/S

#3290 fix: creating file
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
Labels: size/M

#3289 fix: transient resources navigator
  src/redux/selectors/resourceMapSelectors.ts
Labels: size/S

#3291 fix: preview kustomization
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFile.tsx
  src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
  src/components/organisms_new/ExplorerPane/FilePane/old/CreateNode.styled.tsx
  src/components/organisms_new/ExplorerPane/FilePane/old/CreateNode.tsx
  src/components/organisms_new/ExplorerPane/FilePane/old/FilePaneTree.styled.tsx
  src/components/organisms_new/ExplorerPane/FilePane/old/FilePaneTree.tsx
  src/components/organisms_new/ExplorerPane/FilePane/old/TreeItem.styled.tsx
  src/components/organisms_new/ExplorerPane/FilePane/old/TreeItem.tsx
Labels: size/XL

#3292 fix: deploy modal defaults
  src/components/molecules/ModalConfirmWithNamespaceSelect/ModalConfirmWithNamespaceSelect.tsx
Labels: size/XS

#3286 fix: icon order
  src/components/atoms/StyledComponents/SectionBlueprintList.tsx
  src/components/atoms/StyledComponents/index.ts
  src/components/atoms/index.ts
  src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
  src/components/organisms_new/ExplorerPane/HelmPane/HelmPane.tsx
  src/components/organisms_new/ExplorerPane/ImagesPane/ImagesPane.styled.tsx
  src/components/organisms_new/ExplorerPane/ImagesPane/ImagesPane.tsx
  src/components/organisms_new/ExplorerPane/KustomizePane/KustomizePane.styled.tsx
  src/components/organisms_new/ExplorerPane/KustomizePane/KustomizePane.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.styled.tsx
Labels: size/M

#3285 refactor: telemetry events
  src/components/organisms_new/ExplorerPane/ExplorerPane.tsx
  src/components/organisms_new/PaneManager/PaneManagerLeftMenu.tsx
  src/shared/models/telemetry.ts
Labels: size/XS

#3293 refactor: use monokle-core search input
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.styled.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.tsx
Labels: size/S

#3294 fix: cluster configure
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms_new/SettingsPane/Settings/Settings.tsx
  src/components/organisms_new/SettingsPane/SettingsPane.tsx
  src/redux/initialState.ts
  src/shared/models/config.ts
  src/shared/models/ui.ts
Labels: size/M

#3295 fix: git publish branch
  src/components/molecules/BranchSelect/CreateBranchInput.tsx
  src/components/organisms/GitPane/BottomActions.tsx
  src/redux/git/git.slice.ts
Labels: size/S

#3296 [Snyk] Upgrade node-fetch from 2.6.7 to 2.6.9
  package-lock.json
  package.json
Labels: size/XS

#3297 refactor: UI/UX
  src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
  src/components/organisms_new/SettingsPane/GlobalSettings/GlobalSettings.styled.tsx
  src/components/organisms_new/SettingsPane/GlobalSettings/GlobalSettings.tsx
  src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.styled.tsx
  src/components/organisms_new/SettingsPane/PluginsManager/PluginManager.tsx
  src/components/organisms_new/SettingsPane/Settings/Settings.styled.tsx
  src/components/organisms_new/SettingsPane/Settings/Settings.tsx
  src/components/organisms_new/SettingsPane/SettingsPane.styled.tsx
  src/components/organisms_new/SettingsPane/SettingsPane.tsx
  src/components/organisms_new/StartPage/StartPage.styled.tsx
Labels: size/M

#3299 fix: change left menu selection only on connect
  src/redux/thunks/cluster/startClusterConnection.ts
Labels: size/XS

#3301 fix: looping syncing localState with global state
  src/components/organisms_new/SettingsPane/CurrentProjectSettings/CurrentProjectSettings.tsx
  src/components/organisms_new/SettingsPane/Settings/Settings.tsx
  src/redux/appConfig/appConfig.listeners.ts
  src/redux/reducers/ui.ts
  src/redux/thunks/cluster/startClusterConnection.ts
  src/shared/utils/selectors.ts
Labels: size/M

#3300 chore: update package
  package-lock.json
  package.json
Labels: size/XS

#3302 chore(release): 2.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#3303 Razvantopliceanu/feat/update package lock
  package-lock.json
  package.json
Labels: size/XS

#3304 chore(release): 2.0.1
  CHANGELOG.md
  package.json
Labels: size/S

#3305 chore: update package-lock
  package-lock.json
  package.json
Labels: size/XS

#3306 chore(release): 2.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS

#3311 feat: silent patch releases
  src/App.tsx
  src/components/organisms/UpdateNotice/UpdateNotice.styled.tsx
  src/components/organisms/UpdateNotice/UpdateNotice.tsx
Labels: size/M

#3314 docs: Add 2.0 Release Notes Blog Post
  docs/docs/index.md
Labels: size/XS

#3315 chore: fix documentation
  .github/workflows/mkdocs.yml
Labels: size/XS

#3320 chore: change documentation
  docs/docs/development.md
Labels: size/XS

#3321 fix: validation pane height
  src/components/organisms/ValidationPane/ValidationPane.tsx
  src/hooks/usePaneHeight.ts
Labels: size/XS

#3322 fix: kill terminals when going to start page
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/redux/appConfig/appConfig.slice.ts
  src/redux/reducers/terminal.ts
  src/redux/store.ts
Labels: size/M

#3325 feat: validation editor tab
  src/components/molecules/Monaco/Monaco.styled.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/Dashboard/Tableview/EditorTab.tsx
  src/components/organisms/ProblemPane/ProblemPane.styled.tsx
  src/components/organisms/ProblemPane/ProblemPane.tsx
  src/components/organisms/ValidationPane/ValidationPane.tsx
  src/feature-flags.json
  src/hooks/menuItemsHooks/index.ts
  src/hooks/menuItemsHooks/useProblemPaneMenuItems.tsx
  src/redux/validation/validation.selectors.ts
  src/utils/features.tsx
Labels: size/L

#3330 fix: template create project
  src/components/organisms/TemplateExplorer/TemplateCollapseItem/TemplateCollapseItem.tsx
  src/components/organisms/TemplateExplorer/TemplateExplorer.styled.tsx
  src/components/organisms/TemplateExplorer/TemplateExplorer.tsx
  src/redux/reducers/ui.ts
Labels: size/M

#3331 fix: broken link
  src/components/organisms/LearnPage/LearnPage.tsx
  src/components/organisms/LearnPage/WalkThroughModal.tsx
  src/components/organisms/SettingsPane/SettingsPane.tsx
  src/components/organisms/StartPage/StartPage.tsx
  src/components/organisms/StartPage/StartPageHeader.tsx
  src/components/organisms/TemplateExplorer/TitleBarDescription/TitleBarDescription.tsx
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/models/ui.ts
Labels: size/L

#3334 refactor: Done button
  src/components/organisms/TemplateExplorer/CreatedResources/CreatedResources.styled.tsx
  src/components/organisms/TemplateExplorer/CreatedResources/CreatedResources.tsx
Labels: size/S
