Repository kubeshop/monokle, pull requests merged in 2023-01, with the labels that each got.

#2963 chore: track clicks of external doc links
  src/utils/shell.ts
  src/utils/telemetry.ts
Labels: size/XS

#2964 chore: merge main to 2.0
  CHANGELOG.md
  electron/app/createWindow.ts
  electron/app/index.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/kubectl.ts
  electron/app/utils.ts
  package-lock.json
  package.json
  public/Splashscreen.css
  public/index.html
  resources/icon.ico
  resources/releaseNotes/1.13/1.13.md
  resources/schemas/1.26.0.json
  src/components/molecules/Logs/Logs.styled.ts
  src/components/organisms/FileTreePane/styled.tsx
  src/components/organisms/KeyboardShortcuts/BoardKeys/BoardKeys.styled.tsx
  src/components/organisms/SearchPane/styled.tsx
  src/components/organisms/SettingsManager/SettingsManager.tsx
  src/components/organisms/SettingsManager/styled.tsx
  src/components/organisms/UpdateNotice/UpdateNotice.tsx
  src/constants/helmOptions.ts
  src/index.css
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenuWrapper.tsx
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/services/clusterResourceWatcher.ts
  src/redux/services/compare/fetchResources.ts
  src/redux/services/monitorKubeConfig.ts
  src/redux/services/preview.ts
  src/redux/services/projectConfig.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/runPreviewConfiguration.ts
  src/redux/validation/validation.initialState.ts
  src/shared/constants/electronStore.ts
  src/shared/constants/k8s.ts
  src/shared/models/config.ts
  src/shared/models/telemetry.ts
  src/shared/utils/commands/kubectl.ts
  src/shared/utils/kubeclient.ts
  src/utils/promises.ts
Labels: size/XXL

#2962 chore: add requestedExecutionLevel for Windows build
  package.json
Labels: size/XS

#2966 feat: regex validation for image name in templates
  package-lock.json
  package.json
  src/components/molecules/FormEditor/FormArrayFieldTemplate.tsx
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/FormEditor/FormObjectFieldTemplate.tsx
  src/components/molecules/FormEditor/FormWidgets/ImageSelection.tsx
  src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/constants/constants.ts
Labels: size/M

#2968 feat: support additional files
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/FileTreePane/CreateNode.tsx
  src/constants/constants.ts
Labels: size/S

#2969 feat: fetch namespace cluster resources
  src/components/organisms/PageHeader/ClusterSelection.styled.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/constants/tooltips.tsx
  src/models/appconfig.ts
  src/redux/initialState.ts
  src/redux/reducers/appConfig.ts
  src/redux/reducers/main.ts
  src/redux/services/clusterResourceWatcher.ts
  src/redux/services/preview.ts
  src/redux/thunks/previewCluster.ts
  src/redux/thunks/previewKustomization.ts
  src/redux/thunks/startClusterPreview.ts
  src/utils/electronStore.ts
Labels: size/L

#2975 [Snyk] Upgrade @kubernetes/client-node from 0.17.1 to 0.18.0
  package-lock.json
  package.json
Labels: size/XS

#2977 Update CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#2976 feat: create folder from location if it doesn't exist
  src/components/organisms/GitCloneModal/GitCloneModal.tsx
Labels: size/S

#2978 feat: remove repo name directory if cloning fails
  src/components/organisms/CompareModal/CompareModalSelecting.tsx
  src/components/organisms/GitCloneModal/GitCloneModal.tsx
Labels: size/S

#2981 feat: add bulk operation for resource updates
  src/redux/reducers/main.ts
  src/redux/services/clusterResourceWatcher.ts
Labels: size/M

#2984 feat: handle namespace for cluster dashboard
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/Header/Header.tsx
  src/components/organisms/Dashboard/Overview/Activity.tsx
  src/components/organisms/Dashboard/Overview/InventoryInfo.tsx
  src/components/organisms/Dashboard/Overview/Status.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/redux/dashboard/slice.ts
  src/redux/dashboard/state.ts
  src/redux/services/clusterResourceWatcher.ts
  src/redux/services/preview.ts
  src/redux/thunks/previewCluster.ts
Labels: size/L

#2980 fix: notifications badge
  src/components/organisms/PageHeader/PageHeader.styled.tsx
Labels: size/S

#2988 catch getKubeAccess errors
  electron/app/initKubeconfig.ts
  src/components/organisms/Dashboard/Header/Header.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/models/appconfig.ts
  src/redux/services/monitorKubeConfig.ts
  src/utils/kubeclient.ts
Labels: size/L

#2995 fix: add loading skeleton for dashboard reloading
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
Labels: size/XS

#2997 chore(release): 1.13.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS

#2989 feat: new start page
  package-lock.json
  package.json
  src/App.tsx
  src/components/atoms/SearchInput/SearchInput.tsx
  src/components/atoms/SearchInput/index.ts
  src/components/atoms/StyledComponents/IconButton.tsx
  src/components/atoms/StyledComponents/index.ts
  src/components/atoms/index.ts
  src/components/molecules_new/ProjectCard/ProjectCard.styled.tsx
  src/components/molecules_new/ProjectCard/ProjectCard.tsx
  src/components/molecules_new/ProjectCard/index.ts
  src/components/molecules_new/ProjectsList/ProjectsList.styled.tsx
  src/components/molecules_new/ProjectsList/ProjectsList.tsx
  src/components/molecules_new/ProjectsList/index.ts
  src/components/molecules_new/index.ts
  src/components/organisms_new/LearnPage/HelpfulResourceCard.styled.tsx
  src/components/organisms_new/LearnPage/HelpfulResourceCard.tsx
  src/components/organisms_new/LearnPage/LearnCard.styled.tsx
  src/components/organisms_new/LearnPage/LearnCard.tsx
  src/components/organisms_new/LearnPage/LearnPage.styled.tsx
  src/components/organisms_new/LearnPage/LearnPage.tsx
  src/components/organisms_new/LearnPage/index.ts
  src/components/organisms_new/NewProject/ActionCard.styled.tsx
  src/components/organisms_new/NewProject/ActionCard.tsx
  src/components/organisms_new/NewProject/NewProject.styled.tsx
  src/components/organisms_new/NewProject/NewProject.tsx
  src/components/organisms_new/NewProject/index.ts
  src/components/organisms_new/PaneManager/PaneManager.tsx
  src/components/organisms_new/SettingsPane/SettingsPane.styled.tsx
  src/components/organisms_new/SettingsPane/SettingsPane.tsx
  src/components/organisms_new/StartPage/StartPage.styled.tsx
  src/components/organisms_new/StartPage/StartPage.tsx
  src/components/organisms_new/StartPage/StartPageHeader.tsx
  src/components/organisms_new/StartPage/StatePageHeader.styled.tsx
  src/components/organisms_new/StartPage/index.ts
  src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationOpenPolicyAgent.tsx
  src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationOpenPolicyAgentTable.styled.tsx
  src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/ValidationOpenPolicyAgentTable.tsx
  src/components/organisms_new/ValidationSettings/ValidationOverview/ValidationCard.styled.tsx
  src/components/organisms_new/ValidationSettings/ValidationOverview/ValidationOverview.styled.tsx
  src/components/organisms_new/ValidationSettings/ValidationSettings.styled.tsx
  src/components/organisms_new/ValidationSettings/ValidationSettings.tsx
  src/components/organisms_new/index.ts
  src/feature-flags.json
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/models/ui.ts
  src/shared/styles/colors.ts
  src/shared/utils/index.ts
  src/utils/features.tsx
Labels: size/XXL

#3000 refactor: remove titlebar from start page
  src/App.tsx
  src/assets/FromFolder.svg
  src/assets/FromScratch.svg
  src/assets/FromTemplate.svg
  src/components/organisms/StartProjectPane/ActionCard.styled.tsx
  src/components/organisms/StartProjectPane/ActionCard.tsx
  src/components/organisms/StartProjectPane/Guide.styled.tsx
  src/components/organisms/StartProjectPane/Guide.tsx
  src/components/organisms/StartProjectPane/RecentProject.styled.tsx
  src/components/organisms/StartProjectPane/RecentProject.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.styled.tsx
  src/components/organisms/StartProjectPane/RecentProjectsPage.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.styled.tsx
  src/components/organisms/StartProjectPane/StartProjectPage.tsx
  src/components/organisms/StartProjectPane/index.ts
  src/components/organisms/StartProjectPane/styled.tsx
  src/components/organisms/index.ts
  src/components/organisms_new/LearnPage/LearnPage.tsx
  src/components/organisms_new/NewProject/NewProject.styled.tsx
  src/components/organisms_new/NewProject/NewProject.tsx
  src/components/organisms_new/PaneManager/PaneManager.tsx
  src/components/organisms_new/PaneManager/activities.tsx
  src/components/organisms_new/SettingsPane/SettingsPane.styled.tsx
  src/components/organisms_new/SettingsPane/SettingsPane.tsx
  src/components/organisms_new/StartPage/StartPage.styled.tsx
  src/components/organisms_new/StartPage/StartPage.tsx
  src/components/organisms_new/StartPage/StartPageHeader.tsx
  src/components/organisms_new/StartPage/StatePageHeader.styled.tsx
  src/components/organisms_new/TutorialPage/TutorialCard.styled.tsx
  src/components/organisms_new/TutorialPage/TutorialCard.tsx
  src/components/organisms_new/TutorialPage/TutorialPage.styled.tsx
  src/components/organisms_new/TutorialPage/TutorialPage.tsx
  src/components/organisms_new/TutorialPage/TutorialReference.styled.tsx
  src/components/organisms_new/TutorialPage/TutorialReference.tsx
  src/components/organisms_new/TutorialPage/index.ts
  src/components/organisms_new/index.ts
  src/feature-flags.json
  src/utils/features.tsx
Labels: size/XXL

#2993 docs: troubleshooting cluster connection
  docs/cluster-issues.md
  mkdocs.yml
Labels: size/M

#3002 refactor: new project options icon
  src/assets/FromScratch.svg
  src/assets/FromTemplate.svg
  src/components/organisms_new/NewProject/NewProject.tsx
Labels: size/L

#3011 fix: switch to Inter font family
  src/components/molecules/Logs/Logs.styled.ts
  src/components/organisms/FileTreePane/styled.tsx
  src/index.css
Labels: size/S

#3008 fix: new header project title
  src/components/atoms/TableSelect/TableSelect.tsx
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/PageHeader/ProjectSelection.styled.tsx
  src/components/organisms/PageHeader/ProjectSelection.tsx
Labels: size/XL

#3018 feat: add core LearnPage
  package-lock.json
  package.json
  paths.json
  src/components/molecules_new/index.ts
  src/components/organisms_new/LearnPage/HelpfulResourceCard.styled.tsx
  src/components/organisms_new/LearnPage/HelpfulResourceCard.tsx
  src/components/organisms_new/LearnPage/LearnCard.styled.tsx
  src/components/organisms_new/LearnPage/LearnCard.tsx
  src/components/organisms_new/LearnPage/LearnPage.styled.tsx
  src/components/organisms_new/LearnPage/LearnPage.tsx
  src/components/organisms_new/LearnPage/index.ts
  src/components/organisms_new/PaneManager/activities.tsx
  src/components/organisms_new/SettingsPane/SettingsPane.styled.tsx
  src/components/organisms_new/SettingsPane/SettingsPane.tsx
  src/components/organisms_new/SettingsPane/TitleCardDescription/TitleCardDescription.styled.tsx
  src/components/organisms_new/SettingsPane/TitleCardDescription/TitleCardDescription.tsx
  src/components/organisms_new/SettingsPane/TitleCardDescription/index.ts
  src/components/organisms_new/SettingsPane/index.ts
  src/components/organisms_new/StartPage/StartPage.tsx
  src/components/organisms_new/index.ts
  src/hooks/useStartPageOptions.tsx
  src/shared/utils/shell.ts
Labels: size/XL

#3019 refactor: core icon
  package-lock.json
  package.json
  src/components/atoms/Icon/Icon.tsx
  src/components/atoms/Icon/Icons/CRDs.tsx
  src/components/atoms/Icon/Icons/Collapse.tsx
  src/components/atoms/Icon/Icons/Compare.tsx
  src/components/atoms/Icon/Icons/Dashboard.tsx
  src/components/atoms/Icon/Icons/Explorer.tsx
  src/components/atoms/Icon/Icons/Git.tsx
  src/components/atoms/Icon/Icons/GitOps.tsx
  src/components/atoms/Icon/Icons/GitProject.tsx
  src/components/atoms/Icon/Icons/GitRepository.tsx
  src/components/atoms/Icon/Icons/Helm.tsx
  src/components/atoms/Icon/Icons/Images.tsx
  src/components/atoms/Icon/Icons/IncomingRefs.tsx
  src/components/atoms/Icon/Icons/K8sSchema.tsx
  src/components/atoms/Icon/Icons/Kubernetes.tsx
  src/components/atoms/Icon/Icons/Kustomize.tsx
  src/components/atoms/Icon/Icons/OPAStatus.tsx
  src/components/atoms/Icon/Icons/OpenPolicyAgent.tsx
  src/components/atoms/Icon/Icons/OutgoingRefs.tsx
  src/components/atoms/Icon/Icons/ResourceLinks.tsx
  src/components/atoms/Icon/Icons/Search.tsx
  src/components/atoms/Icon/Icons/SeverityHigh.tsx
  src/components/atoms/Icon/Icons/SeverityLow.tsx
  src/components/atoms/Icon/Icons/SeverityMedium.tsx
  src/components/atoms/Icon/Icons/Shortcuts.tsx
  src/components/atoms/Icon/Icons/SplitView.tsx
  src/components/atoms/Icon/Icons/Terminal.tsx
  src/components/atoms/Icon/Icons/Validation.tsx
  src/components/atoms/Icon/Icons/Warning.tsx
  src/components/atoms/Icon/Icons/YAMLSyntax.tsx
  src/components/atoms/Icon/Icons/index.ts
  src/components/atoms/Icon/index.ts
  src/components/atoms/IconWithPopover/IconWithPopover.tsx
  src/components/atoms/index.ts
  src/components/molecules/ImageDetails/ImageDetails.tsx
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/components/molecules/ResourceRefsIconPopover/RefIcon.tsx
  src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
  src/components/molecules/ValidationErrorsPopover/ValidationErrorsPopover.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/FileTreePane/FileTreePane.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/components/organisms/NavigatorPane/OPAValidationStatus.tsx
  src/components/organisms/NavigatorPane/WarningAndErrorsDisplay.styled.tsx
  src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
  src/components/organisms/PageHeader/CreateProject.tsx
  src/components/organisms/PageHeader/OPAChip.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
  src/components/organisms_new/ValidationSettings/ValidationOpenPolicyAgent/useOpenPolicyAgentTable.tsx
  src/components/organisms_new/ValidationSettings/ValidationOverview/ValidationCard.styled.tsx
  src/components/organisms_new/ValidationSettings/ValidationPaneHeading/ValidationPaneHeading.styled.tsx
  src/navsections/HelmChartSectionBlueprint/ItemPrefix.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameSuffix.tsx
  src/shared/models/integrations.ts
Labels: size/XL

#3024 feat: fetch cluster resources by kind filters
  src/components/molecules/InputTags/InputTags.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/redux/thunks/previewCluster.ts
Labels: size/M

#3035 Razvantopliceanu/refactor/main refactor help
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
Labels: size/S

#3040 Update Discord link in README
  README.md
Labels: size/XS

#3041 chore: update antd
  package-lock.json
  package.json
  src/components/atoms/ContextMenu/ContextMenu.tsx
  src/components/atoms/TableSelect/TableSelect.tsx
  src/components/molecules/CommandPreview/PreviewSavedCommand.tsx
  src/components/molecules/PreviewDropdown/PreviewDropdown.styled.tsx
  src/components/molecules/PreviewDropdown/PreviewDropdown.tsx
  src/components/molecules/PreviewDropdown/PreviewMenu.tsx
  src/components/molecules/PreviewDropdown/index.ts
  src/components/molecules/index.ts
  src/components/organisms/ActionsPane/ActionsPaneHeader.styled.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/components/organisms/FileTreePane/TreeItem.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/NavigatorPane/WarningsAndErrorsDisplay.tsx
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/PageHeader/CreateProject.styled.tsx
  src/components/organisms/PageHeader/CreateProject.tsx
  src/components/organisms/PageHeader/HelpMenu.styled.tsx
  src/components/organisms/PageHeader/HelpMenu.tsx
  src/components/organisms/PageHeader/K8sVersionSelection.style.tsx
  src/components/organisms/PageHeader/K8sVersionSelection.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/TerminalPane/NewTerminalOptions.styled.tsx
  src/components/organisms/TerminalPane/NewTerminalOptions.tsx
  src/components/organisms/TerminalPane/TerminalOptions.styled.tsx
  src/components/organisms/TerminalPane/TerminalOptions.tsx
  src/components/organisms_new/PaneManager/PaneManagerLeftMenu.tsx
  src/components/organisms_new/PaneManager/activities.tsx
  src/components/organisms_new/StartPage/StartPageHeader.tsx
  src/components/organisms_new/ValidationSettings/CRDsSchemaValidation/CRDItem.tsx
  src/hooks/menuItemsHooks/index.ts
  src/hooks/menuItemsHooks/useHelpMenuItems.tsx
  src/hooks/menuItemsHooks/useNewTerminalMenuItems.tsx
  src/hooks/menuItemsHooks/useRefDropdownMenuItems.tsx
  src/hooks/menuItemsHooks/useTerminalOptionsMenuItems.tsx
  src/index.css
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenuWrapper.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenu.tsx
  src/navsections/K8sResourceSectionBlueprint/ResourceKindContextMenuWrapper.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenu.tsx
  src/navsections/KustomizationSectionBlueprint/KustomizationContextMenuWrapper.tsx
  src/shared/utils/shell.ts
Labels: size/XXL

#3015 Erdikose/feat/cluster dashboard improvements
  electron/app/createWindow.ts
  electron/app/index.ts
  electron/app/ipc/ipcListeners.ts
  electron/env.json
  package-lock.json
  package.json
  src/components/molecules/Logs/Logs.styled.ts
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/Overview/Activity.styled.tsx
  src/components/organisms/Dashboard/Overview/Activity.tsx
  src/components/organisms/Dashboard/Overview/Overview.styled.tsx
  src/components/organisms/Dashboard/Overview/Overview.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/ResourceGroupTable.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.tsx
  src/components/organisms/Dashboard/Tableview/TerminalTab.styled.tsx
  src/components/organisms/Dashboard/Tableview/TerminalTab.tsx
  src/components/organisms/Dashboard/index.ts
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/components/organisms/PaneManager/PaneManagerSplitView.tsx
  src/redux/dashboard/slice.ts
  src/redux/dashboard/state.ts
  src/redux/services/clusterResourceWatcher.ts
  src/redux/thunks/previewCluster.ts
Labels: size/XL

#3046 merge main -> 2.0
  .github/CODEOWNERS
  README.md
  docs/cluster-issues.md
  electron/app/createWindow.ts
  electron/app/index.ts
  electron/app/ipc/ipcListeners.ts
  electron/env.json
  mkdocs.yml
  package-lock.json
  src/components/atoms/InputTags/InputTags.tsx
  src/components/molecules/Logs/Logs.styled.ts
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/Overview/Activity.styled.tsx
  src/components/organisms/Dashboard/Overview/Activity.tsx
  src/components/organisms/Dashboard/Overview/Overview.styled.tsx
  src/components/organisms/Dashboard/Overview/Overview.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/ResourceGroupTable.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.tsx
  src/components/organisms/Dashboard/Tableview/TerminalTab.styled.tsx
  src/components/organisms/Dashboard/Tableview/TerminalTab.tsx
  src/components/organisms/Dashboard/index.ts
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/redux/dashboard/slice.ts
  src/redux/dashboard/state.ts
  src/redux/services/clusterResourceWatcher.ts
  src/shared/models/dashboard.ts
Labels: size/XL

#3047 quick performance fix + sentry webpack plugin
  .github/workflows/monokle-publish-downloads.yml
  .github/workflows/monokle-publish-updater.yml
  .github/workflows/monokle-publish.yml
  craco.config.js
  package-lock.json
  package.json
  src/navsections/K8sResourceSectionBlueprint/K8sResourceSectionBlueprint.ts
  src/navsections/K8sResourceSectionBlueprint/ResourceKindSectionBlueprint.ts
  src/redux/reducers/appConfig.ts
Labels: size/M

#3049 chore(release): 1.13.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#3048 refactor: templates modal
  package-lock.json
  package.json
  src/App.tsx
  src/assets/EmptySelectedTemplate.svg
  src/assets/TemplateExplorerDescription.svg
  src/components/molecules/FormEditor/FormEditor.styled.tsx
  src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
  src/components/molecules/Walkthrough/Walkthrough.styled.tsx
  src/components/organisms/Dashboard/Tableview/Tableview.styled.tsx
  src/components/organisms/DashboardPane/DashboardPane.style.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/PageHeader/K8sVersionSelection.style.tsx
  src/components/organisms_new/TemplateExplorer/CreatedResources/CreatedResources.styled.tsx
  src/components/organisms_new/TemplateExplorer/CreatedResources/CreatedResources.tsx
  src/components/organisms_new/TemplateExplorer/CreatedResources/index.ts
  src/components/organisms_new/TemplateExplorer/TemplateCollapseHeader/TemplateCollapseHeader.styled.tsx
  src/components/organisms_new/TemplateExplorer/TemplateCollapseHeader/TemplateCollapseHeader.tsx
  src/components/organisms_new/TemplateExplorer/TemplateCollapseHeader/index.ts
  src/components/organisms_new/TemplateExplorer/TemplateCollapseItem/TemplateCollapseItem.styled.tsx
  src/components/organisms_new/TemplateExplorer/TemplateCollapseItem/TemplateCollapseItem.tsx
  src/components/organisms_new/TemplateExplorer/TemplateCollapseItem/index.ts
  src/components/organisms_new/TemplateExplorer/TemplateExplorer.styled.tsx
  src/components/organisms_new/TemplateExplorer/TemplateExplorer.tsx
  src/components/organisms_new/TemplateExplorer/TemplateForm/TemplateForm.styled.tsx
  src/components/organisms_new/TemplateExplorer/TemplateForm/TemplateForm.tsx
  src/components/organisms_new/TemplateExplorer/TemplateForm/index.ts
  src/components/organisms_new/TemplateExplorer/TemplateInformation/TemplateInformation.styled.tsx
  src/components/organisms_new/TemplateExplorer/TemplateInformation/TemplateInformation.tsx
  src/components/organisms_new/TemplateExplorer/TemplateInformation/index.ts
  src/components/organisms_new/TemplateExplorer/TitleBarDescription/TitleBarDescription.styled.tsx
  src/components/organisms_new/TemplateExplorer/TitleBarDescription/TitleBarDescription.tsx
  src/components/organisms_new/TemplateExplorer/TitleBarDescription/index.ts
  src/components/organisms_new/TemplateExplorer/index.ts
  src/components/organisms_new/index.ts
  src/hooks/menuItemsHooks/index.ts
  src/hooks/menuItemsHooks/useNewResourceMenuItems.tsx
  src/hooks/useFilteredPluginMap.ts
  src/index.css
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/models/ui.ts
  src/shared/styles/colors.ts
Labels: size/XXL

#3052 refactor: create project template
  src/App.tsx
  src/components/organisms/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateInformation.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.styled.tsx
  src/components/organisms/TemplateManagerPane/TemplateManagerPane.tsx
  src/components/organisms/TemplateManagerPane/index.ts
  src/components/organisms/TemplateModal/TemplateModal.tsx
  src/components/organisms/TemplateModal/index.ts
  src/components/organisms/TemplateModal/styled.tsx
  src/components/organisms/index.ts
  src/components/organisms_new/CreateProjectModal/CreateProjectModal.tsx
  src/components/organisms_new/CreateProjectModal/index.ts
  src/components/organisms_new/TemplateExplorer/CreatedResources/CreatedResources.styled.tsx
  src/components/organisms_new/TemplateExplorer/CreatedResources/CreatedResources.tsx
  src/components/organisms_new/TemplateExplorer/TemplateCollapseItem/TemplateCollapseItem.tsx
  src/components/organisms_new/TemplateExplorer/TemplateExplorer.tsx
  src/components/organisms_new/TemplateExplorer/TemplateForm/TemplateForm.tsx
  src/components/organisms_new/index.ts
  src/redux/reducers/ui.ts
  src/shared/models/ui.ts
Labels: size/XXL

#3050 docs: Misc Updates
  docs/cluster-mode.md
  docs/desktop-v-SAAS.md
  docs/img/CRD-screen.png
  docs/img/pods-log-tab.png
  docs/img/pods-shell-tab.png
  docs/resource-crds.md
  mkdocs.yml
Labels: size/S

#3056 feat: template form back button
  src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/components/organisms_new/TemplateExplorer/TemplateForm/TemplateForm.tsx
Labels: size/S

#3057 fix: windows uac prompt
  package.json
Labels: size/XS
