Repository kubeshop/monokle, pull requests merged in 2023-06, with the labels that each got.

#4028 fix: eslint possible undefined warning
  src/components/molecules/AIGenerationModal/ai.prompt.ts
Labels: size/XS

#4020 refactor: new resource creation
  src/assets/newResource/FromAI.svg
  src/assets/newResource/FromAIHovered.svg
  src/assets/newResource/FromAdvancedTemplate.svg
  src/assets/newResource/FromAdvancedTemplateHovered.svg
  src/assets/newResource/FromModel.svg
  src/assets/newResource/FromModelHovered.svg
  src/components/atoms/StyledComponents/PrimaryButton.tsx
  src/components/organisms/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms/NavigatorPane/EmptyResourceNavigator.tsx
  src/components/organisms/NavigatorPane/EmptyResourceNavigator/EmptyResourceNavigator.tsx
  src/components/organisms/NavigatorPane/EmptyResourceNavigator/NewResourceCard.tsx
  src/components/organisms/NavigatorPane/EmptyResourceNavigator/index.ts
  src/components/organisms/NavigatorPane/NavigatorDescription.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.styled.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/PageHeader/ClusterControl/Buttons.tsx
  src/components/organisms/SettingsPane/CurrentProjectSettings/CurrentProjectSettings.tsx
  src/components/organisms/SettingsPane/Settings/Settings.styled.tsx
  src/components/organisms/SettingsPane/Settings/Settings.tsx
  src/constants/tooltips.tsx
  src/hooks/menuItemsHooks/useNewResourceMenuItems.tsx
  src/index.css
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/models/resourceCreate.ts
  src/shared/models/telemetry.ts
  src/shared/models/ui.ts
Labels: size/XL

#4042 refactor: merge all/recent projects into projects page
  package-lock.json
  src/components/molecules/ProjectCard/ProjectCard.tsx
  src/components/molecules/ProjectsList/ProjectsList.tsx
  src/components/organisms/StartPage/StartPage.tsx
  src/hooks/useStartPageOptions.tsx
  src/shared/models/ui.ts
Labels: size/L

#4043 refactor: start page search input placeholder
  src/components/organisms/StartPage/StartPageHeader.tsx
Labels: size/XS

#4044 fix: improve helm error
  src/components/organisms/HelmRepoPane/HelmChartsView.tsx
  src/components/organisms/HelmRepoPane/styled.tsx
Labels: size/XS

#4047 fix: create resource and save to folder / append to file duplicate
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/redux/services/transientResource.ts
  src/redux/thunks/saveResourceToFileFolder.ts
  src/redux/thunks/saveTransientResources.ts
  src/shared/models/resourceCreate.ts
Labels: size/L

#4048 fix: editor sync external changes
  src/editor/enhancers/applyResourceEnhancers.ts
  src/editor/enhancers/index.ts
  src/editor/listeners/editorSelection.listener.ts
  src/editor/listeners/editorTextUpdate.listener.ts
  src/redux/selectors/helmGetters.ts
Labels: size/L

#4052 chore(release): 2.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#4061 fix: ai generate modal ui
  src/components/molecules/AIGenerationModal/AIGenerationModal.styled.tsx
  src/components/molecules/AIGenerationModal/AIGenerationModal.tsx
  src/components/molecules/FilterPopover/keyValueInput/KeyValueInput.style.ts
  src/components/organisms/CompareSyncPane/ComparisonList/ComparisonList.styled.tsx
  src/components/organisms/CompareSyncPane/ResourceList/ResourceList.styled.tsx
  src/hooks/menuItemsHooks/useHelpMenuItems.tsx
  src/shared/styles/colors.ts
Labels: size/M

#4062 fix: dashboard warnings/errors count
  src/components/organisms/Dashboard/Overview/Overview.styled.tsx
  src/components/organisms/Dashboard/Overview/Status.styled.tsx
  src/components/organisms/Dashboard/Overview/Status.tsx
Labels: size/M

#4064 fix: show files from explorer when opening a new project
  src/redux/reducers/ui.ts
Labels: size/XS

#4063 feat: active back to project button
  src/components/organisms/StartPage/StartPageHeader.styled.tsx
  src/components/organisms/StartPage/StartPageHeader.tsx
  src/shared/styles/borders.ts
Labels: size/M

#4071 chore: track unsuccessful AI generation
  src/components/molecules/AIGenerationModal/AIGenerationModal.tsx
  src/shared/models/telemetry.ts
Labels: size/S

#4074 feat: order of create resource options + disable in cluster mode
  src/components/organisms/NavigatorPane/EmptyResourceNavigator/EmptyResourceNavigator.tsx
  src/components/organisms/NavigatorPane/EmptyResourceNavigator/NewResourceCard.tsx
  src/hooks/menuItemsHooks/useNewResourceMenuItems.tsx
  src/shared/models/resourceCreate.ts
Labels: size/M

#4077 fix: add number of values files to open_project telemetry
  src/redux/thunks/setRootFolder.ts
  src/shared/models/telemetry.ts
Labels: size/XS

#4076 refactor: naming
  src/App.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationAdd.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationList.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationPane.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationQuickAction.tsx
  src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
  src/constants/tooltips.tsx
  src/redux/thunks/runPreviewConfiguration.ts
Labels: size/M

#4083 fix: form editor error when additionalProperties is undefined
  docs/docusaurus.config.js
  package-lock.json
  package.json
  src/redux/services/schema.ts
Labels: size/M

#4085 chore: remove performance notification
  src/assets/PerformanceIcon.svg
  src/components/organisms/GlobalModals/GlobalModals.tsx
Labels: size/M

#4087 fix: saving multiple resources with same name from template
  src/components/organisms/TemplateExplorer/CreatedResources/SaveToFolderModal.tsx
  src/hooks/useFolderTreeSelectData.ts
Labels: size/XS

#4088 feat: telemetry for logs search
  src/components/molecules/Logs/Logs.tsx
  src/shared/models/telemetry.ts
Labels: size/M

#4090 fix: toggle dashboard left menu
  src/components/organisms/PaneManager/PaneManager.tsx
Labels: size/XS

#4089 fix: add helm to start new project
  src/assets/newProject/FromHelm.svg
  src/components/organisms/GlobalModals/GlobalModals.tsx
  src/components/organisms/HelmRepoModal/HelmRepoModal.tsx
  src/components/organisms/HelmRepoModal/index.ts
  src/components/organisms/HelmRepoModal/styled.tsx
  src/components/organisms/NewProject/NewProject.tsx
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/models/ui.ts
Labels: size/L

#4094 fix: git publish local branch and commit
  src/components/organisms/GitPane/BottomActions.tsx
Labels: size/XS

#4095 [Snyk] Security upgrade semver from 7.5.1 to 7.5.2
  package.json
Labels: size/XS

#4093 improve telemetry
  package-lock.json
  src/components/organisms/NewProject/NewProject.tsx
  src/editor/editor.instance.ts
  src/editor/editor.types.ts
  src/editor/enhancers/helm/templates.ts
  src/editor/enhancers/helm/valuesFile.ts
  src/editor/enhancers/k8sResource/refs.ts
  src/editor/enhancers/k8sResource/symbols.ts
  src/redux/services/clusterDashboard.ts
  src/redux/thunks/project/createProject.ts
  src/redux/thunks/runPreviewConfiguration.ts
  src/redux/validation/validation.listeners.tsx
  src/shared/models/telemetry.ts
Labels: size/L

#4102 chore: fix editor error/warning hover telemetry
  src/editor/editor.instance.ts
Labels: size/XS

#4104 fix: only load selected chart versions
  src/components/organisms/HelmRepoPane/HelmChartDetails/HelmChartDetails.tsx
  src/redux/thunks/InstallHelmRepoChart.ts
  src/shared/utils/commands/helm.ts
Labels: size/M

#4107 fix: sync semver libe package-lock with package.json
  package-lock.json
Labels: size/XS

#4108 refactor: file isSupported -> containsK8sResources
  package-lock.json
  package.json
  public/.monokle
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNode.styled.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFile.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFolder.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/ResourceSetSelector/GitSelect/GitFolderSelect.tsx
  src/constants/constants.ts
  src/hooks/useFileSelectOptions.tsx
  src/redux/reducers/main/mainSlice.ts
  src/redux/selectors/fileMapGetters.ts
  src/redux/services/fileEntry.ts
  src/redux/services/helm.ts
  src/shared/constants/electronStore.ts
  src/shared/models/fileEntry.ts
  src/utils/files.ts
Labels: size/M

#4109 fix: allow editing of values files at all times
  src/components/organisms/ExplorerPane/HelmPane/HelmContextMenu.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmPane.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.styled.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.tsx
  src/redux/selectors.tsx
Labels: size/M

#4111 chore: improve validation telemetry
  src/redux/validation/validation.listeners.tsx
  src/shared/models/telemetry.ts
  src/utils/executionTime.ts
Labels: size/M

#4112 chore: update @monokle/components
  package-lock.json
  package.json
  src/components/organisms/ValidationPane/ValidationPane.tsx
  src/utils/downloadJson.ts
Labels: size/S
