Repository kubeshop/monokle, pull requests merged in 2023-04, with the labels that each got.

#3590 fix: remove disabled console warning
  src/components/organisms/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmPane.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizePane.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationPane.tsx
Labels: size/XS

#3591 fix: duplicate dispatch when open project
  src/redux/services/projectConfigMonitor.ts
Labels: size/XS

#3597 feat: performance notification
  src/App.tsx
  src/assets/PerformanceIcon.svg
  src/components/organisms/MessageBox/MessageBox.tsx
  src/shared/models/alert.ts
Labels: size/M

#3598 fix: replaced createSelector with createDeepEqualSelector
  src/redux/validation/validation.selectors.ts
Labels: size/S

#3599 Razvantopliceanu/refactor/notifications
  src/App.tsx
  src/redux/thunks/cluster/loadClusterResources.ts
  src/redux/thunks/setRootFolder.ts
Labels: size/S

#3604 refactor: selectors
  src/components/molecules/FormEditor/FormEditor.tsx
  src/redux/selectors.ts
Labels: size/M

#3607 fix: selectors dependencies
  src/redux/appConfig/appConfig.selectors.ts
  src/shared/utils/selectors.ts
Labels: size/S

#3605 fix: show resource status only in cluster mode
  src/components/organisms/NavigatorPane/ResourceRenderer/ResourceRenderer.tsx
Labels: size/S

#3609 fix: no ellipsis for helm chart name
  src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.styled.tsx
Labels: size/XS

#3596 fix: move global modals from app.tsx
  src/App.tsx
  src/components/organisms/GlobalModals/GlobalModals.tsx
  src/components/organisms/GlobalModals/index.ts
  src/components/organisms/index.ts
  src/utils/hooks.ts
Labels: size/L

#3615 chore: catch known errors
  package-lock.json
  package.json
  src/index.tsx
  src/utils/knownErrors.ts
Labels: size/S

#3620 fix: highlights after editing a kustomization
  src/redux/thunks/updateResource.ts
Labels: size/XS

#3534 fix: increase error badge size & add text next to it
  package-lock.json
  src/components/organisms/Dashboard/Tableview/ErrorCell.styled.tsx
  src/components/organisms/Dashboard/Tableview/ErrorCell.tsx
Labels: size/M

#3625 Erdikose/fix/following link cluster view
  src/components/organisms/DashboardPane/DashboardPane.style.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/components/organisms/DashboardPane/MenuItem.tsx
Labels: size/L

#3627 feat: redesign refs popover
  src/assets/GraphIcon.svg
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.styled.tsx
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/redux/initialState.ts
  src/redux/reducers/main/mainSlice.ts
  src/shared/models/appState.ts
Labels: size/L

#3632 refactor: message
  src/components/organisms/GlobalModals/GlobalModals.tsx
Labels: size/XS

#3572 feat: add ipc framework
  .eslintrc.js
  electron/app/services/cluster/handlers/index.ts
  electron/app/services/cluster/handlers/ping.ts
  electron/app/services/cluster/ipc.ts
  electron/app/utils/ipc.ts
  src/redux/cluster/service/ping.ts
  src/shared/ipc/cluster.ts
  src/shared/ipc/core.ts
  src/shared/ipc/index.ts
  src/utils/ipc.ts
Labels: size/M

#3628 feat: add resource popover
  src/components/molecules/ResourcePopover/ResourcePopover.styled.tsx
  src/components/molecules/ResourcePopover/ResourcePopover.tsx
  src/components/molecules/ResourcePopover/index.ts
  src/components/organisms/NavigatorPane/ResourceRenderer/ResourceRenderer.tsx
Labels: size/L

#3614 refactor: git clone modal
  src/components/organisms/GitCloneModal/GitCloneModal.tsx
  src/constants/constants.ts
Labels: size/M

#3623 chore: remove bulk cluster connection notifications on access check
  electron/app/KubeConfigManager.ts
  src/components/organisms/SettingsPane/Settings/Settings.tsx
  src/shared/utils/kubeclient.ts
Labels: size/M

#3638 Olelensmar/fix/valid resource content
  src/hooks/useResourceYamlSchema.ts
  src/redux/reducers/main/mainSlice.ts
  src/redux/services/fileEntry.ts
  src/redux/services/resource.ts
  src/redux/thunks/updateResource.ts
Labels: size/M

#3639 fix: listener for removing terminal
  src/components/organisms/BottomPaneManager/BottomPaneManager.tsx
  src/redux/reducers/terminal.ts
  src/redux/store.ts
Labels: size/S

#3621 refactor: electron subscribe to store state
  electron/app/createWindow.ts
  electron/app/ipc/ipcListeners.ts
  electron/app/ipc/ipcMainRedux.ts
  electron/app/menu.ts
  electron/app/setWindowTitle.ts
  src/components/organisms/SettingsPane/GlobalSettings/GlobalSettings.tsx
  src/redux/appConfig/appConfig.slice.ts
  src/redux/ipcRendererRedux.ts
  src/shared/models/rootState.ts
  src/shared/utils/selectors.ts
  src/shared/utils/types.ts
  src/utils/index.ts
Labels: size/L

#3636 fix: preview configurations
  src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartCollapse.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.styled.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.styled.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/HelmChartRenderer/HelmChartCollapse.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/HelmChartRenderer/HelmChartRenderer.styled.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/HelmChartRenderer/HelmChartRenderer.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationAdd.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationList.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationPane.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationRenderer.styled.tsx
  src/components/organisms/PreviewConfigurationEditor/PreviewConfigurationEditor.tsx
  src/redux/appConfig/appConfig.slice.ts
  src/redux/selectors/helmSelectors.ts
  src/redux/services/projectConfig.ts
  src/redux/services/projectConfigMonitor.ts
  src/redux/thunks/previewConfiguration.ts
  src/shared/utils/projectConfig.ts
Labels: size/L

#3640 fix: duplicate extra reducer
  src/redux/reducers/main/mainSlice.ts
  src/redux/reducers/main/selectionReducers.ts
Labels: size/M

#3641 fix: add appVersion to all telemetry events
  electron/app/ipc/ipcListeners.ts
  src/shared/utils/telemetry.ts
Labels: size/S

#3642 chore(release): 2.0.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/M

#3643 fix: bugs/improvements
  src/components/molecules/Monaco/Monaco.tsx
  src/components/organisms/GitCloneModal/GitCloneModal.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/redux/parsing/parser.thunks.ts
Labels: size/S

#3666 [Snyk] Upgrade rooks from 7.4.3 to 7.6.1
  package-lock.json
  package.json
Labels: size/XS

#3682 chore: update package-lock
  package-lock.json
  package.json
Labels: size/XS

#3677 fix: make tab heights consistent
  src/components/atoms/TabHeader/TabHeader.styled.tsx
Labels: size/XS

#3678 fix: disabe recource create dropdown
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
Labels: size/XS

#3679 fix: remove scrollbar from filter when it is not opened
  src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
Labels: size/XS

#3675 Erdikose/fix/3645 switching between templates retains formdata
  src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
Labels: size/XS

#3685 refactor: show by resource only in preview mode
  src/components/organisms/ValidationPane/ValidationPane.tsx
Labels: size/XS

#3662 fix: git clone
  src/components/organisms/GitCloneModal/GitCloneModal.tsx
Labels: size/XS

#3673 fix: stay selected left menu when cluster namespace changed
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/components/organisms/DashboardPane/MenuItem.tsx
  src/redux/dashboard/slice.ts
Labels: size/L

#3692 fix: filter on folder
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
Labels: size/M

#3403 fix: format form data
  src/components/organisms/TemplateExplorer/TemplateForm/TemplateForm.tsx
  src/shared/utils/index.ts
  src/shared/utils/templateForm.ts
Labels: size/S

#3676 feat: enable showing relations in Graph view for files
  src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/M

#3690 fix: edit kustomize during previews
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/useDebouncedCodeSave.ts
Labels: size/S

#3686 fix: improve validation when entering previews
  src/redux/reducers/main/previewReducers.ts
  src/redux/services/preview.ts
  src/redux/validation/validation.listeners.tsx
Labels: size/M

#3700 fix: accordions loading when switching projects
  src/components/organisms/ExplorerPane/HelmPane/HelmList.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImagesList.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationList.tsx
Labels: size/M

#3702 chore: recreate package-lock
  package-lock.json
Labels: size/XS

#3709 fix: fixed documentation links in cluster dashboard
  src/components/organisms/Dashboard/Overview/InventoryInfo.tsx
  src/constants/constants.ts
Labels: size/S

#3659 fix: enhance toggle explore pane performance
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
  src/redux/selectors.ts
  src/utils/fileExplorer.ts
Labels: size/L

#3711 fix: added possibility to order projects by name and lastOpened
  src/components/molecules/ProjectsList/ProjectsList.tsx
Labels: size/S

#3703 fix: graph view visiblity
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/XS

#3671 fix: memoize NewResourceWizard component
  src/components/organisms/NavigatorPane/EmptyResourceNavigator.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
Labels: size/S

#3719 fix: resize columns without lose its state
  package-lock.json
  package.json
Labels: size/XS

#3724 fix: packages
  .node-version
  package-lock.json
  package.json
Labels: size/S

#3725 chore: update versions
  .node-version
  .npmrc
  .nvmrc
  package-lock.json
  package.json
Labels: size/S

#3726 chore: update codeowners
  .github/CODEOWNERS
Labels: size/XS

#3727 fix: helm preview configurations
  src/redux/appConfig/appConfig.slice.ts
  src/redux/services/projectConfig.ts
Labels: size/S

#3729 fix: bring events back & prevent autoclose of cluster drawer
  src/components/organisms/Dashboard/Tableview/Tableview.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
Labels: size/S

#3723 fix: find helm resource by file path
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFile.tsx
  src/hooks/resourceHooks/useInstallDeploy.ts
  src/redux/selectors.ts
Labels: size/M

#3733 fix: update selector dependencies
  src/redux/selectors/resourceMapSelectors.ts
Labels: size/XS

#3738 chore: add manual prereleases
  .github/workflows/monokle-build-nightly.yml
Labels: size/M

#3701 fix(docs): update to include .rpm binaries
  README.md
  docs/docs/getting-started.md
Labels: size/XS

#3720 fix: improved handling of transient resources
  src/components/organisms/NavigatorPane/KindRenderer/ResourceCounter.tsx
  src/components/organisms/NavigatorPane/NavigatorDescription.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/components/organisms/TemplateExplorer/TemplateForm/TemplateForm.tsx
  src/redux/reducers/main/mainSlice.ts
  src/redux/selectors/resourceSelectors.ts
  src/redux/services/compare/transferResource.ts
  src/redux/services/templates.ts
  src/redux/services/transientResource.ts
  src/redux/thunks/previewReferencedHelmChart.ts
  src/shared/models/origin.ts
Labels: size/L

#3743 refactor: default 1.26.3 version
  resources/schemas/1.26.3.json
  src/shared/constants/k8s.ts
Labels: size/S

#3745 fix: reload cluster namespaces list on cluster connection
  src/hooks/useTargetClusterNamespaces.ts
Labels: size/S

#3746 fix: hide namespace resource filter in cluster mode
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
Labels: size/S

#3744 fix: consistent YAML parsing/stringification and octal formatting
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/redux/services/__test__/yaml.test.ts
  src/redux/services/manifest-utils.ts
  src/redux/services/transientResource.ts
  src/redux/thunks/applyMultipleResources.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/renameResource.ts
  src/redux/thunks/utils.ts
  src/utils/crds.ts
  src/utils/yaml.ts
Labels: size/L

#3734 fix: validation resources count
  src/components/organisms/NavigatorPane/NavigatorDescription.tsx
  src/redux/selectors/resourceSelectors.ts
  src/redux/validation/validation.selectors.ts
Labels: size/M

#3748 chore(release): 2.0.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/M

#3749 chore: hide ResizeObserver webpack errors
  package.json
  patches/webpack-dev-server+4.13.2.patch
Labels: size/S

#3750 refactor: resource icon tooltip delay
  src/components/organisms/NavigatorPane/ResourceRenderer/ResourceInfoIcon.tsx
  src/utils/yaml.ts
Labels: size/XS

#3751 fix: empty editor image
  src/assets/CurlyArrow.svg
  src/assets/DiscordLogo.svg
  src/assets/ErrorIcon.svg
  src/assets/FolderSmallPlusWhite.svg
  src/assets/FolderSmallWhite.svg
  src/assets/MonacoPlaceholderImage.svg
  src/assets/MonacoPlaceholderImageNew.svg
  src/assets/MonokleStartupBackground.svg
  src/assets/MonokleWarning.svg
  src/assets/OpenPolicyAgentIcon.svg
  src/assets/PlusIcon.svg
  src/assets/QuickClusterPreview.svg
  src/assets/SelectAnEmptyProject.svg
  src/assets/SelectAnExistingFolder.svg
  src/assets/StartBackground.svg
  src/assets/StartFromTemplate.svg
  src/assets/TemplateIcon.svg
  src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.styled.tsx
  src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.tsx
Labels: size/L

#3752 chore: update package-lock
  package-lock.json
Labels: size/XS

#3767 fix: crash when clicking on some resource from cluster list
  src/components/organisms/Dashboard/Tableview/InfoTab.tsx
Labels: size/XS

#3769 fix: menu list
  src/components/organisms/DashboardPane/DashboardPane.tsx
Labels: size/S

#3772 chore: add readme
  .github/README.md
Labels: size/L

#3775 chore: change name
  .github/documentation.md
Labels: size/XS

#3771 fix: overview rerendering
  src/components/organisms/DashboardPane/DashboardFilteredMenu.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
  src/components/organisms/DashboardPane/MenuItem.tsx
Labels: size/L

#3776 refactor: improve dashboard
  src/components/organisms/Dashboard/Overview/Status.tsx
  src/components/organisms/DashboardPane/DashboardPane.tsx
Labels: size/L

#3779 fix: remove watchers when reloading resources
  src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx
  src/redux/reducers/main/mainSlice.ts
Labels: size/XS

#3782 fix: kubeconfig isValid
  electron/app/services/cluster/daemons/kubeconfigWatcher.ts
  electron/kubernetes/ProxyInstance.ts
  src/components/organisms/SettingsPane/Settings/Settings.tsx
  src/shared/models/config.ts
Labels: size/M

#3795 fix: removing file shows git error modal
  src/redux/services/fileMonitor.ts
Labels: size/XS

#3792 fix: fixed deletion of resources
  src/redux/thunks/removeResources.ts
Labels: size/XS

#3797 fix: editor titlebar styling
  package-lock.json
  package.json
  src/components/atoms/StyledComponents/TitleBarWrapper.tsx
  src/components/atoms/TabHeader/TabHeader.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
Labels: size/S

#3800 feat: root folder node
  src/components/atoms/Dots/Dots.styled.tsx
  src/components/organisms/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFolder.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/index.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/index.css
  src/redux/selectors.tsx
  src/utils/git.ts
Labels: size/M

#3805 refactor: on open project show explorer
  src/redux/reducers/ui.ts
Labels: size/XS

#3803 fix: title bar
  package-lock.json
  package.json
  src/components/atoms/StyledComponents/TitleBarWrapper.tsx
  src/components/molecules/FormEditor/FormEditor.styled.tsx
  src/components/molecules/FormEditor/FormObjectFieldTemplate.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.styled.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/CompareSyncPane/CompareSyncPane.styled.tsx
  src/components/organisms/ExplorerPane/AccordionPanel/AccordionTitleBarContainer.tsx
  src/components/organisms/ExplorerPane/ExplorerPane.tsx
  src/components/organisms/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFolder.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmPane.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImagesPane.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizePane.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationPane.tsx
  src/components/organisms/GitPane/GitPane.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/ValidationPane/ValidationPane.styled.tsx
  src/components/organisms/ValidationPane/ValidationPane.tsx
Labels: size/L

#3808 fix: maintains resizable columns
  package-lock.json
  package.json
  src/components/organisms/PaneManager/PaneManager.tsx
Labels: size/XS

#3809 feat: new version header notification
  src/components/molecules/NewVersionNotice/NewVersionNotice.tsx
  src/components/molecules/NewVersionNotice/index.ts
  src/components/molecules/index.ts
  src/components/organisms/GlobalModals/GlobalModals.tsx
  src/components/organisms/PageHeader/PageHeader.styled.tsx
  src/components/organisms/PageHeader/PageHeader.tsx
  src/components/organisms/StartPage/StartPageHeader.styled.tsx
  src/components/organisms/StartPage/StartPageHeader.tsx
  src/components/organisms/UpdateNotice/UpdateNotice.styled.tsx
  src/components/organisms/UpdateNotice/UpdateNotice.tsx
  src/components/organisms/UpdateNotice/index.ts
  src/components/organisms/index.ts
  src/index.css
  src/redux/appConfig/appConfig.slice.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/models/config.ts
  src/shared/models/ui.ts
Labels: size/L

#3815 fix: disable add resource in cluster mode + add tooltip
  src/components/organisms/NavigatorPane/KindRenderer/KindSuffix.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/NavigatorPane/ResourceRenderer/ResourceRenderer.styled.tsx
  src/constants/tooltips.tsx
Labels: size/M

#3816 fix: transferred resources when switching projects
  src/components/molecules/ProjectCard/ProjectCard.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
Labels: size/XS

#3764 WIP: Refactor the Code Editor
  package-lock.json
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/editor/CodeEditor/CodeEditor.styled.tsx
  src/editor/CodeEditor/CodeEditor.tsx
  src/editor/CodeEditor/handleCodeChanges.ts
  src/editor/CodeEditor/index.ts
  src/editor/editor.constants.ts
  src/editor/editor.d.ts
  src/editor/editor.instance.ts
  src/editor/editor.slice.ts
  src/editor/editor.theme.ts
  src/editor/editor.types.ts
  src/editor/editor.utils.ts
  src/editor/enhancers/createEnhancer.ts
  src/editor/enhancers/helm/templates.ts
  src/editor/enhancers/helm/utils.ts
  src/editor/enhancers/helm/valuesFile.ts
  src/editor/enhancers/index.ts
  src/editor/enhancers/k8sResource/refs.ts
  src/editor/enhancers/k8sResource/symbols.ts
  src/editor/enhancers/k8sResource/validation.ts
  src/editor/listeners/editorDispose.listener.ts
  src/editor/listeners/editorSelection.listener.ts
  src/editor/listeners/editorTextUpdate.listener.ts
  src/editor/listeners/editorValidation.listener.ts
  src/editor/listeners/index.ts
  src/redux/reducers/main/mainSlice.ts
  src/redux/selectors/resourceSelectors.ts
  src/redux/services/fileEntry.ts
  src/redux/store.ts
  src/redux/thunks/multiplePathsChanged.ts
  src/redux/thunks/updateFileEntry.ts
  src/redux/thunks/updateResource.ts
  tsconfig.paths.json
Labels: size/XXL

#3817 fix: formatting or removal of timestamp properties retrieved from cluster
  src/redux/thunks/utils.ts
Labels: size/M

#3818 Olelensmar/fix/expand all kinds
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/redux/reducers/ui.ts
  src/redux/selectors/resourceMapSelectors.ts
Labels: size/M

#3820 refactor: add Windows specific messages when throwing errors
  electron/app/services/cluster/handlers/setup.ts
  electron/kubernetes/ProxyInstance.ts
Labels: size/S

#3784 fix: handling side effects from removing files or resources
  src/redux/reducers/main/mainSlice.ts
  src/redux/validation/validation.listeners.tsx
Labels: size/S

#3821 fix: don't try expanding on root click ( file tree )
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
Labels: size/XS

#3822 chore(release): 2.0.10
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/M
