Repository kubeshop/monokle, pull requests merged in 2023-03, with the labels that each got.

#3338 fix: fixing problems in editor
  package-lock.json
  package.json
  src/components/organisms/ValidationPane/ValidationPane.tsx
  src/hooks/menuItemsHooks/useProblemPaneMenuItems.tsx
Labels: size/M

#3339 feat: add Discord link to header
  docs/docusaurus.config.js
  docs/src/css/custom.css
  docs/static/img/NewMonokleLogoDark.svg
Labels: size/M

#3340 chore(release): 2.0.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#3341 fix: github actions
  .github/workflows/monokle-publish-downloads.yml
  .github/workflows/monokle-publish-updater.yml
  package-lock.json
  package.json
Labels: size/XS

#3342 chore(release): 2.0.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#3344 fix: ValidationOverview resizable width
  package-lock.json
  package.json
Labels: size/XS

#3349 chore: update
  package-lock.json
  package.json
Labels: size/XS

#3352 fix: readme icons
  README.md
Labels: size/XS

#3350 chore: update styled-components
  package-lock.json
  package.json
Labels: size/XS

#3353 fix: show refs on first validation
  src/redux/validation/validation.thunks.ts
Labels: size/XS

#3358 fix: settings
  src/components/organisms/SettingsPane/SettingsPane.styled.tsx
  src/components/organisms/SettingsPane/SettingsPane.tsx
Labels: size/S

#3360 feat: redux selected explorer section
  src/components/organisms/ExplorerPane/ExplorerPane.tsx
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/models/ui.ts
Labels: size/S

#3354 feat: compare single file
  src/App.tsx
  src/components/atoms/SelectItemImage/SelectItemImage.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
  src/components/organisms/FileCompareModal/FileCompareModal.styled.tsx
  src/components/organisms/FileCompareModal/FileCompareModal.tsx
  src/components/organisms/FileCompareModal/index.ts
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/components/organisms/ResourceSetSelector/GitSelect/GitFolderSelect.tsx
  src/components/organisms/ResourceSetSelector/LocalSelect/LocalSelect.tsx
  src/components/organisms/TemplateExplorer/CreatedResources/SaveToFolderModal.tsx
  src/components/organisms/index.ts
  src/hooks/useFileSelectOptions.tsx
  src/hooks/useFolderTreeSelectData.ts
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/models/ui.ts
Labels: size/L

#3365 chore: update monokle/components
  package-lock.json
  package.json
Labels: size/XS

#3366 fix: disable section + hide git pane in cluster mode
  src/components/organisms/ExplorerPane/AccordionPanel/AccordionPanel.tsx
  src/components/organisms/ExplorerPane/ExplorerPane.tsx
  src/components/organisms/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmPane.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizePane.tsx
  src/components/organisms/PaneManager/activities.tsx
Labels: size/S

#3367 fix: settings tabs
  src/components/organisms/SettingsPane/SettingsPane.tsx
Labels: size/XS

#3359 fix: watch global kubeconf and project kubeconf
  electron/app/initKubeconfig.ts
  src/redux/appConfig/appConfig.listeners.ts
  src/redux/appConfig/appConfig.selectors.ts
Labels: size/L

#3371 chore(release): 2.0.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#2654 feat(rpm): Addition of rpm release
  .gitignore
  package.json
Labels: size/S

#3362 Editor placeholder update
  src/assets/MonacoPlaceholderImageNew.svg
  src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.styled.tsx
  src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.tsx
  src/redux/appConfig/appConfig.listeners.ts
Labels: size/L

#3374 chore: update to latest version of validation
  craco.config.js
  package-lock.json
  package.json
Labels: size/XS

#3375 fix: navigate to error in manifest tab
  craco.config.js
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.styled.tsx
  src/components/organisms/Dashboard/Tableview/ErrorCell.tsx
  src/components/organisms/Dashboard/Tableview/Tableview.tsx
Labels: size/M

#3376 refactor: on errors/warnings click show validation pane
  src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.tsx
  src/components/organisms/Dashboard/Overview/Status.styled.tsx
  src/components/organisms/Dashboard/Overview/Status.tsx
  src/components/organisms/PaneManager/activities.tsx
  src/components/organisms/ValidationPane/ValidationPane.styled.tsx
  src/components/organisms/ValidationPane/ValidationPane.tsx
  src/constants/tooltips.tsx
  src/redux/reducers/ui.ts
  src/redux/store.ts
Labels: size/L

#3372 feat: handle Image pull errors
  src/components/organisms/Dashboard/Dashboard.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/TableCells.tsx
Labels: size/M

#3381 feat: back to dashboard button
  src/components/organisms/ValidationPane/ValidationPane.styled.tsx
  src/components/organisms/ValidationPane/ValidationPane.tsx
Labels: size/S

#3384 fix: dependencies
  package-lock.json
  package.json
Labels: size/XS

#3387 feat: show alert when opening project if in cluster mode
  src/components/molecules/ProjectCard/ProjectCard.styled.tsx
  src/components/molecules/ProjectCard/ProjectCard.tsx
  src/redux/initialState.ts
  src/redux/reducers/ui.ts
  src/shared/constants/electronStore.ts
  src/shared/models/ui.ts
Labels: size/M

#3391 chore(release): 2.0.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#3394 Update README.md
  README.md
Labels: size/XS

#3405 feat: add rpm binaries to releases
  .github/workflows/monokle-build-nightly.yml
  .github/workflows/monokle-publish-downloads.yml
  .github/workflows/monokle-publish-test.yml
  .github/workflows/monokle-publish-updater.yml
  .github/workflows/monokle-publish.yml
Labels: size/S

#3407 fix: made all skeleton active
  src/components/molecules/ImageDetails/ImageDetails.tsx
  src/components/molecules/ImageDetails/ImageTags.tsx
  src/components/molecules/SectionRenderer/SectionRenderer.tsx
  src/components/molecules/TemplateFormRenderer/TemplateFormRenderer.tsx
  src/components/organisms/PaneManager/PaneManager.tsx
  src/components/organisms/ReleaseNotes/ReleaseNotes.tsx
  src/components/organisms/SettingsPane/PluginsManager/PluginManager.tsx
Labels: size/S

#3378 Fixed clicking outside resource label not selecting the item
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
Labels: size/XS

#3409 feat: resource graph
  src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx
  src/components/molecules/ResourceGraphTab/index.ts
  src/components/molecules/index.ts
  src/components/organisms/ActionsPane/ActionsPane.tsx
Labels: size/M

#3410 feat: default open/ auto focus dropdowns in compare
  src/components/organisms/ResourceSetSelector/ClusterContextSelect.tsx
  src/components/organisms/ResourceSetSelector/CommandSelect/CommandSelect.tsx
  src/components/organisms/ResourceSetSelector/GitSelect/GitBranchSelect.tsx
  src/components/organisms/ResourceSetSelector/HelmSelect/HelmChartSelect.tsx
  src/components/organisms/ResourceSetSelector/KustomizeSelect.tsx
Labels: size/S

#3413 fix: windows kustomization refs
  src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx
  src/redux/parsing/parser.thunks.ts
  src/redux/validation/validation.thunks.ts
  src/utils/resources.ts
Labels: size/S

#3414 fix: refs file path
  src/redux/parsing/parser.thunks.ts
  src/utils/resources.ts
Labels: size/S

#3415 refactor: proxy connection
  src/redux/appConfig/appConfig.listeners.ts
  src/redux/appConfig/appConfig.slice.ts
  src/redux/reducers/main/clusterListeners.ts
  src/redux/store.ts
  src/redux/thunks/cluster/loadClusterResources.ts
  src/redux/thunks/cluster/startClusterConnection.ts
Labels: size/L

#3416 fix: show alert when no resources are created on preview
  src/redux/thunks/previewKustomization.ts
Labels: size/XS

#3418 chore(release): 2.0.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#3419 Razvantopliceanu/fix/versions
  .github/workflows/monokle-publish-downloads.yml
  .github/workflows/monokle-publish-test.yml
  .github/workflows/monokle-publish-updater.yml
  package-lock.json
  package.json
Labels: size/S

#3420 chore(release): 2.0.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/M

#3423 chore: update monokle/components
  package-lock.json
  package.json
Labels: size/XS

#3437 refactor: navigator header
  package-lock.json
  package.json
  src/components/atoms/StyledComponents/TitleBarWrapper.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
  src/components/organisms/NavigatorPane/KindRenderer/KindRenderer.styled.tsx
  src/components/organisms/NavigatorPane/NavigatorDescription.styled.tsx
  src/components/organisms/NavigatorPane/NavigatorDescription.tsx
  src/components/organisms/NavigatorPane/NavigatorPane.tsx
  src/components/organisms/NavigatorPane/NavigatorTitle.tsx
  src/components/organisms/NavigatorPane/ResourceRenderer/ResourceRenderer.styled.tsx
Labels: size/M

#3436 fix: remove show cluster selector setting
  src/components/organisms/PageHeader/ClusterSelection.tsx
  src/components/organisms/SettingsPane/GlobalSettings/GlobalSettings.tsx
  src/redux/appConfig/appConfig.slice.ts
  src/redux/initialState.ts
  src/shared/constants/electronStore.ts
  src/shared/models/config.ts
Labels: size/S

#3442 fix: select resource on ref link click
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
Labels: size/XS

#3439 fix: duplicated keys
  src/components/organisms/StartPage/StartPageHeader.tsx
Labels: size/XS

#3435 fix: read only kustomize
  src/components/molecules/Monaco/Monaco.tsx
Labels: size/S

#3450 fix: is non resource file if the file is excluded
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
Labels: size/XS

#3454 fix: persist resource refs after live cluster update
  src/components/molecules/Monaco/editorHelpers.ts
  src/redux/reducers/main/mainSlice.ts
  src/redux/services/resource.ts
Labels: size/S

#3491 fix: filter on this file
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
Labels: size/S

#3489 fix: bugs and improvements
  src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/ItemRenderer.tsx
  src/components/molecules/SectionRenderer/ItemRenderer/styled.tsx
  src/components/organisms/ExplorerPane/ExplorerPane.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmPane.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImagesPane.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizePane.tsx
  src/components/organisms/PaneManager/activities.tsx
  src/components/organisms/SettingsPane/PluginsManager/PluginManager.styled.tsx
  src/components/organisms/SettingsPane/PluginsManager/PluginManager.tsx
  src/components/organisms/SettingsPane/Settings/Settings.tsx
  src/constants/constants.ts
  src/hooks/menuItemsHooks/useHelpMenuItems.tsx
  src/navsections/HelmChartSectionBlueprint/HelmChartContextMenu.tsx
  src/shared/models/explorer.ts
Labels: size/L

#3496 fix: select from history thunk + selection fix
  electron/app/menu.ts
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizePane.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/redux/thunks/selectFromHistory.ts
  src/shared/utils/selectionHistory.ts
Labels: size/L

#3497 refactor: start page left menu
  src/components/organisms/StartPage/StartPage.styled.tsx
  src/components/organisms/StartPage/StartPageHeader.styled.tsx
  src/components/organisms/StartPage/StartPageHeader.tsx
  src/hooks/useStartPageOptions.tsx
Labels: size/M

#3499 feat: validation pane filters
  package-lock.json
  package.json
  src/components/molecules/ResourceFilter/ResourceFilter.styled.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/organisms/NavigatorPane/NavigatorDescription.styled.tsx
  src/components/organisms/NavigatorPane/NavigatorDescription.tsx
  src/components/organisms/ValidationPane/ValidationPane.tsx
  src/redux/validation/validation.initialState.ts
  src/redux/validation/validation.slice.ts
  src/shared/models/validation.ts
Labels: size/M

#3513 fix: open on github remote url
  electron/app/git/git.ts
Labels: size/XS

#3515 fix: select line number for resource problem
  src/components/molecules/Monaco/Monaco.tsx
Labels: size/XS

#3520 refactor: images map
  electron/app/menu.ts
  src/components/molecules/FormEditor/FormWidgets/ImageSelection.tsx
  src/components/molecules/ImageDetails/ImageDetails.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/Monaco/useCodeIntel.ts
  src/components/molecules/ResourceRefsIconPopover/RefsPopoverContent.tsx
  src/components/molecules/ResourceRefsIconPopover/ResourceRefsIconPopover.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImagesPane.tsx
  src/components/organisms/ReplaceImageModal/ReplaceImageModal.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionBlueprint.ts
  src/redux/initialState.ts
  src/redux/reducers/main/imageListeners.ts
  src/redux/reducers/main/imageReducers.ts
  src/redux/reducers/main/mainSlice.ts
  src/redux/reducers/main/selectionReducers.ts
  src/redux/selectors.ts
  src/redux/thunks/selectFromHistory.ts
  src/shared/models/appState.ts
  src/shared/utils/selectionHistory.ts
Labels: size/L

#3527 [Snyk] Upgrade monaco-editor from 0.35.0 to 0.36.1
  package-lock.json
  package.json
Labels: size/XS

#3528 [Snyk] Upgrade framer-motion from 9.0.4 to 9.1.7
  package-lock.json
  package.json
Labels: size/XS

#3529 [Snyk] Upgrade @reduxjs/toolkit from 1.9.2 to 1.9.3
  package-lock.json
  package.json
Labels: size/XS

#3531 [Snyk] Upgrade antd from 4.24.7 to 4.24.8
  package-lock.json
  package.json
Labels: size/XS

#3517 fix: autosaving status
  src/components/molecules/Monaco/Monaco.tsx
  src/redux/reducers/main/mainSlice.ts
Labels: size/S

#3509 fix: improve log tab performance & track to latest appeared log
  src/components/molecules/Logs/Logs.tsx
Labels: size/S

#3536 refactor: remove full resource map selectors
  src/components/molecules/CheckedResourcesActionsMenu/CheckedResourcesActionsMenu.tsx
  src/components/molecules/FormEditor/FormWidgets/PodSelectorSelection.tsx
  src/components/molecules/ResourceDiff/ResourceDiff.tsx
  src/components/molecules/ResourceGraphTab/ResourceGraphTab.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ClusterResourceDiffModal/ClusterResourceDiffModal.tsx
  src/components/organisms/Dashboard/Overview/Activity.tsx
  src/components/organisms/Dashboard/Overview/InventoryInfo.tsx
  src/components/organisms/Dashboard/Overview/Utilization.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/Dashboard/Tableview/InfoTab.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/LocalResourceDiffModal/LocalResourceDiffModal.tsx
  src/components/organisms/NavigatorPane/ResourceRenderer/ResourceContextMenu.tsx
  src/components/organisms/ReplaceImageModal/ReplaceImageModal.tsx
  src/redux/selectors/resourceMapSelectors.ts
  src/redux/thunks/applyResource.ts
  src/redux/thunks/replaceImageTag.ts
  src/redux/thunks/utils.ts
Labels: size/XL

#3535 refactor: images virtualization
  src/components/molecules/ImageDetails/ImageDetails.styled.tsx
  src/components/molecules/ImageDetails/ImageDetails.tsx
  src/components/organisms/ExplorerPane/AccordionPanel/AccordionPanel.styled.tsx
  src/components/organisms/ExplorerPane/ExplorerPane.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImageFilteredTag.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImageRenderer/ImageOutgoingResourcesPopover.styled.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImageRenderer/ImageOutgoingResourcesPopover.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImageRenderer/ImageQuickAction.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImageRenderer/ImageRenderer.styled.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImageRenderer/ImageRenderer.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImageRenderer/ImageSuffix.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImageSearch.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImagesList.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImagesPane.tsx
  src/components/organisms/ExplorerPane/ImagesPane/useScroll.tsx
  src/navsections/ImagesSectionBlueprint/ImagesQuickAction.styled.tsx
  src/navsections/ImagesSectionBlueprint/ImagesQuickAction.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionBlueprint.ts
  src/navsections/ImagesSectionBlueprint/ImagesSectionEmptyDisplay.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.styled.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameDisplay.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameSuffix.styled.tsx
  src/navsections/ImagesSectionBlueprint/ImagesSectionNameSuffix.tsx
  src/navsections/ImagesSectionBlueprint/index.ts
  src/redux/reducers/main/selectionReducers.ts
  src/redux/selectors/imageSelectors.ts
  src/redux/services/image.ts
  src/shared/models/appState.ts
Labels: size/XL

#3561 refactor: react improvements
  package-lock.json
  package.json
  src/App.tsx
  src/components/atoms/ContextMenu/ContextMenu.tsx
  src/components/atoms/KeyValueInput/KeyValueInput.tsx
  src/components/molecules/ChangeFiltersConfirmModal/ChangeFiltersConfirmModal.tsx
  src/components/molecules/FormEditor/FormEditor.tsx
  src/components/molecules/FormEditor/FormWidgets/SecretKindResourceForm.tsx
  src/components/molecules/ImageDetails/ImageTags.tsx
  src/components/molecules/ResourceFilter/ResourceFilter.tsx
  src/components/organisms/ExplorerPane/FilePane/FilePane.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFile.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFolder.tsx
  src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/index.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmChartRenderer/HelmChartRenderer.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmList.tsx
  src/components/organisms/ExplorerPane/HelmPane/HelmValueRenderer/HelmValueRenderer.tsx
  src/components/organisms/ExplorerPane/HelmPane/useScroll.ts
  src/components/organisms/ExplorerPane/ImagesPane/ImageRenderer/ImageRenderer.tsx
  src/components/organisms/ExplorerPane/ImagesPane/ImagesList.tsx
  src/components/organisms/ExplorerPane/ImagesPane/useScroll.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeHeaderRenderer/KustomizeHeaderRenderer.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeList.tsx
  src/components/organisms/ExplorerPane/KustomizePane/KustomizeRenderer/KustomizeRenderer.tsx
  src/components/organisms/ExplorerPane/KustomizePane/useScroll.ts
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationList.tsx
  src/components/organisms/ExplorerPane/PreviewConfigurationPane/PreviewConfigurationRenderer/PreviewConfigurationRenderer.tsx
  src/components/organisms/GitPane/FileList.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/NavigatorPane/KindRenderer/KindRenderer.tsx
  src/components/organisms/NavigatorPane/ResourceRenderer/ResourcePrefix.tsx
  src/components/organisms/NavigatorPane/ResourceRenderer/ResourceRenderer.tsx
  src/components/organisms/NavigatorPane/ResourceRenderer/ResourceSuffix.tsx
  src/components/organisms/NavigatorPane/useScroll.tsx
  src/components/organisms/PreviewConfigurationEditor/HelmChartSelect.tsx
  src/components/organisms/SettingsPane/DefaultProjectSettings/DefaultProjectSettings.tsx
  src/components/organisms/SettingsPane/Settings/Settings.tsx
  src/components/organisms/TemplateExplorer/TemplateCollapseItem/TemplateCollapseItem.tsx
  src/components/organisms/ValidationPane/ValidationPane.styled.tsx
  src/components/organisms/ValidationPane/ValidationPane.tsx
  src/hooks/menuItemsHooks/useProblemPaneMenuItems.tsx
  src/redux/appConfig/appConfig.slice.ts
  src/redux/reducers/main/filterReducers.ts
  src/redux/reducers/main/imageListeners.ts
  src/redux/reducers/main/mainSlice.ts
  src/redux/selectors/utils.ts
  src/redux/services/projectConfig.ts
  src/redux/thunks/removeResources.ts
  src/redux/thunks/updateMultipleResources.ts
  src/redux/thunks/updateResource.ts
  src/redux/validation/validation.listeners.tsx
  src/redux/validation/validation.slice.ts
  src/shared/utils/isEqual.ts
  src/utils/resources.ts
Labels: size/L

#3562 Olelensmar/fix/more telemetry
  electron/app/openApplication.ts
  src/redux/thunks/setRootFolder.ts
  src/shared/models/telemetry.ts
Labels: size/S

#3568 fix: update cluster resources errors
  src/components/organisms/Dashboard/Tableview/Drawer.styled.tsx
  src/components/organisms/Dashboard/Tableview/Drawer.tsx
  src/components/organisms/LazyDrawer/LazyDrawer.styled.tsx
  src/components/organisms/MessageBox/MessageBox.tsx
  src/redux/reducers/main/mainSlice.ts
  src/redux/services/clusterResourceWatcher.ts
  src/redux/thunks/applyResource.ts
Labels: size/M

#3571 refactor: ref selectors
  src/components/molecules/ChangeFiltersConfirmModal/ChangeFiltersConfirmModal.tsx
  src/components/molecules/Monaco/Monaco.tsx
  src/components/molecules/ProjectCard/ProjectCard.tsx
  src/components/organisms/ActionsPane/ActionsPane.tsx
  src/components/organisms/ActionsPane/ActionsPaneHeader.tsx
  src/components/organisms/FileCompareModal/FileCompareModal.tsx
  src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
  src/components/organisms/NewResourceWizard/NewResourceWizard.tsx
  src/hooks/fileTreeHooks/useFilterByFileOrFolder.tsx
  src/hooks/fileTreeHooks/useProcessing.tsx
  src/utils/hooks.ts
Labels: size/M

#3573 chore(release): 2.0.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S
